export declare const tokenCategories: {
    radius: {
        borderRadius: boolean;
        borderTopLeftRadius: boolean;
        borderTopRightRadius: boolean;
        borderBottomLeftRadius: boolean;
        borderBottomRightRadius: boolean;
        borderStartStartRadius: boolean;
        borderStartEndRadius: boolean;
        borderEndStartRadius: boolean;
        borderEndEndRadius: boolean;
    };
    size: {
        width: boolean;
        height: boolean;
        minWidth: boolean;
        minHeight: boolean;
        maxWidth: boolean;
        maxHeight: boolean;
        blockSize: boolean;
        minBlockSize: boolean;
        maxBlockSize: boolean;
        inlineSize: boolean;
        minInlineSize: boolean;
        maxInlineSize: boolean;
    };
    zIndex: {
        zIndex: boolean;
    };
    color: {
        outlineColor?: boolean | undefined;
        caretColor?: boolean | undefined;
        color: boolean;
        textDecorationColor: boolean;
        textShadowColor: boolean;
        backgroundColor: boolean;
        borderColor: boolean;
        borderBlockStartColor: boolean;
        borderBlockEndColor: boolean;
        borderBlockColor: boolean;
        borderBottomColor: boolean;
        borderInlineColor: boolean;
        borderInlineStartColor: boolean;
        borderInlineEndColor: boolean;
        borderTopColor: boolean;
        borderLeftColor: boolean;
        borderRightColor: boolean;
        borderEndColor: boolean;
        borderStartColor: boolean;
        shadowColor: boolean;
    };
};
export declare const stylePropsUnitless: {
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    gridTemplateColumns: boolean;
    gridTemplateAreas: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zIndex: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
};
export declare const stylePropsTransform: {
    x: boolean;
    y: boolean;
    scale: boolean;
    perspective: boolean;
    scaleX: boolean;
    scaleY: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
};
export declare const stylePropsView: {
    elevationAndroid?: boolean | undefined;
    transition?: boolean | undefined;
    textWrap?: boolean | undefined;
    backdropFilter?: boolean | undefined;
    background?: boolean | undefined;
    backgroundAttachment?: boolean | undefined;
    backgroundBlendMode?: boolean | undefined;
    backgroundClip?: boolean | undefined;
    backgroundColor: boolean;
    backgroundImage?: boolean | undefined;
    backgroundOrigin?: boolean | undefined;
    backgroundPosition?: boolean | undefined;
    backgroundRepeat?: boolean | undefined;
    backgroundSize?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderImage?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    boxSizing?: boolean | undefined;
    caretColor?: boolean | undefined;
    clipPath?: boolean | undefined;
    contain?: boolean | undefined;
    containerType?: boolean | undefined;
    content?: boolean | undefined;
    cursor?: boolean | undefined;
    float?: boolean | undefined;
    mask?: boolean | undefined;
    maskBorder?: boolean | undefined;
    maskBorderMode?: boolean | undefined;
    maskBorderOutset?: boolean | undefined;
    maskBorderRepeat?: boolean | undefined;
    maskBorderSlice?: boolean | undefined;
    maskBorderSource?: boolean | undefined;
    maskBorderWidth?: boolean | undefined;
    maskClip?: boolean | undefined;
    maskComposite?: boolean | undefined;
    maskImage?: boolean | undefined;
    maskMode?: boolean | undefined;
    maskOrigin?: boolean | undefined;
    maskPosition?: boolean | undefined;
    maskRepeat?: boolean | undefined;
    maskSize?: boolean | undefined;
    maskType?: boolean | undefined;
    mixBlendMode?: boolean | undefined;
    objectFit?: boolean | undefined;
    objectPosition?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    overflowBlock?: boolean | undefined;
    overflowInline?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    scrollbarWidth?: boolean | undefined;
    textEmphasis?: boolean | undefined;
    touchAction?: boolean | undefined;
    transformStyle?: boolean | undefined;
    userSelect?: boolean | undefined;
    boxShadow: boolean;
    filter: boolean;
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    gridTemplateColumns: boolean;
    gridTemplateAreas: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zIndex: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    borderRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderStartStartRadius: boolean;
    borderStartEndRadius: boolean;
    borderEndStartRadius: boolean;
    borderEndEndRadius: boolean;
    width: boolean;
    height: boolean;
    minWidth: boolean;
    minHeight: boolean;
    maxWidth: boolean;
    maxHeight: boolean;
    blockSize: boolean;
    minBlockSize: boolean;
    maxBlockSize: boolean;
    inlineSize: boolean;
    minInlineSize: boolean;
    maxInlineSize: boolean;
    outlineColor?: boolean | undefined;
    color: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    borderColor: boolean;
    borderBlockStartColor: boolean;
    borderBlockEndColor: boolean;
    borderBlockColor: boolean;
    borderBottomColor: boolean;
    borderInlineColor: boolean;
    borderInlineStartColor: boolean;
    borderInlineEndColor: boolean;
    borderTopColor: boolean;
    borderLeftColor: boolean;
    borderRightColor: boolean;
    borderEndColor: boolean;
    borderStartColor: boolean;
    shadowColor: boolean;
    backfaceVisibility: boolean;
    borderBottomEndRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderLeftWidth: boolean;
    borderRightWidth: boolean;
    borderBlockWidth: boolean;
    borderBlockEndWidth: boolean;
    borderBlockStartWidth: boolean;
    borderInlineWidth: boolean;
    borderInlineEndWidth: boolean;
    borderInlineStartWidth: boolean;
    borderStyle: boolean;
    borderBlockStyle: boolean;
    borderBlockEndStyle: boolean;
    borderBlockStartStyle: boolean;
    borderInlineStyle: boolean;
    borderInlineEndStyle: boolean;
    borderInlineStartStyle: boolean;
    borderTopEndRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    transformOrigin: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBlock: boolean;
    marginBlockEnd: boolean;
    marginBlockStart: boolean;
    marginInline: boolean;
    marginInlineStart: boolean;
    marginInlineEnd: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingInline: boolean;
    paddingBlock: boolean;
    paddingBlockStart: boolean;
    paddingInlineEnd: boolean;
    paddingInlineStart: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    inset: boolean;
    insetBlock: boolean;
    insetBlockEnd: boolean;
    insetBlockStart: boolean;
    insetInline: boolean;
    insetInlineEnd: boolean;
    insetInlineStart: boolean;
    direction: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const stylePropsTextOnly: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp?: boolean | undefined;
    WebkitBoxOrient?: boolean | undefined;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    userSelect: boolean;
    selectable: boolean;
    verticalAlign: boolean;
    color: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    fontVariant: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
};
export declare const stylePropsText: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp: boolean;
    WebkitBoxOrient?: boolean | undefined;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    userSelect: boolean;
    selectable: boolean;
    verticalAlign: boolean;
    color: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    fontVariant: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
    elevationAndroid?: boolean | undefined;
    transition?: boolean | undefined;
    textWrap?: boolean | undefined;
    backdropFilter?: boolean | undefined;
    background?: boolean | undefined;
    backgroundAttachment?: boolean | undefined;
    backgroundBlendMode?: boolean | undefined;
    backgroundClip?: boolean | undefined;
    backgroundColor: boolean;
    backgroundImage?: boolean | undefined;
    backgroundOrigin?: boolean | undefined;
    backgroundPosition?: boolean | undefined;
    backgroundRepeat?: boolean | undefined;
    backgroundSize?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderImage?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    boxSizing?: boolean | undefined;
    caretColor?: boolean | undefined;
    clipPath?: boolean | undefined;
    contain?: boolean | undefined;
    containerType?: boolean | undefined;
    content?: boolean | undefined;
    float?: boolean | undefined;
    mask?: boolean | undefined;
    maskBorder?: boolean | undefined;
    maskBorderMode?: boolean | undefined;
    maskBorderOutset?: boolean | undefined;
    maskBorderRepeat?: boolean | undefined;
    maskBorderSlice?: boolean | undefined;
    maskBorderSource?: boolean | undefined;
    maskBorderWidth?: boolean | undefined;
    maskClip?: boolean | undefined;
    maskComposite?: boolean | undefined;
    maskImage?: boolean | undefined;
    maskMode?: boolean | undefined;
    maskOrigin?: boolean | undefined;
    maskPosition?: boolean | undefined;
    maskRepeat?: boolean | undefined;
    maskSize?: boolean | undefined;
    maskType?: boolean | undefined;
    mixBlendMode?: boolean | undefined;
    objectFit?: boolean | undefined;
    objectPosition?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    overflowBlock?: boolean | undefined;
    overflowInline?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    scrollbarWidth?: boolean | undefined;
    textEmphasis?: boolean | undefined;
    touchAction?: boolean | undefined;
    transformStyle?: boolean | undefined;
    boxShadow: boolean;
    filter: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    gridTemplateColumns: boolean;
    gridTemplateAreas: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zIndex: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    borderRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderStartStartRadius: boolean;
    borderStartEndRadius: boolean;
    borderEndStartRadius: boolean;
    borderEndEndRadius: boolean;
    width: boolean;
    height: boolean;
    minWidth: boolean;
    minHeight: boolean;
    maxWidth: boolean;
    maxHeight: boolean;
    blockSize: boolean;
    minBlockSize: boolean;
    maxBlockSize: boolean;
    inlineSize: boolean;
    minInlineSize: boolean;
    maxInlineSize: boolean;
    outlineColor?: boolean | undefined;
    borderColor: boolean;
    borderBlockStartColor: boolean;
    borderBlockEndColor: boolean;
    borderBlockColor: boolean;
    borderBottomColor: boolean;
    borderInlineColor: boolean;
    borderInlineStartColor: boolean;
    borderInlineEndColor: boolean;
    borderTopColor: boolean;
    borderLeftColor: boolean;
    borderRightColor: boolean;
    borderEndColor: boolean;
    borderStartColor: boolean;
    shadowColor: boolean;
    backfaceVisibility: boolean;
    borderBottomEndRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderLeftWidth: boolean;
    borderRightWidth: boolean;
    borderBlockWidth: boolean;
    borderBlockEndWidth: boolean;
    borderBlockStartWidth: boolean;
    borderInlineWidth: boolean;
    borderInlineEndWidth: boolean;
    borderInlineStartWidth: boolean;
    borderStyle: boolean;
    borderBlockStyle: boolean;
    borderBlockEndStyle: boolean;
    borderBlockStartStyle: boolean;
    borderInlineStyle: boolean;
    borderInlineEndStyle: boolean;
    borderInlineStartStyle: boolean;
    borderTopEndRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    transformOrigin: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBlock: boolean;
    marginBlockEnd: boolean;
    marginBlockStart: boolean;
    marginInline: boolean;
    marginInlineStart: boolean;
    marginInlineEnd: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingInline: boolean;
    paddingBlock: boolean;
    paddingBlockStart: boolean;
    paddingInlineEnd: boolean;
    paddingInlineStart: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    inset: boolean;
    insetBlock: boolean;
    insetBlockEnd: boolean;
    insetBlockStart: boolean;
    insetInline: boolean;
    insetInlineEnd: boolean;
    insetInlineStart: boolean;
    direction: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const stylePropsAll: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp: boolean;
    WebkitBoxOrient?: boolean | undefined;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    userSelect: boolean;
    selectable: boolean;
    verticalAlign: boolean;
    color: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    fontVariant: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
    elevationAndroid?: boolean | undefined;
    transition?: boolean | undefined;
    textWrap?: boolean | undefined;
    backdropFilter?: boolean | undefined;
    background?: boolean | undefined;
    backgroundAttachment?: boolean | undefined;
    backgroundBlendMode?: boolean | undefined;
    backgroundClip?: boolean | undefined;
    backgroundColor: boolean;
    backgroundImage?: boolean | undefined;
    backgroundOrigin?: boolean | undefined;
    backgroundPosition?: boolean | undefined;
    backgroundRepeat?: boolean | undefined;
    backgroundSize?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderImage?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    boxSizing?: boolean | undefined;
    caretColor?: boolean | undefined;
    clipPath?: boolean | undefined;
    contain?: boolean | undefined;
    containerType?: boolean | undefined;
    content?: boolean | undefined;
    float?: boolean | undefined;
    mask?: boolean | undefined;
    maskBorder?: boolean | undefined;
    maskBorderMode?: boolean | undefined;
    maskBorderOutset?: boolean | undefined;
    maskBorderRepeat?: boolean | undefined;
    maskBorderSlice?: boolean | undefined;
    maskBorderSource?: boolean | undefined;
    maskBorderWidth?: boolean | undefined;
    maskClip?: boolean | undefined;
    maskComposite?: boolean | undefined;
    maskImage?: boolean | undefined;
    maskMode?: boolean | undefined;
    maskOrigin?: boolean | undefined;
    maskPosition?: boolean | undefined;
    maskRepeat?: boolean | undefined;
    maskSize?: boolean | undefined;
    maskType?: boolean | undefined;
    mixBlendMode?: boolean | undefined;
    objectFit?: boolean | undefined;
    objectPosition?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    overflowBlock?: boolean | undefined;
    overflowInline?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    scrollbarWidth?: boolean | undefined;
    textEmphasis?: boolean | undefined;
    touchAction?: boolean | undefined;
    transformStyle?: boolean | undefined;
    boxShadow: boolean;
    filter: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    gridTemplateColumns: boolean;
    gridTemplateAreas: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zIndex: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    borderRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderStartStartRadius: boolean;
    borderStartEndRadius: boolean;
    borderEndStartRadius: boolean;
    borderEndEndRadius: boolean;
    width: boolean;
    height: boolean;
    minWidth: boolean;
    minHeight: boolean;
    maxWidth: boolean;
    maxHeight: boolean;
    blockSize: boolean;
    minBlockSize: boolean;
    maxBlockSize: boolean;
    inlineSize: boolean;
    minInlineSize: boolean;
    maxInlineSize: boolean;
    outlineColor?: boolean | undefined;
    borderColor: boolean;
    borderBlockStartColor: boolean;
    borderBlockEndColor: boolean;
    borderBlockColor: boolean;
    borderBottomColor: boolean;
    borderInlineColor: boolean;
    borderInlineStartColor: boolean;
    borderInlineEndColor: boolean;
    borderTopColor: boolean;
    borderLeftColor: boolean;
    borderRightColor: boolean;
    borderEndColor: boolean;
    borderStartColor: boolean;
    shadowColor: boolean;
    backfaceVisibility: boolean;
    borderBottomEndRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderLeftWidth: boolean;
    borderRightWidth: boolean;
    borderBlockWidth: boolean;
    borderBlockEndWidth: boolean;
    borderBlockStartWidth: boolean;
    borderInlineWidth: boolean;
    borderInlineEndWidth: boolean;
    borderInlineStartWidth: boolean;
    borderStyle: boolean;
    borderBlockStyle: boolean;
    borderBlockEndStyle: boolean;
    borderBlockStartStyle: boolean;
    borderInlineStyle: boolean;
    borderInlineEndStyle: boolean;
    borderInlineStartStyle: boolean;
    borderTopEndRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    transformOrigin: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBlock: boolean;
    marginBlockEnd: boolean;
    marginBlockStart: boolean;
    marginInline: boolean;
    marginInlineStart: boolean;
    marginInlineEnd: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingInline: boolean;
    paddingBlock: boolean;
    paddingBlockStart: boolean;
    paddingInlineEnd: boolean;
    paddingInlineStart: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    inset: boolean;
    insetBlock: boolean;
    insetBlockEnd: boolean;
    insetBlockStart: boolean;
    insetInline: boolean;
    insetInlineEnd: boolean;
    insetInlineStart: boolean;
    direction: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const validPseudoKeys: {
    focusVisibleStyle?: boolean | undefined;
    enterStyle: boolean;
    exitStyle: boolean;
    hoverStyle: boolean;
    pressStyle: boolean;
    focusStyle: boolean;
    disabledStyle: boolean;
    focusWithinStyle: boolean;
};
export declare const validStyles: {
    elevationAndroid?: boolean | undefined;
    transition?: boolean | undefined;
    textWrap?: boolean | undefined;
    backdropFilter?: boolean | undefined;
    background?: boolean | undefined;
    backgroundAttachment?: boolean | undefined;
    backgroundBlendMode?: boolean | undefined;
    backgroundClip?: boolean | undefined;
    backgroundColor: boolean;
    backgroundImage?: boolean | undefined;
    backgroundOrigin?: boolean | undefined;
    backgroundPosition?: boolean | undefined;
    backgroundRepeat?: boolean | undefined;
    backgroundSize?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderImage?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    boxSizing?: boolean | undefined;
    caretColor?: boolean | undefined;
    clipPath?: boolean | undefined;
    contain?: boolean | undefined;
    containerType?: boolean | undefined;
    content?: boolean | undefined;
    cursor?: boolean | undefined;
    float?: boolean | undefined;
    mask?: boolean | undefined;
    maskBorder?: boolean | undefined;
    maskBorderMode?: boolean | undefined;
    maskBorderOutset?: boolean | undefined;
    maskBorderRepeat?: boolean | undefined;
    maskBorderSlice?: boolean | undefined;
    maskBorderSource?: boolean | undefined;
    maskBorderWidth?: boolean | undefined;
    maskClip?: boolean | undefined;
    maskComposite?: boolean | undefined;
    maskImage?: boolean | undefined;
    maskMode?: boolean | undefined;
    maskOrigin?: boolean | undefined;
    maskPosition?: boolean | undefined;
    maskRepeat?: boolean | undefined;
    maskSize?: boolean | undefined;
    maskType?: boolean | undefined;
    mixBlendMode?: boolean | undefined;
    objectFit?: boolean | undefined;
    objectPosition?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    overflowBlock?: boolean | undefined;
    overflowInline?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    scrollbarWidth?: boolean | undefined;
    textEmphasis?: boolean | undefined;
    touchAction?: boolean | undefined;
    transformStyle?: boolean | undefined;
    userSelect?: boolean | undefined;
    boxShadow: boolean;
    filter: boolean;
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    gridTemplateColumns: boolean;
    gridTemplateAreas: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zIndex: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    borderRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderStartStartRadius: boolean;
    borderStartEndRadius: boolean;
    borderEndStartRadius: boolean;
    borderEndEndRadius: boolean;
    width: boolean;
    height: boolean;
    minWidth: boolean;
    minHeight: boolean;
    maxWidth: boolean;
    maxHeight: boolean;
    blockSize: boolean;
    minBlockSize: boolean;
    maxBlockSize: boolean;
    inlineSize: boolean;
    minInlineSize: boolean;
    maxInlineSize: boolean;
    outlineColor?: boolean | undefined;
    color: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    borderColor: boolean;
    borderBlockStartColor: boolean;
    borderBlockEndColor: boolean;
    borderBlockColor: boolean;
    borderBottomColor: boolean;
    borderInlineColor: boolean;
    borderInlineStartColor: boolean;
    borderInlineEndColor: boolean;
    borderTopColor: boolean;
    borderLeftColor: boolean;
    borderRightColor: boolean;
    borderEndColor: boolean;
    borderStartColor: boolean;
    shadowColor: boolean;
    backfaceVisibility: boolean;
    borderBottomEndRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderLeftWidth: boolean;
    borderRightWidth: boolean;
    borderBlockWidth: boolean;
    borderBlockEndWidth: boolean;
    borderBlockStartWidth: boolean;
    borderInlineWidth: boolean;
    borderInlineEndWidth: boolean;
    borderInlineStartWidth: boolean;
    borderStyle: boolean;
    borderBlockStyle: boolean;
    borderBlockEndStyle: boolean;
    borderBlockStartStyle: boolean;
    borderInlineStyle: boolean;
    borderInlineEndStyle: boolean;
    borderInlineStartStyle: boolean;
    borderTopEndRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    transformOrigin: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBlock: boolean;
    marginBlockEnd: boolean;
    marginBlockStart: boolean;
    marginInline: boolean;
    marginInlineStart: boolean;
    marginInlineEnd: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingInline: boolean;
    paddingBlock: boolean;
    paddingBlockStart: boolean;
    paddingInlineEnd: boolean;
    paddingInlineStart: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    inset: boolean;
    insetBlock: boolean;
    insetBlockEnd: boolean;
    insetBlockStart: boolean;
    insetInline: boolean;
    insetInlineEnd: boolean;
    insetInlineStart: boolean;
    direction: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
//# sourceMappingURL=validStyleProps.d.ts.map