# This Dockerfile is used to run tests for the Tamagui monorepo in a clean environment
# If CI is failing you can run bun run test:docker on your own machine to debug

# syntax=docker/dockerfile:1.2

# Use an official Bun image
FROM oven/bun:1.2.22
ENV CI=true

# Install required dependencies
RUN apt-get update && apt-get install -y \
  bsdmainutils \
  grep \
  openssl \
  sed \
  xxd \
  && rm -rf /var/lib/apt/lists/*

# Copy the entire project into the Docker image
# Copy the local .git folder into the Docker image
COPY .git /.git

ARG CACHEBUST=1
RUN git clone --local /.git /repo
COPY .env /repo/.env

WORKDIR /repo

# Verify Bun version
RUN bun --version

# Install dependencies
RUN bun install

# Build JavaScript
RUN bun run build:js

# Install Playwright dependencies in a separate layer
RUN bunx playwright install-deps && bunx playwright install

# Run the tests
CMD bun run test
