# This Dockerfile is used to run tests for the Tamagui monorepo in a clean environment
# If CI is failing you can run yarn test:docker on your own machine to debug

# syntax=docker/dockerfile:1.2

# Use an official Node.js LTS runtime as a parent image
FROM node:20.17.0
ENV CI=true

# Install required dependencies
RUN apt-get update && apt-get install -y \
  bsdmainutils \
  grep \
  openssl \
  sed \
  xxd \
  && rm -rf /var/lib/apt/lists/*

# Install Yarn
RUN corepack enable && corepack prepare yarn@4.4.0 --activate

# Copy the entire project into the Docker image
# Copy the local .git folder into the Docker image
COPY .git /.git

ARG CACHEBUST=1 
RUN git clone --local /.git /repo
COPY .env /repo/.env

WORKDIR /repo

# Accept TRANSCRYPT_PASSWORD as a build argument
ARG TRANSCRYPT_PASSWORD
ENV TRANSCRYPT_PASSWORD=${TRANSCRYPT_PASSWORD}

RUN SHOULD_UNLOCK_GIT_CRYPT=1 ./scripts/unlock-repo.sh

# Verify Yarn version
RUN yarn --version

# Install dependencies
RUN yarn install

# Build JavaScript
RUN yarn build:js

# Install Playwright dependencies in a separate layer
RUN yarn playwright install-deps && yarn playwright install

# Run the tests
CMD yarn test
