export declare const shorthands: {
<<<<<<< HEAD
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bc: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly bg: "backgroundColor";
    readonly blc: "borderLeftColor";
    readonly bls: "borderLeftStyle";
    readonly blw: "borderLeftWidth";
    readonly boc: "borderColor";
    readonly boxs: "boxSizing";
    readonly boxsh: "boxShadow";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly col: "color";
    readonly cur: "cursor";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly ovx: "overflowX";
    readonly ovy: "overflowY";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pe: "pointerEvents";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ussel: "userSelect";
    readonly w: "width";
    readonly ww: "wordWrap";
    readonly zi: "zIndex";
=======
    ussel: "userSelect";
    cur: "cursor";
    pe: "pointerEvents";
    col: "color";
    ff: "fontFamily";
    fos: "fontSize";
    fost: "fontStyle";
    fow: "fontWeight";
    ls: "letterSpacing";
    lh: "lineHeight";
    ta: "textAlign";
    tt: "textTransform";
    ww: "wordWrap";
    ac: "alignContent";
    ai: "alignItems";
    als: "alignSelf";
    b: "bottom";
    bc: "backgroundColor";
    bg: "backgroundColor";
    bbc: "borderBottomColor";
    bblr: "borderBottomLeftRadius";
    bbrr: "borderBottomRightRadius";
    bbw: "borderBottomWidth";
    blc: "borderLeftColor";
    blw: "borderLeftWidth";
    boc: "borderColor";
    br: "borderRadius";
    bs: "borderStyle";
    brw: "borderRightWidth";
    brc: "borderRightColor";
    btc: "borderTopColor";
    btlr: "borderTopLeftRadius";
    btrr: "borderTopRightRadius";
    btw: "borderTopWidth";
    bw: "borderWidth";
    dsp: "display";
    f: "flex";
    fb: "flexBasis";
    fd: "flexDirection";
    fg: "flexGrow";
    fs: "flexShrink";
    fw: "flexWrap";
    h: "height";
    jc: "justifyContent";
    l: "left";
    m: "margin";
    mah: "maxHeight";
    maw: "maxWidth";
    mb: "marginBottom";
    mih: "minHeight";
    miw: "minWidth";
    ml: "marginLeft";
    mr: "marginRight";
    mt: "marginTop";
    mx: "marginHorizontal";
    my: "marginVertical";
    o: "opacity";
    ov: "overflow";
    p: "padding";
    pb: "paddingBottom";
    pl: "paddingLeft";
    pos: "position";
    pr: "paddingRight";
    pt: "paddingTop";
    px: "paddingHorizontal";
    py: "paddingVertical";
    r: "right";
    shac: "shadowColor";
    shar: "shadowRadius";
    shof: "shadowOffset";
    shop: "shadowOpacity";
    t: "top";
    w: "width";
    zi: "zIndex";
>>>>>>> 52fafa81c (refactor(shorthands): Remove invalid shorthands boxsh, bls)
};
//# sourceMappingURL=index.d.ts.map