export { amber as amberDark } from './dark/amber';
export { blue as blueDark } from './dark/blue';
export { bronze as bronzeDark } from './dark/bronze';
export { brown as brownDark } from './dark/brown';
export { crimson as crimsonDark } from './dark/crimson';
export { cyan as cyanDark } from './dark/cyan';
export { gold as goldDark } from './dark/gold';
export { grass as grassDark } from './dark/grass';
export { gray as grayDark } from './dark/gray';
export { green as greenDark } from './dark/green';
export { indigo as indigoDark } from './dark/indigo';
export { lime as limeDark } from './dark/lime';
export { mint as mintDark } from './dark/mint';
export { olive as oliveDark } from './dark/olive';
export { orange as orangeDark } from './dark/orange';
export { pink as pinkDark } from './dark/pink';
export { plum as plumDark } from './dark/plum';
export { purple as purpleDark } from './dark/purple';
export { mauve as mauveDark } from './dark/mauve';
export { red as redDark } from './dark/red';
export { sage as sageDark } from './dark/sage';
export { sand as sandDark } from './dark/sand';
export { sky as skyDark } from './dark/sky';
export { slate as slateDark } from './dark/slate';
export { teal as tealDark } from './dark/teal';
export { tomato as tomatoDark } from './dark/tomato';
export { violet as violetDark } from './dark/violet';
export { yellow as yellowDark } from './dark/yellow';
export { amberA as amberDarkA } from './dark/amberA';
export { blueA as blueDarkA } from './dark/blueA';
export { bronzeA as bronzeDarkA } from './dark/bronzeA';
export { brownA as brownDarkA } from './dark/brownA';
export { crimsonA as crimsonDarkA } from './dark/crimsonA';
export { cyanA as cyanDarkA } from './dark/cyanA';
export { goldA as goldDarkA } from './dark/goldA';
export { grassA as grassDarkA } from './dark/grassA';
export { grayA as grayDarkA } from './dark/grayA';
export { greenA as greenDarkA } from './dark/greenA';
export { indigoA as indigoDarkA } from './dark/indigoA';
export { limeA as limeDarkA } from './dark/limeA';
export { mintA as mintDarkA } from './dark/mintA';
export { oliveA as oliveDarkA } from './dark/oliveA';
export { orangeA as orangeDarkA } from './dark/orangeA';
export { pinkA as pinkDarkA } from './dark/pinkA';
export { plumA as plumDarkA } from './dark/plumA';
export { purpleA as purpleDarkA } from './dark/purpleA';
export { mauveA as mauveDarkA } from './dark/mauveA';
export { redA as redDarkA } from './dark/redA';
export { sageA as sageDarkA } from './dark/sageA';
export { sandA as sandDarkA } from './dark/sandA';
export { skyA as skyDarkA } from './dark/skyA';
export { slateA as slateDarkA } from './dark/slateA';
export { tealA as tealDarkA } from './dark/tealA';
export { tomatoA as tomatoDarkA } from './dark/tomatoA';
export { violetA as violetDarkA } from './dark/violetA';
export { yellowA as yellowDarkA } from './dark/yellowA';
export { amber } from './light/amber';
export { blue } from './light/blue';
export { bronze } from './light/bronze';
export { brown } from './light/brown';
export { crimson } from './light/crimson';
export { cyan } from './light/cyan';
export { gold } from './light/gold';
export { grass } from './light/grass';
export { gray } from './light/gray';
export { green } from './light/green';
export { indigo } from './light/indigo';
export { lime } from './light/lime';
export { mint } from './light/mint';
export { olive } from './light/olive';
export { orange } from './light/orange';
export { pink } from './light/pink';
export { plum } from './light/plum';
export { purple } from './light/purple';
export { mauve } from './light/mauve';
export { red } from './light/red';
export { sage } from './light/sage';
export { sand } from './light/sand';
export { sky } from './light/sky';
export { slate } from './light/slate';
export { teal } from './light/teal';
export { tomato } from './light/tomato';
export { violet } from './light/violet';
export { yellow } from './light/yellow';
export { amberA } from './light/amberA';
export { blueA } from './light/blueA';
export { bronzeA } from './light/bronzeA';
export { brownA } from './light/brownA';
export { crimsonA } from './light/crimsonA';
export { cyanA } from './light/cyanA';
export { goldA } from './light/goldA';
export { grassA } from './light/grassA';
export { grayA } from './light/grayA';
export { greenA } from './light/greenA';
export { indigoA } from './light/indigoA';
export { limeA } from './light/limeA';
export { mintA } from './light/mintA';
export { oliveA } from './light/oliveA';
export { orangeA } from './light/orangeA';
export { pinkA } from './light/pinkA';
export { plumA } from './light/plumA';
export { purpleA } from './light/purpleA';
export { mauveA } from './light/mauveA';
export { redA } from './light/redA';
export { sageA } from './light/sageA';
export { sandA } from './light/sandA';
export { skyA } from './light/skyA';
export { slateA } from './light/slateA';
export { tealA } from './light/tealA';
export { tomatoA } from './light/tomatoA';
export { violetA } from './light/violetA';
export { yellowA } from './light/yellowA';
export { blackA } from './blackA';
export { whiteA } from './whiteA';
export declare const colorNames: readonly ["blue", "gray", "green", "indigo", "orange", "pink", "purple", "red", "violet", "yellow", "teal"];
export declare const allLightColors: {
    teal1: string;
    teal2: string;
    teal3: string;
    teal4: string;
    teal5: string;
    teal6: string;
    teal7: string;
    teal8: string;
    teal9: string;
    teal10: string;
    teal11: string;
    teal12: string;
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    violet1: string;
    violet2: string;
    violet3: string;
    violet4: string;
    violet5: string;
    violet6: string;
    violet7: string;
    violet8: string;
    violet9: string;
    violet10: string;
    violet11: string;
    violet12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    indigo1: string;
    indigo2: string;
    indigo3: string;
    indigo4: string;
    indigo5: string;
    indigo6: string;
    indigo7: string;
    indigo8: string;
    indigo9: string;
    indigo10: string;
    indigo11: string;
    indigo12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    grayA1: string;
    grayA2: string;
    grayA3: string;
    grayA4: string;
    grayA5: string;
    grayA6: string;
    grayA7: string;
    grayA8: string;
    grayA9: string;
    grayA10: string;
    grayA11: string;
    grayA12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const allDarkColors: {
    teal1: string;
    teal2: string;
    teal3: string;
    teal4: string;
    teal5: string;
    teal6: string;
    teal7: string;
    teal8: string;
    teal9: string;
    teal10: string;
    teal11: string;
    teal12: string;
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    violet1: string;
    violet2: string;
    violet3: string;
    violet4: string;
    violet5: string;
    violet6: string;
    violet7: string;
    violet8: string;
    violet9: string;
    violet10: string;
    violet11: string;
    violet12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    indigo1: string;
    indigo2: string;
    indigo3: string;
    indigo4: string;
    indigo5: string;
    indigo6: string;
    indigo7: string;
    indigo8: string;
    indigo9: string;
    indigo10: string;
    indigo11: string;
    indigo12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    grayA1: string;
    grayA2: string;
    grayA3: string;
    grayA4: string;
    grayA5: string;
    grayA6: string;
    grayA7: string;
    grayA8: string;
    grayA9: string;
    grayA10: string;
    grayA11: string;
    grayA12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const darkColorsPostfixed: {
    teal1Dark: string;
    teal2Dark: string;
    teal3Dark: string;
    teal4Dark: string;
    teal5Dark: string;
    teal6Dark: string;
    teal7Dark: string;
    teal8Dark: string;
    teal9Dark: string;
    teal10Dark: string;
    teal11Dark: string;
    teal12Dark: string;
    yellow1Dark: string;
    yellow2Dark: string;
    yellow3Dark: string;
    yellow4Dark: string;
    yellow5Dark: string;
    yellow6Dark: string;
    yellow7Dark: string;
    yellow8Dark: string;
    yellow9Dark: string;
    yellow10Dark: string;
    yellow11Dark: string;
    yellow12Dark: string;
    violet1Dark: string;
    violet2Dark: string;
    violet3Dark: string;
    violet4Dark: string;
    violet5Dark: string;
    violet6Dark: string;
    violet7Dark: string;
    violet8Dark: string;
    violet9Dark: string;
    violet10Dark: string;
    violet11Dark: string;
    violet12Dark: string;
    red1Dark: string;
    red2Dark: string;
    red3Dark: string;
    red4Dark: string;
    red5Dark: string;
    red6Dark: string;
    red7Dark: string;
    red8Dark: string;
    red9Dark: string;
    red10Dark: string;
    red11Dark: string;
    red12Dark: string;
    purple1Dark: string;
    purple2Dark: string;
    purple3Dark: string;
    purple4Dark: string;
    purple5Dark: string;
    purple6Dark: string;
    purple7Dark: string;
    purple8Dark: string;
    purple9Dark: string;
    purple10Dark: string;
    purple11Dark: string;
    purple12Dark: string;
    pink1Dark: string;
    pink2Dark: string;
    pink3Dark: string;
    pink4Dark: string;
    pink5Dark: string;
    pink6Dark: string;
    pink7Dark: string;
    pink8Dark: string;
    pink9Dark: string;
    pink10Dark: string;
    pink11Dark: string;
    pink12Dark: string;
    orange1Dark: string;
    orange2Dark: string;
    orange3Dark: string;
    orange4Dark: string;
    orange5Dark: string;
    orange6Dark: string;
    orange7Dark: string;
    orange8Dark: string;
    orange9Dark: string;
    orange10Dark: string;
    orange11Dark: string;
    orange12Dark: string;
    indigo1Dark: string;
    indigo2Dark: string;
    indigo3Dark: string;
    indigo4Dark: string;
    indigo5Dark: string;
    indigo6Dark: string;
    indigo7Dark: string;
    indigo8Dark: string;
    indigo9Dark: string;
    indigo10Dark: string;
    indigo11Dark: string;
    indigo12Dark: string;
    green1Dark: string;
    green2Dark: string;
    green3Dark: string;
    green4Dark: string;
    green5Dark: string;
    green6Dark: string;
    green7Dark: string;
    green8Dark: string;
    green9Dark: string;
    green10Dark: string;
    green11Dark: string;
    green12Dark: string;
    grayA1Dark: string;
    grayA2Dark: string;
    grayA3Dark: string;
    grayA4Dark: string;
    grayA5Dark: string;
    grayA6Dark: string;
    grayA7Dark: string;
    grayA8Dark: string;
    grayA9Dark: string;
    grayA10Dark: string;
    grayA11Dark: string;
    grayA12Dark: string;
    gray1Dark: string;
    gray2Dark: string;
    gray3Dark: string;
    gray4Dark: string;
    gray5Dark: string;
    gray6Dark: string;
    gray7Dark: string;
    gray8Dark: string;
    gray9Dark: string;
    gray10Dark: string;
    gray11Dark: string;
    gray12Dark: string;
    blue1Dark: string;
    blue2Dark: string;
    blue3Dark: string;
    blue4Dark: string;
    blue5Dark: string;
    blue6Dark: string;
    blue7Dark: string;
    blue8Dark: string;
    blue9Dark: string;
    blue10Dark: string;
    blue11Dark: string;
    blue12Dark: string;
};
export declare type ColorNamesLight = keyof typeof allLightColors;
export declare type ColorNamesDark = keyof typeof allDarkColors;
export declare const colorNamesLight: ("teal1" | "teal2" | "teal3" | "teal4" | "teal5" | "teal6" | "teal7" | "teal8" | "teal9" | "teal10" | "teal11" | "teal12" | "yellow1" | "yellow2" | "yellow3" | "yellow4" | "yellow5" | "yellow6" | "yellow7" | "yellow8" | "yellow9" | "yellow10" | "yellow11" | "yellow12" | "violet1" | "violet2" | "violet3" | "violet4" | "violet5" | "violet6" | "violet7" | "violet8" | "violet9" | "violet10" | "violet11" | "violet12" | "red1" | "red2" | "red3" | "red4" | "red5" | "red6" | "red7" | "red8" | "red9" | "red10" | "red11" | "red12" | "purple1" | "purple2" | "purple3" | "purple4" | "purple5" | "purple6" | "purple7" | "purple8" | "purple9" | "purple10" | "purple11" | "purple12" | "pink1" | "pink2" | "pink3" | "pink4" | "pink5" | "pink6" | "pink7" | "pink8" | "pink9" | "pink10" | "pink11" | "pink12" | "orange1" | "orange2" | "orange3" | "orange4" | "orange5" | "orange6" | "orange7" | "orange8" | "orange9" | "orange10" | "orange11" | "orange12" | "indigo1" | "indigo2" | "indigo3" | "indigo4" | "indigo5" | "indigo6" | "indigo7" | "indigo8" | "indigo9" | "indigo10" | "indigo11" | "indigo12" | "green1" | "green2" | "green3" | "green4" | "green5" | "green6" | "green7" | "green8" | "green9" | "green10" | "green11" | "green12" | "grayA1" | "grayA2" | "grayA3" | "grayA4" | "grayA5" | "grayA6" | "grayA7" | "grayA8" | "grayA9" | "grayA10" | "grayA11" | "grayA12" | "gray1" | "gray2" | "gray3" | "gray4" | "gray5" | "gray6" | "gray7" | "gray8" | "gray9" | "gray10" | "gray11" | "gray12" | "blue1" | "blue2" | "blue3" | "blue4" | "blue5" | "blue6" | "blue7" | "blue8" | "blue9" | "blue10" | "blue11" | "blue12")[];
export declare const colorNamesDark: ("teal1" | "teal2" | "teal3" | "teal4" | "teal5" | "teal6" | "teal7" | "teal8" | "teal9" | "teal10" | "teal11" | "teal12" | "yellow1" | "yellow2" | "yellow3" | "yellow4" | "yellow5" | "yellow6" | "yellow7" | "yellow8" | "yellow9" | "yellow10" | "yellow11" | "yellow12" | "violet1" | "violet2" | "violet3" | "violet4" | "violet5" | "violet6" | "violet7" | "violet8" | "violet9" | "violet10" | "violet11" | "violet12" | "red1" | "red2" | "red3" | "red4" | "red5" | "red6" | "red7" | "red8" | "red9" | "red10" | "red11" | "red12" | "purple1" | "purple2" | "purple3" | "purple4" | "purple5" | "purple6" | "purple7" | "purple8" | "purple9" | "purple10" | "purple11" | "purple12" | "pink1" | "pink2" | "pink3" | "pink4" | "pink5" | "pink6" | "pink7" | "pink8" | "pink9" | "pink10" | "pink11" | "pink12" | "orange1" | "orange2" | "orange3" | "orange4" | "orange5" | "orange6" | "orange7" | "orange8" | "orange9" | "orange10" | "orange11" | "orange12" | "indigo1" | "indigo2" | "indigo3" | "indigo4" | "indigo5" | "indigo6" | "indigo7" | "indigo8" | "indigo9" | "indigo10" | "indigo11" | "indigo12" | "green1" | "green2" | "green3" | "green4" | "green5" | "green6" | "green7" | "green8" | "green9" | "green10" | "green11" | "green12" | "grayA1" | "grayA2" | "grayA3" | "grayA4" | "grayA5" | "grayA6" | "grayA7" | "grayA8" | "grayA9" | "grayA10" | "grayA11" | "grayA12" | "gray1" | "gray2" | "gray3" | "gray4" | "gray5" | "gray6" | "gray7" | "gray8" | "gray9" | "gray10" | "gray11" | "gray12" | "blue1" | "blue2" | "blue3" | "blue4" | "blue5" | "blue6" | "blue7" | "blue8" | "blue9" | "blue10" | "blue11" | "blue12")[];
//# sourceMappingURL=index.d.ts.map