name: Release

on:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  deploy-site:
    name: Deploy site
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install
        with:
          transcrypt_password: ${{ secrets.transcrypt_password }}

      - name: Build Site
        shell: bash
        run: |
          yarn --cwd apps/site ci:build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./apps/site/out
          cname: tamagui.dev
