compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs
