compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 00959c0d2a5826bc669416a83428f711bbd22a02aa6534f07749b3d806ab35b9d66352f0c967fbd2b4e03cdadc31193af7dd403dd359c1a897d97ff60a358adc
    path: .yarn/plugins/correct-yarn-formatting.cjs
    spec: "https://raw.githubusercontent.com/HanseltimeIndustries/correct-yarn-formatting/v1.0.2/lib/index.js"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
