compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: dd1402820c9f1be4f23995511109ef5110d44502498f59e7f637d6771bce032aafffba0042842f4c9cd3ea5fc4faa0cafdad023cfbd554aa2f1f4bb00711b3fb
    path: .yarn/plugins/correct-yarn-formatting.cjs
    spec: "https://raw.githubusercontent.com/HanseltimeIndustries/correct-yarn-formatting/v1.0.1/lib/index.js"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
