packages:
  - "./code/compiler/**/*"
  - "./code/core/**/*"
  - "./code/demos"
  - "./code/kitchen-sink"
  - "./code/kitchen-sink-go"
  - "./code/kitchen-sink-shared"
  - "./code/starters/*"
  - "./code/tests/**/*"
  - "./code/sandbox"
  - "./code/packages/**/*"
  - "./code/tamagui.dev"
  - "./code/ui/**/*"
