/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 /Users/n8/tamagui/apps/site/public/takeout.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/takeout.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pack.geometry} material={materials['Chinese_Takeout_Box_chinese.002']} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.handle.geometry} material={materials['Chinese_Takeout_Box_chinese.002']} rotation={[0, 1.571, 0]} />
    </group>
  )
}

useGLTF.preload('/takeout.gltf')
