process.env.TAMAGUI_COMPILE_PROCESS = '1'

export { TamaguiOptions } from './types.js'
export { createExtractor } from './extractor/createExtractor.js'
export { literalToAst } from './extractor/literalToAst.js'
export * from './constants.js'
export * from './extractor/extractToClassNames.js'
export * from './extractor/extractHelpers.js'
export * from '@tamagui/patch-rnw'
export * from './extractor/loadTamagui.js'
export * from './require.js'
export * from './getPragmaOptions.js'
