import { Variable } from '@tamagui/core';
export declare const colorSchemes: readonly [{
    readonly name: "blue";
    readonly colors: {
        blue1: string;
        blue2: string;
        blue3: string;
        blue4: string;
        blue5: string;
        blue6: string;
        blue7: string;
        blue8: string;
        blue9: string;
        blue10: string;
        blue11: string;
        blue12: string;
    };
    readonly darkColors: {
        blue1: string;
        blue2: string;
        blue3: string;
        blue4: string;
        blue5: string;
        blue6: string;
        blue7: string;
        blue8: string;
        blue9: string;
        blue10: string;
        blue11: string;
        blue12: string;
    };
}, {
    readonly name: "gray";
    readonly colors: {
        gray1: string;
        gray2: string;
        gray3: string;
        gray4: string;
        gray5: string;
        gray6: string;
        gray7: string;
        gray8: string;
        gray9: string;
        gray10: string;
        gray11: string;
        gray12: string;
    };
    readonly darkColors: {
        gray1: string;
        gray2: string;
        gray3: string;
        gray4: string;
        gray5: string;
        gray6: string;
        gray7: string;
        gray8: string;
        gray9: string;
        gray10: string;
        gray11: string;
        gray12: string;
    };
}, {
    readonly name: "green";
    readonly colors: {
        green1: string;
        green2: string;
        green3: string;
        green4: string;
        green5: string;
        green6: string;
        green7: string;
        green8: string;
        green9: string;
        green10: string;
        green11: string;
        green12: string;
    };
    readonly darkColors: {
        green1: string;
        green2: string;
        green3: string;
        green4: string;
        green5: string;
        green6: string;
        green7: string;
        green8: string;
        green9: string;
        green10: string;
        green11: string;
        green12: string;
    };
}, {
    readonly name: "indigo";
    readonly colors: {
        indigo1: string;
        indigo2: string;
        indigo3: string;
        indigo4: string;
        indigo5: string;
        indigo6: string;
        indigo7: string;
        indigo8: string;
        indigo9: string;
        indigo10: string;
        indigo11: string;
        indigo12: string;
    };
    readonly darkColors: {
        indigo1: string;
        indigo2: string;
        indigo3: string;
        indigo4: string;
        indigo5: string;
        indigo6: string;
        indigo7: string;
        indigo8: string;
        indigo9: string;
        indigo10: string;
        indigo11: string;
        indigo12: string;
    };
}, {
    readonly name: "orange";
    readonly colors: {
        orange1: string;
        orange2: string;
        orange3: string;
        orange4: string;
        orange5: string;
        orange6: string;
        orange7: string;
        orange8: string;
        orange9: string;
        orange10: string;
        orange11: string;
        orange12: string;
    };
    readonly darkColors: {
        orange1: string;
        orange2: string;
        orange3: string;
        orange4: string;
        orange5: string;
        orange6: string;
        orange7: string;
        orange8: string;
        orange9: string;
        orange10: string;
        orange11: string;
        orange12: string;
    };
}, {
    readonly name: "pink";
    readonly colors: {
        pink1: string;
        pink2: string;
        pink3: string;
        pink4: string;
        pink5: string;
        pink6: string;
        pink7: string;
        pink8: string;
        pink9: string;
        pink10: string;
        pink11: string;
        pink12: string;
    };
    readonly darkColors: {
        pink1: string;
        pink2: string;
        pink3: string;
        pink4: string;
        pink5: string;
        pink6: string;
        pink7: string;
        pink8: string;
        pink9: string;
        pink10: string;
        pink11: string;
        pink12: string;
    };
}, {
    readonly name: "purple";
    readonly colors: {
        purple1: string;
        purple2: string;
        purple3: string;
        purple4: string;
        purple5: string;
        purple6: string;
        purple7: string;
        purple8: string;
        purple9: string;
        purple10: string;
        purple11: string;
        purple12: string;
    };
    readonly darkColors: {
        purple1: string;
        purple2: string;
        purple3: string;
        purple4: string;
        purple5: string;
        purple6: string;
        purple7: string;
        purple8: string;
        purple9: string;
        purple10: string;
        purple11: string;
        purple12: string;
    };
}, {
    readonly name: "red";
    readonly colors: {
        red1: string;
        red2: string;
        red3: string;
        red4: string;
        red5: string;
        red6: string;
        red7: string;
        red8: string;
        red9: string;
        red10: string;
        red11: string;
        red12: string;
    };
    readonly darkColors: {
        red1: string;
        red2: string;
        red3: string;
        red4: string;
        red5: string;
        red6: string;
        red7: string;
        red8: string;
        red9: string;
        red10: string;
        red11: string;
        red12: string;
    };
}, {
    readonly name: "violet";
    readonly colors: {
        violet1: string;
        violet2: string;
        violet3: string;
        violet4: string;
        violet5: string;
        violet6: string;
        violet7: string;
        violet8: string;
        violet9: string;
        violet10: string;
        violet11: string;
        violet12: string;
    };
    readonly darkColors: {
        violet1: string;
        violet2: string;
        violet3: string;
        violet4: string;
        violet5: string;
        violet6: string;
        violet7: string;
        violet8: string;
        violet9: string;
        violet10: string;
        violet11: string;
        violet12: string;
    };
}, {
    readonly name: "yellow";
    readonly colors: {
        yellow1: string;
        yellow2: string;
        yellow3: string;
        yellow4: string;
        yellow5: string;
        yellow6: string;
        yellow7: string;
        yellow8: string;
        yellow9: string;
        yellow10: string;
        yellow11: string;
        yellow12: string;
    };
    readonly darkColors: {
        yellow1: string;
        yellow2: string;
        yellow3: string;
        yellow4: string;
        yellow5: string;
        yellow6: string;
        yellow7: string;
        yellow8: string;
        yellow9: string;
        yellow10: string;
        yellow11: string;
        yellow12: string;
    };
}, {
    readonly name: "teal";
    readonly colors: {
        teal1: string;
        teal2: string;
        teal3: string;
        teal4: string;
        teal5: string;
        teal6: string;
        teal7: string;
        teal8: string;
        teal9: string;
        teal10: string;
        teal11: string;
        teal12: string;
    };
    readonly darkColors: {
        teal1: string;
        teal2: string;
        teal3: string;
        teal4: string;
        teal5: string;
        teal6: string;
        teal7: string;
        teal8: string;
        teal9: string;
        teal10: string;
        teal11: string;
        teal12: string;
    };
}, {
    readonly name: "lime";
    readonly colors: {
        lime1: string;
        lime2: string;
        lime3: string;
        lime4: string;
        lime5: string;
        lime6: string;
        lime7: string;
        lime8: string;
        lime9: string;
        lime10: string;
        lime11: string;
        lime12: string;
    };
    readonly darkColors: {
        lime1: string;
        lime2: string;
        lime3: string;
        lime4: string;
        lime5: string;
        lime6: string;
        lime7: string;
        lime8: string;
        lime9: string;
        lime10: string;
        lime11: string;
        lime12: string;
    };
}, {
    readonly name: "brown";
    readonly colors: {
        brown1: string;
        brown2: string;
        brown3: string;
        brown4: string;
        brown5: string;
        brown6: string;
        brown7: string;
        brown8: string;
        brown9: string;
        brown10: string;
        brown11: string;
        brown12: string;
    };
    readonly darkColors: {
        brown1: string;
        brown2: string;
        brown3: string;
        brown4: string;
        brown5: string;
        brown6: string;
        brown7: string;
        brown8: string;
        brown9: string;
        brown10: string;
        brown11: string;
        brown12: string;
    };
}];
export declare type ColorNames = typeof colorSchemes[number]['name'];
export declare const lightGradient: (string | Variable)[];
export declare const darkGradient: string[];
declare const baseThemes: {
    dark: any;
    dark_active: any;
    dark_Card: any;
    dark_Button: any;
    dark_alt1: any;
    dark_alt4: any;
    dark_alt2: any;
    dark_alt3: any;
    dark_darker: any;
    light: any;
    light_active: any;
    light_Card: any;
    light_Button: any;
    light_alt1: any;
    light_alt4: any;
    light_alt2: any;
    light_alt3: any;
    light_darker: any;
};
declare const allThemes: {
    readonly dark_outline: any;
    readonly light_outline: any;
    readonly blue: any;
    readonly gray: any;
    readonly green: any;
    readonly indigo: any;
    readonly orange: any;
    readonly pink: any;
    readonly purple: any;
    readonly red: any;
    readonly violet: any;
    readonly yellow: any;
    readonly teal: any;
    readonly lime: any;
    readonly brown: any;
    readonly light_blue_alt1: any;
    readonly light_blue_alt4: any;
    readonly light_blue_alt2: any;
    readonly light_blue_alt3: any;
    readonly light_gray_alt1: any;
    readonly light_gray_alt4: any;
    readonly light_gray_alt2: any;
    readonly light_gray_alt3: any;
    readonly light_green_alt1: any;
    readonly light_green_alt4: any;
    readonly light_green_alt2: any;
    readonly light_green_alt3: any;
    readonly light_indigo_alt1: any;
    readonly light_indigo_alt4: any;
    readonly light_indigo_alt2: any;
    readonly light_indigo_alt3: any;
    readonly light_orange_alt1: any;
    readonly light_orange_alt4: any;
    readonly light_orange_alt2: any;
    readonly light_orange_alt3: any;
    readonly light_pink_alt1: any;
    readonly light_pink_alt4: any;
    readonly light_pink_alt2: any;
    readonly light_pink_alt3: any;
    readonly light_purple_alt1: any;
    readonly light_purple_alt4: any;
    readonly light_purple_alt2: any;
    readonly light_purple_alt3: any;
    readonly light_red_alt1: any;
    readonly light_red_alt4: any;
    readonly light_red_alt2: any;
    readonly light_red_alt3: any;
    readonly light_violet_alt1: any;
    readonly light_violet_alt4: any;
    readonly light_violet_alt2: any;
    readonly light_violet_alt3: any;
    readonly light_yellow_alt1: any;
    readonly light_yellow_alt4: any;
    readonly light_yellow_alt2: any;
    readonly light_yellow_alt3: any;
    readonly light_teal_alt1: any;
    readonly light_teal_alt4: any;
    readonly light_teal_alt2: any;
    readonly light_teal_alt3: any;
    readonly light_lime_alt1: any;
    readonly light_lime_alt4: any;
    readonly light_lime_alt2: any;
    readonly light_lime_alt3: any;
    readonly light_brown_alt1: any;
    readonly light_brown_alt4: any;
    readonly light_brown_alt2: any;
    readonly light_brown_alt3: any;
    readonly dark_blue_alt1: any;
    readonly dark_blue_alt4: any;
    readonly dark_blue_alt2: any;
    readonly dark_blue_alt3: any;
    readonly dark_gray_alt1: any;
    readonly dark_gray_alt4: any;
    readonly dark_gray_alt2: any;
    readonly dark_gray_alt3: any;
    readonly dark_green_alt1: any;
    readonly dark_green_alt4: any;
    readonly dark_green_alt2: any;
    readonly dark_green_alt3: any;
    readonly dark_indigo_alt1: any;
    readonly dark_indigo_alt4: any;
    readonly dark_indigo_alt2: any;
    readonly dark_indigo_alt3: any;
    readonly dark_orange_alt1: any;
    readonly dark_orange_alt4: any;
    readonly dark_orange_alt2: any;
    readonly dark_orange_alt3: any;
    readonly dark_pink_alt1: any;
    readonly dark_pink_alt4: any;
    readonly dark_pink_alt2: any;
    readonly dark_pink_alt3: any;
    readonly dark_purple_alt1: any;
    readonly dark_purple_alt4: any;
    readonly dark_purple_alt2: any;
    readonly dark_purple_alt3: any;
    readonly dark_red_alt1: any;
    readonly dark_red_alt4: any;
    readonly dark_red_alt2: any;
    readonly dark_red_alt3: any;
    readonly dark_violet_alt1: any;
    readonly dark_violet_alt4: any;
    readonly dark_violet_alt2: any;
    readonly dark_violet_alt3: any;
    readonly dark_yellow_alt1: any;
    readonly dark_yellow_alt4: any;
    readonly dark_yellow_alt2: any;
    readonly dark_yellow_alt3: any;
    readonly dark_teal_alt1: any;
    readonly dark_teal_alt4: any;
    readonly dark_teal_alt2: any;
    readonly dark_teal_alt3: any;
    readonly dark_lime_alt1: any;
    readonly dark_lime_alt4: any;
    readonly dark_lime_alt2: any;
    readonly dark_lime_alt3: any;
    readonly dark_brown_alt1: any;
    readonly dark_brown_alt4: any;
    readonly dark_brown_alt2: any;
    readonly dark_brown_alt3: any;
    readonly dark: any;
    readonly dark_active: any;
    readonly dark_Card: any;
    readonly dark_Button: any;
    readonly dark_alt1: any;
    readonly dark_alt4: any;
    readonly dark_alt2: any;
    readonly dark_alt3: any;
    readonly dark_darker: any;
    readonly light: any;
    readonly light_active: any;
    readonly light_Card: any;
    readonly light_Button: any;
    readonly light_alt1: any;
    readonly light_alt4: any;
    readonly light_alt2: any;
    readonly light_alt3: any;
    readonly light_darker: any;
};
export declare const themes: {
    [key in keyof typeof allThemes]: typeof baseThemes['light'];
};
export {};
//# sourceMappingURL=themes.d.ts.map