import { Variable } from '@tamagui/core';
export declare const size: {
    0: number;
    0.25: number;
    0.5: number;
    0.75: number;
    1: number;
    1.5: number;
    2: number;
    2.5: number;
    3: number;
    3.5: number;
    4: number;
    true: number;
    4.5: number;
    5: number;
    5.5: number;
    6: number;
    6.5: number;
    7: number;
    7.6: number;
    8: number;
    8.5: number;
    9: number;
    9.5: number;
    10: number;
    11: number;
    12: number;
    13: number;
    14: number;
    15: number;
    16: number;
    17: number;
    18: number;
    19: number;
    20: number;
};
declare type Sizes = typeof size;
declare type SizeKeys = `${keyof Sizes}`;
export declare const space: {
    [Key in `-${SizeKeys}` | SizeKeys]: Key extends keyof Sizes ? Sizes[Key] : number;
};
export declare const zIndex: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
export declare const darkColors: {
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const lightColors: {
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const color: {
    yellow1Dark: string | Variable<string>;
    yellow2Dark: string | Variable<string>;
    yellow3Dark: string | Variable<string>;
    yellow4Dark: string | Variable<string>;
    yellow5Dark: string | Variable<string>;
    yellow6Dark: string | Variable<string>;
    yellow7Dark: string | Variable<string>;
    yellow8Dark: string | Variable<string>;
    yellow9Dark: string | Variable<string>;
    yellow10Dark: string | Variable<string>;
    yellow11Dark: string | Variable<string>;
    yellow12Dark: string | Variable<string>;
    red1Dark: string | Variable<string>;
    red2Dark: string | Variable<string>;
    red3Dark: string | Variable<string>;
    red4Dark: string | Variable<string>;
    red5Dark: string | Variable<string>;
    red6Dark: string | Variable<string>;
    red7Dark: string | Variable<string>;
    red8Dark: string | Variable<string>;
    red9Dark: string | Variable<string>;
    red10Dark: string | Variable<string>;
    red11Dark: string | Variable<string>;
    red12Dark: string | Variable<string>;
    purple1Dark: string | Variable<string>;
    purple2Dark: string | Variable<string>;
    purple3Dark: string | Variable<string>;
    purple4Dark: string | Variable<string>;
    purple5Dark: string | Variable<string>;
    purple6Dark: string | Variable<string>;
    purple7Dark: string | Variable<string>;
    purple8Dark: string | Variable<string>;
    purple9Dark: string | Variable<string>;
    purple10Dark: string | Variable<string>;
    purple11Dark: string | Variable<string>;
    purple12Dark: string | Variable<string>;
    pink1Dark: string | Variable<string>;
    pink2Dark: string | Variable<string>;
    pink3Dark: string | Variable<string>;
    pink4Dark: string | Variable<string>;
    pink5Dark: string | Variable<string>;
    pink6Dark: string | Variable<string>;
    pink7Dark: string | Variable<string>;
    pink8Dark: string | Variable<string>;
    pink9Dark: string | Variable<string>;
    pink10Dark: string | Variable<string>;
    pink11Dark: string | Variable<string>;
    pink12Dark: string | Variable<string>;
    orange1Dark: string | Variable<string>;
    orange2Dark: string | Variable<string>;
    orange3Dark: string | Variable<string>;
    orange4Dark: string | Variable<string>;
    orange5Dark: string | Variable<string>;
    orange6Dark: string | Variable<string>;
    orange7Dark: string | Variable<string>;
    orange8Dark: string | Variable<string>;
    orange9Dark: string | Variable<string>;
    orange10Dark: string | Variable<string>;
    orange11Dark: string | Variable<string>;
    orange12Dark: string | Variable<string>;
    green1Dark: string | Variable<string>;
    green2Dark: string | Variable<string>;
    green3Dark: string | Variable<string>;
    green4Dark: string | Variable<string>;
    green5Dark: string | Variable<string>;
    green6Dark: string | Variable<string>;
    green7Dark: string | Variable<string>;
    green8Dark: string | Variable<string>;
    green9Dark: string | Variable<string>;
    green10Dark: string | Variable<string>;
    green11Dark: string | Variable<string>;
    green12Dark: string | Variable<string>;
    gray1Dark: string | Variable<string>;
    gray2Dark: string | Variable<string>;
    gray3Dark: string | Variable<string>;
    gray4Dark: string | Variable<string>;
    gray5Dark: string | Variable<string>;
    gray6Dark: string | Variable<string>;
    gray7Dark: string | Variable<string>;
    gray8Dark: string | Variable<string>;
    gray9Dark: string | Variable<string>;
    gray10Dark: string | Variable<string>;
    gray11Dark: string | Variable<string>;
    gray12Dark: string | Variable<string>;
    blue1Dark: string | Variable<string>;
    blue2Dark: string | Variable<string>;
    blue3Dark: string | Variable<string>;
    blue4Dark: string | Variable<string>;
    blue5Dark: string | Variable<string>;
    blue6Dark: string | Variable<string>;
    blue7Dark: string | Variable<string>;
    blue8Dark: string | Variable<string>;
    blue9Dark: string | Variable<string>;
    blue10Dark: string | Variable<string>;
    blue11Dark: string | Variable<string>;
    blue12Dark: string | Variable<string>;
    yellow1Light: string | Variable<string>;
    yellow2Light: string | Variable<string>;
    yellow3Light: string | Variable<string>;
    yellow4Light: string | Variable<string>;
    yellow5Light: string | Variable<string>;
    yellow6Light: string | Variable<string>;
    yellow7Light: string | Variable<string>;
    yellow8Light: string | Variable<string>;
    yellow9Light: string | Variable<string>;
    yellow10Light: string | Variable<string>;
    yellow11Light: string | Variable<string>;
    yellow12Light: string | Variable<string>;
    red1Light: string | Variable<string>;
    red2Light: string | Variable<string>;
    red3Light: string | Variable<string>;
    red4Light: string | Variable<string>;
    red5Light: string | Variable<string>;
    red6Light: string | Variable<string>;
    red7Light: string | Variable<string>;
    red8Light: string | Variable<string>;
    red9Light: string | Variable<string>;
    red10Light: string | Variable<string>;
    red11Light: string | Variable<string>;
    red12Light: string | Variable<string>;
    purple1Light: string | Variable<string>;
    purple2Light: string | Variable<string>;
    purple3Light: string | Variable<string>;
    purple4Light: string | Variable<string>;
    purple5Light: string | Variable<string>;
    purple6Light: string | Variable<string>;
    purple7Light: string | Variable<string>;
    purple8Light: string | Variable<string>;
    purple9Light: string | Variable<string>;
    purple10Light: string | Variable<string>;
    purple11Light: string | Variable<string>;
    purple12Light: string | Variable<string>;
    pink1Light: string | Variable<string>;
    pink2Light: string | Variable<string>;
    pink3Light: string | Variable<string>;
    pink4Light: string | Variable<string>;
    pink5Light: string | Variable<string>;
    pink6Light: string | Variable<string>;
    pink7Light: string | Variable<string>;
    pink8Light: string | Variable<string>;
    pink9Light: string | Variable<string>;
    pink10Light: string | Variable<string>;
    pink11Light: string | Variable<string>;
    pink12Light: string | Variable<string>;
    orange1Light: string | Variable<string>;
    orange2Light: string | Variable<string>;
    orange3Light: string | Variable<string>;
    orange4Light: string | Variable<string>;
    orange5Light: string | Variable<string>;
    orange6Light: string | Variable<string>;
    orange7Light: string | Variable<string>;
    orange8Light: string | Variable<string>;
    orange9Light: string | Variable<string>;
    orange10Light: string | Variable<string>;
    orange11Light: string | Variable<string>;
    orange12Light: string | Variable<string>;
    green1Light: string | Variable<string>;
    green2Light: string | Variable<string>;
    green3Light: string | Variable<string>;
    green4Light: string | Variable<string>;
    green5Light: string | Variable<string>;
    green6Light: string | Variable<string>;
    green7Light: string | Variable<string>;
    green8Light: string | Variable<string>;
    green9Light: string | Variable<string>;
    green10Light: string | Variable<string>;
    green11Light: string | Variable<string>;
    green12Light: string | Variable<string>;
    gray1Light: string | Variable<string>;
    gray2Light: string | Variable<string>;
    gray3Light: string | Variable<string>;
    gray4Light: string | Variable<string>;
    gray5Light: string | Variable<string>;
    gray6Light: string | Variable<string>;
    gray7Light: string | Variable<string>;
    gray8Light: string | Variable<string>;
    gray9Light: string | Variable<string>;
    gray10Light: string | Variable<string>;
    gray11Light: string | Variable<string>;
    gray12Light: string | Variable<string>;
    blue1Light: string | Variable<string>;
    blue2Light: string | Variable<string>;
    blue3Light: string | Variable<string>;
    blue4Light: string | Variable<string>;
    blue5Light: string | Variable<string>;
    blue6Light: string | Variable<string>;
    blue7Light: string | Variable<string>;
    blue8Light: string | Variable<string>;
    blue9Light: string | Variable<string>;
    blue10Light: string | Variable<string>;
    blue11Light: string | Variable<string>;
    blue12Light: string | Variable<string>;
};
export declare const radius: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
};
export declare const tokens: {
    color: {
        yellow1Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow2Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow3Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow4Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow5Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow6Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow7Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow8Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow9Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow10Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow11Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow12Dark: Variable<import("@tamagui/core").VariableValue>;
        red1Dark: Variable<import("@tamagui/core").VariableValue>;
        red2Dark: Variable<import("@tamagui/core").VariableValue>;
        red3Dark: Variable<import("@tamagui/core").VariableValue>;
        red4Dark: Variable<import("@tamagui/core").VariableValue>;
        red5Dark: Variable<import("@tamagui/core").VariableValue>;
        red6Dark: Variable<import("@tamagui/core").VariableValue>;
        red7Dark: Variable<import("@tamagui/core").VariableValue>;
        red8Dark: Variable<import("@tamagui/core").VariableValue>;
        red9Dark: Variable<import("@tamagui/core").VariableValue>;
        red10Dark: Variable<import("@tamagui/core").VariableValue>;
        red11Dark: Variable<import("@tamagui/core").VariableValue>;
        red12Dark: Variable<import("@tamagui/core").VariableValue>;
        purple1Dark: Variable<import("@tamagui/core").VariableValue>;
        purple2Dark: Variable<import("@tamagui/core").VariableValue>;
        purple3Dark: Variable<import("@tamagui/core").VariableValue>;
        purple4Dark: Variable<import("@tamagui/core").VariableValue>;
        purple5Dark: Variable<import("@tamagui/core").VariableValue>;
        purple6Dark: Variable<import("@tamagui/core").VariableValue>;
        purple7Dark: Variable<import("@tamagui/core").VariableValue>;
        purple8Dark: Variable<import("@tamagui/core").VariableValue>;
        purple9Dark: Variable<import("@tamagui/core").VariableValue>;
        purple10Dark: Variable<import("@tamagui/core").VariableValue>;
        purple11Dark: Variable<import("@tamagui/core").VariableValue>;
        purple12Dark: Variable<import("@tamagui/core").VariableValue>;
        pink1Dark: Variable<import("@tamagui/core").VariableValue>;
        pink2Dark: Variable<import("@tamagui/core").VariableValue>;
        pink3Dark: Variable<import("@tamagui/core").VariableValue>;
        pink4Dark: Variable<import("@tamagui/core").VariableValue>;
        pink5Dark: Variable<import("@tamagui/core").VariableValue>;
        pink6Dark: Variable<import("@tamagui/core").VariableValue>;
        pink7Dark: Variable<import("@tamagui/core").VariableValue>;
        pink8Dark: Variable<import("@tamagui/core").VariableValue>;
        pink9Dark: Variable<import("@tamagui/core").VariableValue>;
        pink10Dark: Variable<import("@tamagui/core").VariableValue>;
        pink11Dark: Variable<import("@tamagui/core").VariableValue>;
        pink12Dark: Variable<import("@tamagui/core").VariableValue>;
        orange1Dark: Variable<import("@tamagui/core").VariableValue>;
        orange2Dark: Variable<import("@tamagui/core").VariableValue>;
        orange3Dark: Variable<import("@tamagui/core").VariableValue>;
        orange4Dark: Variable<import("@tamagui/core").VariableValue>;
        orange5Dark: Variable<import("@tamagui/core").VariableValue>;
        orange6Dark: Variable<import("@tamagui/core").VariableValue>;
        orange7Dark: Variable<import("@tamagui/core").VariableValue>;
        orange8Dark: Variable<import("@tamagui/core").VariableValue>;
        orange9Dark: Variable<import("@tamagui/core").VariableValue>;
        orange10Dark: Variable<import("@tamagui/core").VariableValue>;
        orange11Dark: Variable<import("@tamagui/core").VariableValue>;
        orange12Dark: Variable<import("@tamagui/core").VariableValue>;
        green1Dark: Variable<import("@tamagui/core").VariableValue>;
        green2Dark: Variable<import("@tamagui/core").VariableValue>;
        green3Dark: Variable<import("@tamagui/core").VariableValue>;
        green4Dark: Variable<import("@tamagui/core").VariableValue>;
        green5Dark: Variable<import("@tamagui/core").VariableValue>;
        green6Dark: Variable<import("@tamagui/core").VariableValue>;
        green7Dark: Variable<import("@tamagui/core").VariableValue>;
        green8Dark: Variable<import("@tamagui/core").VariableValue>;
        green9Dark: Variable<import("@tamagui/core").VariableValue>;
        green10Dark: Variable<import("@tamagui/core").VariableValue>;
        green11Dark: Variable<import("@tamagui/core").VariableValue>;
        green12Dark: Variable<import("@tamagui/core").VariableValue>;
        gray1Dark: Variable<import("@tamagui/core").VariableValue>;
        gray2Dark: Variable<import("@tamagui/core").VariableValue>;
        gray3Dark: Variable<import("@tamagui/core").VariableValue>;
        gray4Dark: Variable<import("@tamagui/core").VariableValue>;
        gray5Dark: Variable<import("@tamagui/core").VariableValue>;
        gray6Dark: Variable<import("@tamagui/core").VariableValue>;
        gray7Dark: Variable<import("@tamagui/core").VariableValue>;
        gray8Dark: Variable<import("@tamagui/core").VariableValue>;
        gray9Dark: Variable<import("@tamagui/core").VariableValue>;
        gray10Dark: Variable<import("@tamagui/core").VariableValue>;
        gray11Dark: Variable<import("@tamagui/core").VariableValue>;
        gray12Dark: Variable<import("@tamagui/core").VariableValue>;
        blue1Dark: Variable<import("@tamagui/core").VariableValue>;
        blue2Dark: Variable<import("@tamagui/core").VariableValue>;
        blue3Dark: Variable<import("@tamagui/core").VariableValue>;
        blue4Dark: Variable<import("@tamagui/core").VariableValue>;
        blue5Dark: Variable<import("@tamagui/core").VariableValue>;
        blue6Dark: Variable<import("@tamagui/core").VariableValue>;
        blue7Dark: Variable<import("@tamagui/core").VariableValue>;
        blue8Dark: Variable<import("@tamagui/core").VariableValue>;
        blue9Dark: Variable<import("@tamagui/core").VariableValue>;
        blue10Dark: Variable<import("@tamagui/core").VariableValue>;
        blue11Dark: Variable<import("@tamagui/core").VariableValue>;
        blue12Dark: Variable<import("@tamagui/core").VariableValue>;
        yellow1Light: Variable<import("@tamagui/core").VariableValue>;
        yellow2Light: Variable<import("@tamagui/core").VariableValue>;
        yellow3Light: Variable<import("@tamagui/core").VariableValue>;
        yellow4Light: Variable<import("@tamagui/core").VariableValue>;
        yellow5Light: Variable<import("@tamagui/core").VariableValue>;
        yellow6Light: Variable<import("@tamagui/core").VariableValue>;
        yellow7Light: Variable<import("@tamagui/core").VariableValue>;
        yellow8Light: Variable<import("@tamagui/core").VariableValue>;
        yellow9Light: Variable<import("@tamagui/core").VariableValue>;
        yellow10Light: Variable<import("@tamagui/core").VariableValue>;
        yellow11Light: Variable<import("@tamagui/core").VariableValue>;
        yellow12Light: Variable<import("@tamagui/core").VariableValue>;
        red1Light: Variable<import("@tamagui/core").VariableValue>;
        red2Light: Variable<import("@tamagui/core").VariableValue>;
        red3Light: Variable<import("@tamagui/core").VariableValue>;
        red4Light: Variable<import("@tamagui/core").VariableValue>;
        red5Light: Variable<import("@tamagui/core").VariableValue>;
        red6Light: Variable<import("@tamagui/core").VariableValue>;
        red7Light: Variable<import("@tamagui/core").VariableValue>;
        red8Light: Variable<import("@tamagui/core").VariableValue>;
        red9Light: Variable<import("@tamagui/core").VariableValue>;
        red10Light: Variable<import("@tamagui/core").VariableValue>;
        red11Light: Variable<import("@tamagui/core").VariableValue>;
        red12Light: Variable<import("@tamagui/core").VariableValue>;
        purple1Light: Variable<import("@tamagui/core").VariableValue>;
        purple2Light: Variable<import("@tamagui/core").VariableValue>;
        purple3Light: Variable<import("@tamagui/core").VariableValue>;
        purple4Light: Variable<import("@tamagui/core").VariableValue>;
        purple5Light: Variable<import("@tamagui/core").VariableValue>;
        purple6Light: Variable<import("@tamagui/core").VariableValue>;
        purple7Light: Variable<import("@tamagui/core").VariableValue>;
        purple8Light: Variable<import("@tamagui/core").VariableValue>;
        purple9Light: Variable<import("@tamagui/core").VariableValue>;
        purple10Light: Variable<import("@tamagui/core").VariableValue>;
        purple11Light: Variable<import("@tamagui/core").VariableValue>;
        purple12Light: Variable<import("@tamagui/core").VariableValue>;
        pink1Light: Variable<import("@tamagui/core").VariableValue>;
        pink2Light: Variable<import("@tamagui/core").VariableValue>;
        pink3Light: Variable<import("@tamagui/core").VariableValue>;
        pink4Light: Variable<import("@tamagui/core").VariableValue>;
        pink5Light: Variable<import("@tamagui/core").VariableValue>;
        pink6Light: Variable<import("@tamagui/core").VariableValue>;
        pink7Light: Variable<import("@tamagui/core").VariableValue>;
        pink8Light: Variable<import("@tamagui/core").VariableValue>;
        pink9Light: Variable<import("@tamagui/core").VariableValue>;
        pink10Light: Variable<import("@tamagui/core").VariableValue>;
        pink11Light: Variable<import("@tamagui/core").VariableValue>;
        pink12Light: Variable<import("@tamagui/core").VariableValue>;
        orange1Light: Variable<import("@tamagui/core").VariableValue>;
        orange2Light: Variable<import("@tamagui/core").VariableValue>;
        orange3Light: Variable<import("@tamagui/core").VariableValue>;
        orange4Light: Variable<import("@tamagui/core").VariableValue>;
        orange5Light: Variable<import("@tamagui/core").VariableValue>;
        orange6Light: Variable<import("@tamagui/core").VariableValue>;
        orange7Light: Variable<import("@tamagui/core").VariableValue>;
        orange8Light: Variable<import("@tamagui/core").VariableValue>;
        orange9Light: Variable<import("@tamagui/core").VariableValue>;
        orange10Light: Variable<import("@tamagui/core").VariableValue>;
        orange11Light: Variable<import("@tamagui/core").VariableValue>;
        orange12Light: Variable<import("@tamagui/core").VariableValue>;
        green1Light: Variable<import("@tamagui/core").VariableValue>;
        green2Light: Variable<import("@tamagui/core").VariableValue>;
        green3Light: Variable<import("@tamagui/core").VariableValue>;
        green4Light: Variable<import("@tamagui/core").VariableValue>;
        green5Light: Variable<import("@tamagui/core").VariableValue>;
        green6Light: Variable<import("@tamagui/core").VariableValue>;
        green7Light: Variable<import("@tamagui/core").VariableValue>;
        green8Light: Variable<import("@tamagui/core").VariableValue>;
        green9Light: Variable<import("@tamagui/core").VariableValue>;
        green10Light: Variable<import("@tamagui/core").VariableValue>;
        green11Light: Variable<import("@tamagui/core").VariableValue>;
        green12Light: Variable<import("@tamagui/core").VariableValue>;
        gray1Light: Variable<import("@tamagui/core").VariableValue>;
        gray2Light: Variable<import("@tamagui/core").VariableValue>;
        gray3Light: Variable<import("@tamagui/core").VariableValue>;
        gray4Light: Variable<import("@tamagui/core").VariableValue>;
        gray5Light: Variable<import("@tamagui/core").VariableValue>;
        gray6Light: Variable<import("@tamagui/core").VariableValue>;
        gray7Light: Variable<import("@tamagui/core").VariableValue>;
        gray8Light: Variable<import("@tamagui/core").VariableValue>;
        gray9Light: Variable<import("@tamagui/core").VariableValue>;
        gray10Light: Variable<import("@tamagui/core").VariableValue>;
        gray11Light: Variable<import("@tamagui/core").VariableValue>;
        gray12Light: Variable<import("@tamagui/core").VariableValue>;
        blue1Light: Variable<import("@tamagui/core").VariableValue>;
        blue2Light: Variable<import("@tamagui/core").VariableValue>;
        blue3Light: Variable<import("@tamagui/core").VariableValue>;
        blue4Light: Variable<import("@tamagui/core").VariableValue>;
        blue5Light: Variable<import("@tamagui/core").VariableValue>;
        blue6Light: Variable<import("@tamagui/core").VariableValue>;
        blue7Light: Variable<import("@tamagui/core").VariableValue>;
        blue8Light: Variable<import("@tamagui/core").VariableValue>;
        blue9Light: Variable<import("@tamagui/core").VariableValue>;
        blue10Light: Variable<import("@tamagui/core").VariableValue>;
        blue11Light: Variable<import("@tamagui/core").VariableValue>;
        blue12Light: Variable<import("@tamagui/core").VariableValue>;
    };
    space: {
        true: Variable<import("@tamagui/core").VariableValue>;
        0: Variable<import("@tamagui/core").VariableValue>;
        1: Variable<import("@tamagui/core").VariableValue>;
        4: Variable<import("@tamagui/core").VariableValue>;
        2: Variable<import("@tamagui/core").VariableValue>;
        16: Variable<import("@tamagui/core").VariableValue>;
        3: Variable<import("@tamagui/core").VariableValue>;
        8: Variable<import("@tamagui/core").VariableValue>;
        20: Variable<import("@tamagui/core").VariableValue>;
        0.25: Variable<import("@tamagui/core").VariableValue>;
        0.5: Variable<import("@tamagui/core").VariableValue>;
        0.75: Variable<import("@tamagui/core").VariableValue>;
        1.5: Variable<import("@tamagui/core").VariableValue>;
        2.5: Variable<import("@tamagui/core").VariableValue>;
        3.5: Variable<import("@tamagui/core").VariableValue>;
        4.5: Variable<import("@tamagui/core").VariableValue>;
        5: Variable<import("@tamagui/core").VariableValue>;
        5.5: Variable<import("@tamagui/core").VariableValue>;
        6: Variable<import("@tamagui/core").VariableValue>;
        6.5: Variable<import("@tamagui/core").VariableValue>;
        7: Variable<import("@tamagui/core").VariableValue>;
        7.6: Variable<import("@tamagui/core").VariableValue>;
        8.5: Variable<import("@tamagui/core").VariableValue>;
        9: Variable<import("@tamagui/core").VariableValue>;
        9.5: Variable<import("@tamagui/core").VariableValue>;
        10: Variable<import("@tamagui/core").VariableValue>;
        11: Variable<import("@tamagui/core").VariableValue>;
        12: Variable<import("@tamagui/core").VariableValue>;
        13: Variable<import("@tamagui/core").VariableValue>;
        14: Variable<import("@tamagui/core").VariableValue>;
        15: Variable<import("@tamagui/core").VariableValue>;
        17: Variable<import("@tamagui/core").VariableValue>;
        18: Variable<import("@tamagui/core").VariableValue>;
        19: Variable<import("@tamagui/core").VariableValue>;
        "-true": Variable<import("@tamagui/core").VariableValue>;
        "-0": Variable<import("@tamagui/core").VariableValue>;
        [-1]: Variable<import("@tamagui/core").VariableValue>;
        [-4]: Variable<import("@tamagui/core").VariableValue>;
        [-2]: Variable<import("@tamagui/core").VariableValue>;
        [-16]: Variable<import("@tamagui/core").VariableValue>;
        [-3]: Variable<import("@tamagui/core").VariableValue>;
        [-8]: Variable<import("@tamagui/core").VariableValue>;
        [-20]: Variable<import("@tamagui/core").VariableValue>;
        [-0.25]: Variable<import("@tamagui/core").VariableValue>;
        [-0.5]: Variable<import("@tamagui/core").VariableValue>;
        [-0.75]: Variable<import("@tamagui/core").VariableValue>;
        [-1.5]: Variable<import("@tamagui/core").VariableValue>;
        [-2.5]: Variable<import("@tamagui/core").VariableValue>;
        [-3.5]: Variable<import("@tamagui/core").VariableValue>;
        [-4.5]: Variable<import("@tamagui/core").VariableValue>;
        [-5]: Variable<import("@tamagui/core").VariableValue>;
        [-5.5]: Variable<import("@tamagui/core").VariableValue>;
        [-6]: Variable<import("@tamagui/core").VariableValue>;
        [-6.5]: Variable<import("@tamagui/core").VariableValue>;
        [-7]: Variable<import("@tamagui/core").VariableValue>;
        [-7.6]: Variable<import("@tamagui/core").VariableValue>;
        [-8.5]: Variable<import("@tamagui/core").VariableValue>;
        [-9]: Variable<import("@tamagui/core").VariableValue>;
        [-9.5]: Variable<import("@tamagui/core").VariableValue>;
        [-10]: Variable<import("@tamagui/core").VariableValue>;
        [-11]: Variable<import("@tamagui/core").VariableValue>;
        [-12]: Variable<import("@tamagui/core").VariableValue>;
        [-13]: Variable<import("@tamagui/core").VariableValue>;
        [-14]: Variable<import("@tamagui/core").VariableValue>;
        [-15]: Variable<import("@tamagui/core").VariableValue>;
        [-17]: Variable<import("@tamagui/core").VariableValue>;
        [-18]: Variable<import("@tamagui/core").VariableValue>;
        [-19]: Variable<import("@tamagui/core").VariableValue>;
    };
    size: {
        0: Variable<import("@tamagui/core").VariableValue>;
        0.25: Variable<import("@tamagui/core").VariableValue>;
        0.5: Variable<import("@tamagui/core").VariableValue>;
        0.75: Variable<import("@tamagui/core").VariableValue>;
        1: Variable<import("@tamagui/core").VariableValue>;
        1.5: Variable<import("@tamagui/core").VariableValue>;
        2: Variable<import("@tamagui/core").VariableValue>;
        2.5: Variable<import("@tamagui/core").VariableValue>;
        3: Variable<import("@tamagui/core").VariableValue>;
        3.5: Variable<import("@tamagui/core").VariableValue>;
        4: Variable<import("@tamagui/core").VariableValue>;
        true: Variable<import("@tamagui/core").VariableValue>;
        4.5: Variable<import("@tamagui/core").VariableValue>;
        5: Variable<import("@tamagui/core").VariableValue>;
        5.5: Variable<import("@tamagui/core").VariableValue>;
        6: Variable<import("@tamagui/core").VariableValue>;
        6.5: Variable<import("@tamagui/core").VariableValue>;
        7: Variable<import("@tamagui/core").VariableValue>;
        7.6: Variable<import("@tamagui/core").VariableValue>;
        8: Variable<import("@tamagui/core").VariableValue>;
        8.5: Variable<import("@tamagui/core").VariableValue>;
        9: Variable<import("@tamagui/core").VariableValue>;
        9.5: Variable<import("@tamagui/core").VariableValue>;
        10: Variable<import("@tamagui/core").VariableValue>;
        11: Variable<import("@tamagui/core").VariableValue>;
        12: Variable<import("@tamagui/core").VariableValue>;
        13: Variable<import("@tamagui/core").VariableValue>;
        14: Variable<import("@tamagui/core").VariableValue>;
        15: Variable<import("@tamagui/core").VariableValue>;
        16: Variable<import("@tamagui/core").VariableValue>;
        17: Variable<import("@tamagui/core").VariableValue>;
        18: Variable<import("@tamagui/core").VariableValue>;
        19: Variable<import("@tamagui/core").VariableValue>;
        20: Variable<import("@tamagui/core").VariableValue>;
    };
    radius: {
        0: Variable<import("@tamagui/core").VariableValue>;
        1: Variable<import("@tamagui/core").VariableValue>;
        2: Variable<import("@tamagui/core").VariableValue>;
        3: Variable<import("@tamagui/core").VariableValue>;
        4: Variable<import("@tamagui/core").VariableValue>;
        5: Variable<import("@tamagui/core").VariableValue>;
        6: Variable<import("@tamagui/core").VariableValue>;
        7: Variable<import("@tamagui/core").VariableValue>;
        8: Variable<import("@tamagui/core").VariableValue>;
        9: Variable<import("@tamagui/core").VariableValue>;
        10: Variable<import("@tamagui/core").VariableValue>;
        11: Variable<import("@tamagui/core").VariableValue>;
        12: Variable<import("@tamagui/core").VariableValue>;
    };
    zIndex: {
        0: Variable<import("@tamagui/core").VariableValue>;
        1: Variable<import("@tamagui/core").VariableValue>;
        2: Variable<import("@tamagui/core").VariableValue>;
        3: Variable<import("@tamagui/core").VariableValue>;
        4: Variable<import("@tamagui/core").VariableValue>;
        5: Variable<import("@tamagui/core").VariableValue>;
    };
};
export {};
//# sourceMappingURL=tokens.d.ts.map