//! The Rust parser against the grammar's own answers.
//!
//! `tests/vectors.json` is generated by `@tamagui/style-grammar`'s
//! `scripts/generateRustGrammar.ts`: it runs that package's `parseValue` and its
//! modifier registry over a fixed config and writes down what they said. Nothing
//! here decides what a value means; it only checks that this crate says the same
//! thing.
//!
//! That is the whole point of the file. The two implementations had already
//! drifted (camelCase `focusVisible`, no `active` alias, no group or container
//! modifiers, `[` and `{` treated as nesting, a payload cut at every space) and
//! every one of those was invisible because nothing compared them. Reading
//! two parsers side by side does not catch a fork; running both over the same
//! inputs does.
//!
//! To regenerate: `bun scripts/generateRustGrammar.ts` in
//! `code/core/style-grammar`.

use serde_json::Value as Json;
use tamagui_grammar::modifier::{
    canonical_modifier, parse_container_modifier, parse_group_modifier, ModifierLookup,
    ModifierRegistry,
};
use tamagui_grammar::value::{parse_with, ParseErrorCode};

const VECTORS: &str = include_str!("vectors.json");

fn strings(json: &Json, key: &str) -> Vec<String> {
    json[key]
        .as_array()
        .unwrap_or_else(|| panic!("vectors are missing config.{key}"))
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect()
}

struct Fixture {
    registry: ModifierRegistry,
    vectors: Json,
}

fn fixture() -> Fixture {
    let vectors: Json = serde_json::from_str(VECTORS).expect("vectors.json is not valid JSON");
    let config = &vectors["config"];
    let media = strings(config, "mediaNames");
    let themes = strings(config, "themeNames");
    let sizes = strings(config, "containerSizeNames");
    let registry = ModifierRegistry::build(
        &media.iter().map(String::as_str).collect::<Vec<_>>(),
        &themes.iter().map(String::as_str).collect::<Vec<_>>(),
        &sizes.iter().map(String::as_str).collect::<Vec<_>>(),
    );
    Fixture { registry, vectors }
}

#[test]
fn the_modifier_registry_agrees_with_the_grammar() {
    let Fixture { registry, vectors } = fixture();
    let cases = vectors["modifiers"].as_array().expect("modifier vectors");
    assert!(cases.len() > 40, "expected a real vector set, got {}", cases.len());

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let expected_kind = case["kind"].as_str();
        let actual_kind = registry.kind(name).map(|k| k.as_str());
        assert_eq!(actual_kind, expected_kind, "kind of {name:?}");

        assert_eq!(
            canonical_modifier(name),
            case["canonical"].as_str().unwrap(),
            "canonical spelling of {name:?}"
        );

        match (parse_group_modifier(name), case["group"].as_object()) {
            (None, None) => {}
            (Some(group), Some(expected)) => {
                assert_eq!(group.state, expected["state"].as_str().unwrap(), "group state of {name:?}");
                assert_eq!(
                    group.group.as_deref(),
                    expected["group"].as_str(),
                    "group name of {name:?}"
                );
            }
            (actual, expected) => panic!("group modifier of {name:?}: {actual:?} vs {expected:?}"),
        }

        match (parse_container_modifier(name), case["container"].as_object()) {
            (None, None) => {}
            (Some(container), Some(expected)) => {
                assert_eq!(
                    container.size,
                    expected["size"].as_str().unwrap(),
                    "container size of {name:?}"
                );
                assert_eq!(
                    container.container.as_deref(),
                    expected["container"].as_str(),
                    "container name of {name:?}"
                );
            }
            (actual, expected) => {
                panic!("container modifier of {name:?}: {actual:?} vs {expected:?}")
            }
        }
    }
}

fn code_name(code: ParseErrorCode) -> &'static str {
    code.as_str()
}

#[test]
fn the_parser_splits_every_vector_the_way_the_grammar_does() {
    let Fixture { registry, vectors } = fixture();
    let cases = vectors["parse"].as_array().expect("parse vectors");
    assert!(cases.len() > 400, "expected a real vector set, got {}", cases.len());

    let mut with_clauses = 0;
    let mut refused = 0;

    for case in cases {
        let source = case["source"].as_str().unwrap();
        let parsed = parse_with(source, &registry);
        let label = format!("{source:?}");

        let expected_errors: Vec<(String, usize)> = case["errors"]
            .as_array()
            .map(|errors| {
                errors
                    .iter()
                    .map(|e| {
                        (
                            e["code"].as_str().unwrap().to_string(),
                            e["index"].as_u64().unwrap() as usize,
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();
        let actual_errors: Vec<(String, usize)> = parsed
            .errors
            .iter()
            .map(|e| (code_name(e.code).to_string(), e.index))
            .collect();
        assert_eq!(actual_errors, expected_errors, "errors for {label}");

        assert_eq!(
            parsed.is_ok(),
            case["ok"].as_bool().unwrap(),
            "ok for {label}"
        );
        if !parsed.is_ok() {
            refused += 1;
            // a refused value has no meaning to compare; the grammar reports
            // no base and no clauses for one either
            continue;
        }

        assert_eq!(
            parsed.base.map(|b| b.of(source)),
            case["base"].as_str(),
            "base for {label}"
        );

        let expected_clauses = case["clauses"].as_array().expect("clauses");
        assert_eq!(
            parsed.clauses.len(),
            expected_clauses.len(),
            "clause count for {label}"
        );
        for (index, clause) in parsed.clauses.iter().enumerate() {
            let expected = &expected_clauses[index];
            let modifiers: Vec<&str> =
                clause.modifiers.iter().map(|m| m.span.of(source)).collect();
            let expected_modifiers: Vec<&str> = expected["modifiers"]
                .as_array()
                .unwrap()
                .iter()
                .map(|m| m.as_str().unwrap())
                .collect();
            assert_eq!(modifiers, expected_modifiers, "clause {index} modifiers for {label}");
            assert_eq!(
                clause.payload.of(source),
                expected["payload"].as_str().unwrap(),
                "clause {index} payload for {label}"
            );
        }
        if !parsed.clauses.is_empty() {
            with_clauses += 1;
        }
    }

    // a vector set that never exercised a clause, or never a refusal, would
    // pass this file while proving nothing
    assert!(with_clauses > 100, "only {with_clauses} vectors carried a clause");
    assert!(refused > 100, "only {refused} vectors were refused");
}
