import type React from 'react'
import { useThemeName } from '@tamagui/core'
import { Text, type TextProps, type TextStyle } from 'react-native'

export interface TamaguiTextProps extends TextProps {
  /**
   * Pre-computed styles for each theme, keyed by theme name.
   * Generated by the compiler at build time.
   */
  __styles?: Record<string, TextStyle>
}

/**
 * Optimized Text component that uses pre-computed theme styles.
 * The compiler generates __styles with resolved values for each theme,
 * eliminating runtime style computation.
 */
export function _TamaguiText({
  __styles,
  style,
  ...props
}: TamaguiTextProps): React.ReactElement {
  const themeName = useThemeName()
  const themedStyle = __styles?.[themeName]

  return <Text {...props} style={themedStyle ? [themedStyle, style] : style} />
}
