import type React from 'react'
import { useThemeName } from '@tamagui/core'
import { View, type ViewProps, type ViewStyle } from 'react-native'

export interface TamaguiViewProps extends ViewProps {
  /**
   * Pre-computed styles for each theme, keyed by theme name.
   * Generated by the compiler at build time.
   */
  __styles?: Record<string, ViewStyle>
}

/**
 * Optimized View component that uses pre-computed theme styles.
 * The compiler generates __styles with resolved values for each theme,
 * eliminating runtime style computation.
 */
export function _TamaguiView({
  __styles,
  style,
  ...props
}: TamaguiViewProps): React.ReactElement {
  const themeName = useThemeName()
  const themedStyle = __styles?.[themeName]

  return <View {...props} style={themedStyle ? [themedStyle, style] : style} />
}
