name: Reproducible Bug Report
description: Get much faster response time by **forking this repo, reproducing the bug, and then submitting it was a PR with the title "[Issue] ..."**
labels: [Bug]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: Describe what's happening in 1-2 sentences.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Tamagui Version
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    render: markdown
    description: |
      - If this is a bug with Tamagui, fork [this CodeSandbox](https://codesandbox.io/p/sandbox/github/tamagui/tamagui/starters/expo-next-solito) to reproduce the issue.
      - If this is a bug with the Starter, fork [this CodeSandbox](https://codesandbox.io/p/sandbox/github/tamagui/tamagui/apps/starter) to reproduce the issue.
      - For native-only bugs, please fork this repo and use `apps/kitchen-sink` to reproduce the bug. Once reproduced, submit a PR with the title `[Issue] ...`
  validations:
    required: true
