name: Reproducible Bug Report
description: Issues **will be closed without review** if reproduction steps are omitted. More context is helpful before submitting search github, discord, the docs and google.
labels: [Bug]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what's happening in 1-2 sentences.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tamagui Version
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Platform (Web, iOS, Android)
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      render: markdown
      description: |
        - If you don't include reproduction, we will close the issue.
        - The easiest way to reproduce is using the starter free repo: https://github.com/tamagui/starter-free
        - Clone that repo and push your reproduction as a new commit.
        - For simpler bugs you can fork [this CodeSandbox](https://codesandbox.io/p/sandbox/github/tamagui/starter-free) to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Info
      render: markdown
      description: |
        - Output of `npx envinfo --system --npmPackages --binaries --browsers`
