// extracts the 12-step color scales from the frozen v5 base themes into
// src/v5-color-scales.generated.ts, the pack createV6Config `scales` consumes.
// run: bun scripts/generate-v5-color-scales.ts [--check]
import { writeFileSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { themes } from '../src/generated-v5'

const SCALE_NAMES = [
  'black',
  'white',
  'gray',
  'blue',
  'red',
  'yellow',
  'green',
  'orange',
  'pink',
  'purple',
  'teal',
  'neutral',
] as const

const steps = Array.from({ length: 12 }, (_, index) => index + 1)

const scaleFor = (theme: Record<string, string>, name: string) =>
  steps.map((step) => {
    const value = theme[`${name}${step}`]
    if (!value) {
      throw new Error(`v5 theme is missing ${name}${step}`)
    }
    return value
  })

const scales = Object.fromEntries(
  SCALE_NAMES.map((name) => [
    name,
    {
      light: scaleFor(themes.light as any, name),
      dark: scaleFor(themes.dark as any, name),
    },
  ])
)

const file = `// generated by scripts/generate-v5-color-scales.ts — do not edit.
// the 12-step color scales from the frozen v5 base themes, for
// createV6Config's \`scales\` option.

export const v5ColorScales = ${JSON.stringify(scales, null, 2)} as const
`

const target = join(
  dirname(fileURLToPath(import.meta.url)),
  '../src/v5-color-scales.generated.ts'
)

if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== file) {
    console.error('v5-color-scales.generated.ts is stale, re-run the generator')
    process.exit(1)
  }
} else {
  writeFileSync(target, file)
  console.info(`wrote ${target}`)
}
