/// <reference types="react" />
export declare const elevate: {
    true: (_: boolean, extras: any) => {
        [x: `$${string}`]: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>> & import("@tamagui/web").PseudoProps<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>>) | import("@tamagui/web").Variable<any> | undefined;
        [x: `$${number}`]: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>> & import("@tamagui/web").PseudoProps<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>>) | import("@tamagui/web").Variable<any> | undefined;
        hitSlop?: import("@tamagui/web").VariableVal | import("react-native").Insets | (import("react-native").Insets & number) | import("@tamagui/web").Variable<any> | undefined;
        id?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        pointerEvents?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        removeClippedSubviews?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        testID?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        nativeID?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        collapsable?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        needsOffscreenAlphaCompositing?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        renderToHardwareTextureAndroid?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        focusable?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        shouldRasterizeIOS?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        isTVSelectable?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        hasTVPreferredFocus?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tvParallaxProperties?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react-native").TVParallaxProperties | undefined;
        tvParallaxShiftDistanceX?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tvParallaxShiftDistanceY?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tvParallaxTiltAngle?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tvParallaxMagnification?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        onTouchStart?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | undefined;
        onTouchMove?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | undefined;
        onTouchEnd?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | undefined;
        onTouchCancel?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | undefined;
        onTouchEndCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | undefined;
        onPointerEnter?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerEnterCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerLeave?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerLeaveCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerMove?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerMoveCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerCancel?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerCancelCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerDown?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerDownCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerUp?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        onPointerUpCapture?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").PointerEvent) => void) | undefined;
        accessible?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityActions?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | readonly Readonly<{
            name: string;
            label?: string | undefined;
        }>[] | undefined;
        accessibilityLabel?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-label'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityRole?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        accessibilityState?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react-native").AccessibilityState | undefined;
        'aria-busy'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-checked'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-disabled'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-expanded'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-selected'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-labelledby'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityHint?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityValue?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react-native").AccessibilityValue | undefined;
        'aria-valuemax'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-valuemin'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-valuenow'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-valuetext'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        onAccessibilityAction?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").AccessibilityActionEvent) => void) | undefined;
        importantForAccessibility?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-hidden'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-live'?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        'aria-modal'?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        role?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityLiveRegion?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityLabelledBy?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | string[] | undefined;
        accessibilityElementsHidden?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityViewIsModal?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        onAccessibilityEscape?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | (() => void) | undefined;
        onAccessibilityTap?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | (() => void) | undefined;
        onMagicTap?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | (() => void) | undefined;
        accessibilityIgnoresInvertColors?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        accessibilityLanguage?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        target?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        asChild?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        dangerouslySetInnerHTML?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | {
            __html: string;
        } | undefined;
        children?: any;
        debug?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        disabled?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        className?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        themeShallow?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tag?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        theme?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | null | undefined;
        componentName?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        tabIndex?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        forceStyle?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        onPress?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | null | undefined;
        onLongPress?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | null | undefined;
        onPressIn?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | null | undefined;
        onPressOut?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react-native").GestureResponderEvent) => void) | null | undefined;
        onHoverIn?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onHoverOut?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onMouseEnter?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onMouseLeave?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onMouseDown?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onMouseUp?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("react").MouseEventHandler<HTMLDivElement> | undefined;
        onFocus?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react").FocusEvent<HTMLDivElement, Element>) => void) | undefined;
        onScroll?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | ((event: import("react").UIEvent<HTMLDivElement, UIEvent>) => void) | undefined;
        style?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("@tamagui/web").StyleProp<import("react-native").ViewStyle | import("react").CSSProperties | (import("react").CSSProperties & import("react-native").ViewStyle)>;
        backgroundColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderBlockColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderBlockEndColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderBlockStartColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderBottomColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderBottomEndRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderBottomLeftRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderBottomRightRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderBottomStartRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderCurve?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        borderEndColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderEndEndRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderEndStartRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderLeftColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderRightColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderStartColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderStartEndRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderStartStartRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderStyle?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        borderTopColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        borderTopEndRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderTopLeftRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderTopRightRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderTopStartRadius?: import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        opacity?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | undefined;
        alignContent?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        alignItems?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        alignSelf?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        aspectRatio?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        borderBottomWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderEndWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderLeftWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderRightWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderStartWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderTopWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        borderWidth?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        bottom?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        end?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | null | undefined;
        flex?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        flexBasis?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | null | undefined;
        flexDirection?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        flexGrow?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        flexShrink?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        flexWrap?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        height?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        justifyContent?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        left?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        margin?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginBottom?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginEnd?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginHorizontal?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginLeft?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginRight?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginStart?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginTop?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        marginVertical?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        maxHeight?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        maxWidth?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        minHeight?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        minWidth?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        overflow?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        padding?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingBottom?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingEnd?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingHorizontal?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingLeft?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingRight?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingStart?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingTop?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        paddingVertical?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        position?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        right?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        start?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | null | undefined;
        top?: boolean | import("@tamagui/web").VariableVal | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        width?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | null | undefined;
        zIndex?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        direction?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        shadowColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react-native").OpaqueColorValue | undefined;
        shadowOffset?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | {
            width: import("@tamagui/web").SpaceTokens;
            height: import("@tamagui/web").SpaceTokens;
        } | Readonly<{
            width: number;
            height: number;
        }> | undefined;
        shadowOpacity?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | undefined;
        shadowRadius?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        transform?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | (import("react-native").PerpectiveTransform | import("react-native").RotateTransform | import("react-native").RotateXTransform | import("react-native").RotateYTransform | import("react-native").RotateZTransform | import("react-native").ScaleTransform | import("react-native").ScaleXTransform | import("react-native").ScaleYTransform | import("react-native").TranslateXTransform | import("react-native").TranslateYTransform | import("react-native").SkewXTransform | import("react-native").SkewYTransform | import("react-native").MatrixTransform)[] | undefined;
        transformMatrix?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | number[] | undefined;
        rotation?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | undefined;
        scaleX?: string | number | boolean | import("@tamagui/web").Variable<any> | (import("react-native").Animated.AnimatedNode & number) | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        scaleY?: string | number | boolean | import("@tamagui/web").Variable<any> | (import("react-native").Animated.AnimatedNode & number) | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        translateX?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | undefined;
        translateY?: string | number | import("@tamagui/web").Variable<any> | import("react-native").Animated.AnimatedNode | import("@tamagui/web").Variable<any> | undefined;
        x?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        y?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        perspective?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        scale?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        skewX?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        skewY?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        matrix?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | number[] | undefined;
        rotate?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        rotateY?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        rotateX?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        rotateZ?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        columnGap?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        contain?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | (string & {}) | undefined;
        cursor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | (string & {}) | undefined;
        display?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | undefined;
        gap?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        outlineColor?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | (string & {}) | undefined;
        outlineOffset?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        outlineStyle?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | (string & {}) | undefined;
        outlineWidth?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        rowGap?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        space?: boolean | import("@tamagui/web").VariableVal | import("@tamagui/web").UnionableNumber | import("@tamagui/web").UnionableString | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        spaceDirection?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        separator?: string | number | boolean | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>> | import("react").ReactFragment | import("react").ReactPortal | null | undefined;
        animation?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | {
            [key: string]: string | number | {
                [key: string]: any;
                type: string | number;
            };
        } | [string | number, {
            [key: string]: string | number | {
                [key: string]: any;
                type?: string | number | undefined;
            };
        }] | null | undefined;
        animateOnly?: import("@tamagui/web").VariableVal | import("@tamagui/web").Variable<any> | string[] | undefined;
        userSelect?: string | number | import("@tamagui/web").Variable<any> | import("@tamagui/web").Variable<any> | undefined;
        hoverStyle?: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>) | import("@tamagui/web").Variable<any> | null | undefined;
        pressStyle?: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>) | import("@tamagui/web").Variable<any> | null | undefined;
        focusStyle?: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>) | import("@tamagui/web").Variable<any> | null | undefined;
        exitStyle?: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>) | import("@tamagui/web").Variable<any> | null | undefined;
        enterStyle?: import("@tamagui/web").VariableVal | (import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase> & import("@tamagui/web").WithShorthands<import("@tamagui/web").WithThemeValues<import("@tamagui/web").StackStylePropsBase>>) | import("@tamagui/web").Variable<any> | null | undefined;
    } | null | undefined;
};
export declare const bordered: (val: boolean | number, { props }: {
    props: any;
}) => any;
export declare const padded: {
    true: (_: any, extras: any) => {
        padding: any;
    };
};
export declare const radiused: {
    true: (_: any, extras: any) => {
        borderRadius: any;
    };
};
export declare const circular: {
    true: (_: any, { props, tokens }: {
        props: any;
        tokens: any;
    }) => {
        width: any;
        height: any;
        maxWidth: any;
        maxHeight: any;
        minWidth: any;
        minHeight: any;
        borderRadius: number;
        padding: number;
    };
};
export declare const hoverTheme: {
    true: {
        hoverStyle: {
            backgroundColor: string;
            borderColor: string;
        };
    };
    false: {};
};
export declare const pressTheme: {
    true: {
        cursor: string;
        pressStyle: {
            backgroundColor: string;
            borderColor: string;
        };
    };
    false: {};
};
export declare const focusTheme: {
    true: {
        focusStyle: {
            backgroundColor: string;
            borderColor: string;
        };
    };
    false: {};
};
//# sourceMappingURL=variants.d.ts.map