import { BuildThemeSuiteProps } from './types';
export declare function buildThemeSuite({ baseTheme, subThemes }: BuildThemeSuiteProps): {
    built: {
        [x: `light_${string}`]: {
            [x: string]: string;
        };
        [x: `dark_${string}`]: {
            [x: string]: string;
        };
        [x: `light_${string}_alt1`]: unknown;
        [x: `light_${string}_alt2`]: unknown;
        [x: `dark_${string}_alt1`]: unknown;
        [x: `dark_${string}_alt2`]: unknown;
        [x: `light_${string}_${string}`]: unknown;
        [x: `dark_${string}_${string}`]: unknown;
        [x: `light_${string}_alt1_${string}`]: unknown;
        [x: `light_${string}_alt2_${string}`]: unknown;
        [x: `dark_${string}_alt1_${string}`]: unknown;
        [x: `dark_${string}_alt2_${string}`]: unknown;
        [x: `light_${string}_Card`]: unknown;
        [x: `light_${string}_Button`]: unknown;
        [x: `light_${string}_Checkbox`]: unknown;
        [x: `light_${string}_Switch`]: unknown;
        [x: `light_${string}_SwitchThumb`]: unknown;
        [x: `light_${string}_TooltipContent`]: unknown;
        [x: `light_${string}_DrawerFrame`]: unknown;
        [x: `light_${string}_Progress`]: unknown;
        [x: `light_${string}_RadioGroupItem`]: unknown;
        [x: `light_${string}_TooltipArrow`]: unknown;
        [x: `light_${string}_SliderTrackActive`]: unknown;
        [x: `light_${string}_SliderTrack`]: unknown;
        [x: `light_${string}_SliderThumb`]: unknown;
        [x: `light_${string}_Tooltip`]: unknown;
        [x: `light_${string}_ProgressIndicator`]: unknown;
        [x: `light_${string}_SheetOverlay`]: unknown;
        [x: `light_${string}_DialogOverlay`]: unknown;
        [x: `light_${string}_ModalOverlay`]: unknown;
        [x: `light_${string}_Input`]: unknown;
        [x: `light_${string}_TextArea`]: unknown;
        [x: `dark_${string}_Card`]: unknown;
        [x: `dark_${string}_Button`]: unknown;
        [x: `dark_${string}_Checkbox`]: unknown;
        [x: `dark_${string}_Switch`]: unknown;
        [x: `dark_${string}_SwitchThumb`]: unknown;
        [x: `dark_${string}_TooltipContent`]: unknown;
        [x: `dark_${string}_DrawerFrame`]: unknown;
        [x: `dark_${string}_Progress`]: unknown;
        [x: `dark_${string}_RadioGroupItem`]: unknown;
        [x: `dark_${string}_TooltipArrow`]: unknown;
        [x: `dark_${string}_SliderTrackActive`]: unknown;
        [x: `dark_${string}_SliderTrack`]: unknown;
        [x: `dark_${string}_SliderThumb`]: unknown;
        [x: `dark_${string}_Tooltip`]: unknown;
        [x: `dark_${string}_ProgressIndicator`]: unknown;
        [x: `dark_${string}_SheetOverlay`]: unknown;
        [x: `dark_${string}_DialogOverlay`]: unknown;
        [x: `dark_${string}_ModalOverlay`]: unknown;
        [x: `dark_${string}_Input`]: unknown;
        [x: `dark_${string}_TextArea`]: unknown;
        [x: `light_${string}_alt1_Card`]: unknown;
        [x: `light_${string}_alt1_Button`]: unknown;
        [x: `light_${string}_alt1_Checkbox`]: unknown;
        [x: `light_${string}_alt1_Switch`]: unknown;
        [x: `light_${string}_alt1_SwitchThumb`]: unknown;
        [x: `light_${string}_alt1_TooltipContent`]: unknown;
        [x: `light_${string}_alt1_DrawerFrame`]: unknown;
        [x: `light_${string}_alt1_Progress`]: unknown;
        [x: `light_${string}_alt1_RadioGroupItem`]: unknown;
        [x: `light_${string}_alt1_TooltipArrow`]: unknown;
        [x: `light_${string}_alt1_SliderTrackActive`]: unknown;
        [x: `light_${string}_alt1_SliderTrack`]: unknown;
        [x: `light_${string}_alt1_SliderThumb`]: unknown;
        [x: `light_${string}_alt1_Tooltip`]: unknown;
        [x: `light_${string}_alt1_ProgressIndicator`]: unknown;
        [x: `light_${string}_alt1_SheetOverlay`]: unknown;
        [x: `light_${string}_alt1_DialogOverlay`]: unknown;
        [x: `light_${string}_alt1_ModalOverlay`]: unknown;
        [x: `light_${string}_alt1_Input`]: unknown;
        [x: `light_${string}_alt1_TextArea`]: unknown;
        [x: `light_${string}_alt2_Card`]: unknown;
        [x: `light_${string}_alt2_Button`]: unknown;
        [x: `light_${string}_alt2_Checkbox`]: unknown;
        [x: `light_${string}_alt2_Switch`]: unknown;
        [x: `light_${string}_alt2_SwitchThumb`]: unknown;
        [x: `light_${string}_alt2_TooltipContent`]: unknown;
        [x: `light_${string}_alt2_DrawerFrame`]: unknown;
        [x: `light_${string}_alt2_Progress`]: unknown;
        [x: `light_${string}_alt2_RadioGroupItem`]: unknown;
        [x: `light_${string}_alt2_TooltipArrow`]: unknown;
        [x: `light_${string}_alt2_SliderTrackActive`]: unknown;
        [x: `light_${string}_alt2_SliderTrack`]: unknown;
        [x: `light_${string}_alt2_SliderThumb`]: unknown;
        [x: `light_${string}_alt2_Tooltip`]: unknown;
        [x: `light_${string}_alt2_ProgressIndicator`]: any;
        [x: `light_${string}_alt2_SheetOverlay`]: any;
        [x: `light_${string}_alt2_DialogOverlay`]: any;
        [x: `light_${string}_alt2_ModalOverlay`]: any;
        [x: `light_${string}_alt2_Input`]: any;
        [x: `light_${string}_alt2_TextArea`]: any;
        [x: `dark_${string}_alt1_Card`]: any;
        [x: `dark_${string}_alt1_Button`]: any;
        [x: `dark_${string}_alt1_Checkbox`]: any;
        [x: `dark_${string}_alt1_Switch`]: any;
        [x: `dark_${string}_alt1_SwitchThumb`]: any;
        [x: `dark_${string}_alt1_TooltipContent`]: any;
        [x: `dark_${string}_alt1_DrawerFrame`]: any;
        [x: `dark_${string}_alt1_Progress`]: any;
        [x: `dark_${string}_alt1_RadioGroupItem`]: any;
        [x: `dark_${string}_alt1_TooltipArrow`]: any;
        [x: `dark_${string}_alt1_SliderTrackActive`]: any;
        [x: `dark_${string}_alt1_SliderTrack`]: any;
        [x: `dark_${string}_alt1_SliderThumb`]: any;
        [x: `dark_${string}_alt1_Tooltip`]: any;
        [x: `dark_${string}_alt1_ProgressIndicator`]: any;
        [x: `dark_${string}_alt1_SheetOverlay`]: any;
        [x: `dark_${string}_alt1_DialogOverlay`]: any;
        [x: `dark_${string}_alt1_ModalOverlay`]: any;
        [x: `dark_${string}_alt1_Input`]: any;
        [x: `dark_${string}_alt1_TextArea`]: any;
        [x: `dark_${string}_alt2_Card`]: any;
        [x: `dark_${string}_alt2_Button`]: any;
        [x: `dark_${string}_alt2_Checkbox`]: any;
        [x: `dark_${string}_alt2_Switch`]: any;
        [x: `dark_${string}_alt2_SwitchThumb`]: any;
        [x: `dark_${string}_alt2_TooltipContent`]: any;
        [x: `dark_${string}_alt2_DrawerFrame`]: any;
        [x: `dark_${string}_alt2_Progress`]: any;
        [x: `dark_${string}_alt2_RadioGroupItem`]: any;
        [x: `dark_${string}_alt2_TooltipArrow`]: any;
        [x: `dark_${string}_alt2_SliderTrackActive`]: any;
        [x: `dark_${string}_alt2_SliderTrack`]: any;
        [x: `dark_${string}_alt2_SliderThumb`]: any;
        [x: `dark_${string}_alt2_Tooltip`]: any;
        [x: `dark_${string}_alt2_ProgressIndicator`]: any;
        [x: `dark_${string}_alt2_SheetOverlay`]: any;
        [x: `dark_${string}_alt2_DialogOverlay`]: any;
        [x: `dark_${string}_alt2_ModalOverlay`]: any;
        [x: `dark_${string}_alt2_Input`]: any;
        [x: `dark_${string}_alt2_TextArea`]: any;
        [x: `light_${string}_${string}_Card`]: any;
        [x: `light_${string}_${string}_Button`]: any;
        [x: `light_${string}_${string}_Checkbox`]: any;
        [x: `light_${string}_${string}_Switch`]: any;
        [x: `light_${string}_${string}_SwitchThumb`]: any;
        [x: `light_${string}_${string}_TooltipContent`]: any;
        [x: `light_${string}_${string}_DrawerFrame`]: any;
        [x: `light_${string}_${string}_Progress`]: any;
        [x: `light_${string}_${string}_RadioGroupItem`]: any;
        [x: `light_${string}_${string}_TooltipArrow`]: any;
        [x: `light_${string}_${string}_SliderTrackActive`]: any;
        [x: `light_${string}_${string}_SliderTrack`]: any;
        [x: `light_${string}_${string}_SliderThumb`]: any;
        [x: `light_${string}_${string}_Tooltip`]: any;
        [x: `light_${string}_${string}_ProgressIndicator`]: any;
        [x: `light_${string}_${string}_SheetOverlay`]: any;
        [x: `light_${string}_${string}_DialogOverlay`]: any;
        [x: `light_${string}_${string}_ModalOverlay`]: any;
        [x: `light_${string}_${string}_Input`]: any;
        [x: `light_${string}_${string}_TextArea`]: any;
        [x: `dark_${string}_${string}_Card`]: any;
        [x: `dark_${string}_${string}_Button`]: any;
        [x: `dark_${string}_${string}_Checkbox`]: any;
        [x: `dark_${string}_${string}_Switch`]: any;
        [x: `dark_${string}_${string}_SwitchThumb`]: any;
        [x: `dark_${string}_${string}_TooltipContent`]: any;
        [x: `dark_${string}_${string}_DrawerFrame`]: any;
        [x: `dark_${string}_${string}_Progress`]: any;
        [x: `dark_${string}_${string}_RadioGroupItem`]: any;
        [x: `dark_${string}_${string}_TooltipArrow`]: any;
        [x: `dark_${string}_${string}_SliderTrackActive`]: any;
        [x: `dark_${string}_${string}_SliderTrack`]: any;
        [x: `dark_${string}_${string}_SliderThumb`]: any;
        [x: `dark_${string}_${string}_Tooltip`]: any;
        [x: `dark_${string}_${string}_ProgressIndicator`]: any;
        [x: `dark_${string}_${string}_SheetOverlay`]: any;
        [x: `dark_${string}_${string}_DialogOverlay`]: any;
        [x: `dark_${string}_${string}_ModalOverlay`]: any;
        [x: `dark_${string}_${string}_Input`]: any;
        [x: `dark_${string}_${string}_TextArea`]: any;
        [x: `light_${string}_alt1_${string}_Card`]: any;
        [x: `light_${string}_alt1_${string}_Button`]: any;
        [x: `light_${string}_alt1_${string}_Checkbox`]: any;
        [x: `light_${string}_alt1_${string}_Switch`]: any;
        [x: `light_${string}_alt1_${string}_SwitchThumb`]: any;
        [x: `light_${string}_alt1_${string}_TooltipContent`]: any;
        [x: `light_${string}_alt1_${string}_DrawerFrame`]: any;
        [x: `light_${string}_alt1_${string}_Progress`]: any;
        [x: `light_${string}_alt1_${string}_RadioGroupItem`]: any;
        [x: `light_${string}_alt1_${string}_TooltipArrow`]: any;
        [x: `light_${string}_alt1_${string}_SliderTrackActive`]: any;
        [x: `light_${string}_alt1_${string}_SliderTrack`]: any;
        [x: `light_${string}_alt1_${string}_SliderThumb`]: any;
        [x: `light_${string}_alt1_${string}_Tooltip`]: any;
        [x: `light_${string}_alt1_${string}_ProgressIndicator`]: any;
        [x: `light_${string}_alt1_${string}_SheetOverlay`]: any;
        [x: `light_${string}_alt1_${string}_DialogOverlay`]: any;
        [x: `light_${string}_alt1_${string}_ModalOverlay`]: any;
        [x: `light_${string}_alt1_${string}_Input`]: any;
        [x: `light_${string}_alt1_${string}_TextArea`]: any;
        [x: `light_${string}_alt2_${string}_Card`]: any;
        [x: `light_${string}_alt2_${string}_Button`]: any;
        [x: `light_${string}_alt2_${string}_Checkbox`]: any;
        [x: `light_${string}_alt2_${string}_Switch`]: any;
        [x: `light_${string}_alt2_${string}_SwitchThumb`]: any;
        [x: `light_${string}_alt2_${string}_TooltipContent`]: any;
        [x: `light_${string}_alt2_${string}_DrawerFrame`]: any;
        [x: `light_${string}_alt2_${string}_Progress`]: any;
        [x: `light_${string}_alt2_${string}_RadioGroupItem`]: any;
        [x: `light_${string}_alt2_${string}_TooltipArrow`]: any;
        [x: `light_${string}_alt2_${string}_SliderTrackActive`]: any;
        [x: `light_${string}_alt2_${string}_SliderTrack`]: any;
        [x: `light_${string}_alt2_${string}_SliderThumb`]: any;
        [x: `light_${string}_alt2_${string}_Tooltip`]: any;
        [x: `light_${string}_alt2_${string}_ProgressIndicator`]: any;
        [x: `light_${string}_alt2_${string}_SheetOverlay`]: any;
        [x: `light_${string}_alt2_${string}_DialogOverlay`]: any;
        [x: `light_${string}_alt2_${string}_ModalOverlay`]: any;
        [x: `light_${string}_alt2_${string}_Input`]: any;
        [x: `light_${string}_alt2_${string}_TextArea`]: any;
        [x: `dark_${string}_alt1_${string}_Card`]: any;
        [x: `dark_${string}_alt1_${string}_Button`]: any;
        [x: `dark_${string}_alt1_${string}_Checkbox`]: any;
        [x: `dark_${string}_alt1_${string}_Switch`]: any;
        [x: `dark_${string}_alt1_${string}_SwitchThumb`]: any;
        [x: `dark_${string}_alt1_${string}_TooltipContent`]: any;
        [x: `dark_${string}_alt1_${string}_DrawerFrame`]: any;
        [x: `dark_${string}_alt1_${string}_Progress`]: any;
        [x: `dark_${string}_alt1_${string}_RadioGroupItem`]: any;
        [x: `dark_${string}_alt1_${string}_TooltipArrow`]: any;
        [x: `dark_${string}_alt1_${string}_SliderTrackActive`]: any;
        [x: `dark_${string}_alt1_${string}_SliderTrack`]: any;
        [x: `dark_${string}_alt1_${string}_SliderThumb`]: any;
        [x: `dark_${string}_alt1_${string}_Tooltip`]: any;
        [x: `dark_${string}_alt1_${string}_ProgressIndicator`]: any;
        [x: `dark_${string}_alt1_${string}_SheetOverlay`]: any;
        [x: `dark_${string}_alt1_${string}_DialogOverlay`]: any;
        [x: `dark_${string}_alt1_${string}_ModalOverlay`]: any;
        [x: `dark_${string}_alt1_${string}_Input`]: any;
        [x: `dark_${string}_alt1_${string}_TextArea`]: any;
        [x: `dark_${string}_alt2_${string}_Card`]: any;
        [x: `dark_${string}_alt2_${string}_Button`]: any;
        [x: `dark_${string}_alt2_${string}_Checkbox`]: any;
        [x: `dark_${string}_alt2_${string}_Switch`]: any;
        [x: `dark_${string}_alt2_${string}_SwitchThumb`]: any;
        [x: `dark_${string}_alt2_${string}_TooltipContent`]: any;
        [x: `dark_${string}_alt2_${string}_DrawerFrame`]: any;
        [x: `dark_${string}_alt2_${string}_Progress`]: any;
        [x: `dark_${string}_alt2_${string}_RadioGroupItem`]: any;
        [x: `dark_${string}_alt2_${string}_TooltipArrow`]: any;
        [x: `dark_${string}_alt2_${string}_SliderTrackActive`]: any;
        [x: `dark_${string}_alt2_${string}_SliderTrack`]: any;
        [x: `dark_${string}_alt2_${string}_SliderThumb`]: any;
        [x: `dark_${string}_alt2_${string}_Tooltip`]: any;
        [x: `dark_${string}_alt2_${string}_ProgressIndicator`]: any;
        [x: `dark_${string}_alt2_${string}_SheetOverlay`]: any;
        [x: `dark_${string}_alt2_${string}_DialogOverlay`]: any;
        [x: `dark_${string}_alt2_${string}_ModalOverlay`]: any;
        [x: `dark_${string}_alt2_${string}_Input`]: any;
        [x: `dark_${string}_alt2_${string}_TextArea`]: any;
        readonly light: any;
        readonly dark: any;
        light_alt1: any;
        light_alt2: any;
        dark_alt1: any;
        dark_alt2: any;
        light_Card: any;
        light_Button: any;
        light_Checkbox: any;
        light_Switch: any;
        light_SwitchThumb: any;
        light_TooltipContent: any;
        light_DrawerFrame: any;
        light_Progress: any;
        light_RadioGroupItem: any;
        light_TooltipArrow: any;
        light_SliderTrackActive: any;
        light_SliderTrack: any;
        light_SliderThumb: any;
        light_Tooltip: any;
        light_ProgressIndicator: any;
        light_SheetOverlay: any;
        light_DialogOverlay: any;
        light_ModalOverlay: any;
        light_Input: any;
        light_TextArea: any;
        dark_Card: any;
        dark_Button: any;
        dark_Checkbox: any;
        dark_Switch: any;
        dark_SwitchThumb: any;
        dark_TooltipContent: any;
        dark_DrawerFrame: any;
        dark_Progress: any;
        dark_RadioGroupItem: any;
        dark_TooltipArrow: any;
        dark_SliderTrackActive: any;
        dark_SliderTrack: any;
        dark_SliderThumb: any;
        dark_Tooltip: any;
        dark_ProgressIndicator: any;
        dark_SheetOverlay: any;
        dark_DialogOverlay: any;
        dark_ModalOverlay: any;
        dark_Input: any;
        dark_TextArea: any;
    };
    palettes: import("./types").BuildThemeSuitePalettes;
};
export type BuildBaseThemesResult = ReturnType<typeof buildThemeSuite>;
//# sourceMappingURL=buildThemeSuite.d.ts.map