export { amber as amberDark } from "./legacy/dark/amber";
export { blue as blueDark } from "./legacy/dark/blue";
export { bronze as bronzeDark } from "./legacy/dark/bronze";
export { brown as brownDark } from "./legacy/dark/brown";
export { crimson as crimsonDark } from "./legacy/dark/crimson";
export { cyan as cyanDark } from "./legacy/dark/cyan";
export { gold as goldDark } from "./legacy/dark/gold";
export { grass as grassDark } from "./legacy/dark/grass";
export { gray as grayDark } from "./legacy/dark/gray";
export { green as greenDark } from "./legacy/dark/green";
export { indigo as indigoDark } from "./legacy/dark/indigo";
export { lime as limeDark } from "./legacy/dark/lime";
export { mauve as mauveDark } from "./legacy/dark/mauve";
export { mint as mintDark } from "./legacy/dark/mint";
export { olive as oliveDark } from "./legacy/dark/olive";
export { orange as orangeDark } from "./legacy/dark/orange";
export { pink as pinkDark } from "./legacy/dark/pink";
export { plum as plumDark } from "./legacy/dark/plum";
export { purple as purpleDark } from "./legacy/dark/purple";
export { red as redDark } from "./legacy/dark/red";
export { sage as sageDark } from "./legacy/dark/sage";
export { sand as sandDark } from "./legacy/dark/sand";
export { sky as skyDark } from "./legacy/dark/sky";
export { slate as slateDark } from "./legacy/dark/slate";
export { teal as tealDark } from "./legacy/dark/teal";
export { tomato as tomatoDark } from "./legacy/dark/tomato";
export { violet as violetDark } from "./legacy/dark/violet";
export { yellow as yellowDark } from "./legacy/dark/yellow";
export { amberA as amberDarkA } from "./legacy/dark/amberA";
export { blueA as blueDarkA } from "./legacy/dark/blueA";
export { bronzeA as bronzeDarkA } from "./legacy/dark/bronzeA";
export { brownA as brownDarkA } from "./legacy/dark/brownA";
export { crimsonA as crimsonDarkA } from "./legacy/dark/crimsonA";
export { cyanA as cyanDarkA } from "./legacy/dark/cyanA";
export { goldA as goldDarkA } from "./legacy/dark/goldA";
export { grassA as grassDarkA } from "./legacy/dark/grassA";
export { grayA as grayDarkA } from "./legacy/dark/grayA";
export { greenA as greenDarkA } from "./legacy/dark/greenA";
export { indigoA as indigoDarkA } from "./legacy/dark/indigoA";
export { limeA as limeDarkA } from "./legacy/dark/limeA";
export { mauveA as mauveDarkA } from "./legacy/dark/mauveA";
export { mintA as mintDarkA } from "./legacy/dark/mintA";
export { oliveA as oliveDarkA } from "./legacy/dark/oliveA";
export { orangeA as orangeDarkA } from "./legacy/dark/orangeA";
export { pinkA as pinkDarkA } from "./legacy/dark/pinkA";
export { plumA as plumDarkA } from "./legacy/dark/plumA";
export { purpleA as purpleDarkA } from "./legacy/dark/purpleA";
export { redA as redDarkA } from "./legacy/dark/redA";
export { sageA as sageDarkA } from "./legacy/dark/sageA";
export { sandA as sandDarkA } from "./legacy/dark/sandA";
export { skyA as skyDarkA } from "./legacy/dark/skyA";
export { slateA as slateDarkA } from "./legacy/dark/slateA";
export { tealA as tealDarkA } from "./legacy/dark/tealA";
export { tomatoA as tomatoDarkA } from "./legacy/dark/tomatoA";
export { violetA as violetDarkA } from "./legacy/dark/violetA";
export { yellowA as yellowDarkA } from "./legacy/dark/yellowA";
export { amber } from "./legacy/light/amber";
export { blue } from "./legacy/light/blue";
export { bronze } from "./legacy/light/bronze";
export { brown } from "./legacy/light/brown";
export { crimson } from "./legacy/light/crimson";
export { cyan } from "./legacy/light/cyan";
export { gold } from "./legacy/light/gold";
export { grass } from "./legacy/light/grass";
export { gray } from "./legacy/light/gray";
export { green } from "./legacy/light/green";
export { indigo } from "./legacy/light/indigo";
export { lime } from "./legacy/light/lime";
export { mauve } from "./legacy/light/mauve";
export { mint } from "./legacy/light/mint";
export { olive } from "./legacy/light/olive";
export { orange } from "./legacy/light/orange";
export { pink } from "./legacy/light/pink";
export { plum } from "./legacy/light/plum";
export { purple } from "./legacy/light/purple";
export { red } from "./legacy/light/red";
export { sage } from "./legacy/light/sage";
export { sand } from "./legacy/light/sand";
export { sky } from "./legacy/light/sky";
export { slate } from "./legacy/light/slate";
export { teal } from "./legacy/light/teal";
export { tomato } from "./legacy/light/tomato";
export { violet } from "./legacy/light/violet";
export { yellow } from "./legacy/light/yellow";
export { amberA } from "./legacy/light/amberA";
export { blueA } from "./legacy/light/blueA";
export { bronzeA } from "./legacy/light/bronzeA";
export { brownA } from "./legacy/light/brownA";
export { crimsonA } from "./legacy/light/crimsonA";
export { cyanA } from "./legacy/light/cyanA";
export { goldA } from "./legacy/light/goldA";
export { grassA } from "./legacy/light/grassA";
export { grayA } from "./legacy/light/grayA";
export { greenA } from "./legacy/light/greenA";
export { indigoA } from "./legacy/light/indigoA";
export { limeA } from "./legacy/light/limeA";
export { mauveA } from "./legacy/light/mauveA";
export { mintA } from "./legacy/light/mintA";
export { oliveA } from "./legacy/light/oliveA";
export { orangeA } from "./legacy/light/orangeA";
export { pinkA } from "./legacy/light/pinkA";
export { plumA } from "./legacy/light/plumA";
export { purpleA } from "./legacy/light/purpleA";
export { redA } from "./legacy/light/redA";
export { sageA } from "./legacy/light/sageA";
export { sandA } from "./legacy/light/sandA";
export { skyA } from "./legacy/light/skyA";
export { slateA } from "./legacy/light/slateA";
export { tealA } from "./legacy/light/tealA";
export { tomatoA } from "./legacy/light/tomatoA";
export { violetA } from "./legacy/light/violetA";
export { yellowA } from "./legacy/light/yellowA";
export { blackA } from "./blackA";
export { whiteA } from "./whiteA";

//# sourceMappingURL=legacy.d.ts.map