import { Button, Card, H3, Paragraph, Text, Theme, XStack, YStack } from 'tamagui'

/**
 * This usecase tests that themes generated by the v5 theme builder work correctly.
 * It uses the accent, warning, error, and success childrenThemes that the builder outputs.
 */
export function V5ThemeBuilderOutput() {
  return (
    <YStack gap="$4" padding="$4">
      {/* Test base light/dark themes */}
      <YStack gap="$2">
        <Text testID="section-base">Base Themes</Text>
        <XStack gap="$2">
          <Theme name="light">
            <Button testID="button-light">Light Theme</Button>
          </Theme>
          <Theme name="dark">
            <Button testID="button-dark">Dark Theme</Button>
          </Theme>
        </XStack>
      </YStack>

      {/* Test accent theme (user's custom color from theme builder) */}
      <YStack gap="$2">
        <Text testID="section-accent">Accent Theme</Text>
        <XStack gap="$2">
          <Theme name="light">
            <Theme name="accent">
              <Button testID="button-accent-light" backgroundColor="$background" color="$color">
                Accent Light
              </Button>
            </Theme>
          </Theme>
          <Theme name="dark">
            <Theme name="accent">
              <Button testID="button-accent-dark" backgroundColor="$background" color="$color">
                Accent Dark
              </Button>
            </Theme>
          </Theme>
        </XStack>
      </YStack>

      {/* Test semantic color themes (yellow=warning, red=error, green=success in v5) */}
      <YStack gap="$2">
        <Text testID="section-semantic">Semantic Color Themes</Text>
        <XStack gap="$2" flexWrap="wrap">
          <Theme name="yellow">
            <Button testID="button-yellow" size="$3">
              Yellow (Warning)
            </Button>
          </Theme>
          <Theme name="red">
            <Button testID="button-red" size="$3">
              Red (Error)
            </Button>
          </Theme>
          <Theme name="green">
            <Button testID="button-green" size="$3">
              Green (Success)
            </Button>
          </Theme>
        </XStack>
      </YStack>

      {/* Test color tokens from defaultChildrenThemes */}
      <YStack gap="$2">
        <Text testID="section-colors">Color Tokens</Text>
        <XStack gap="$2">
          <Theme name="blue">
            <Card testID="card-blue" padding="$3" backgroundColor="$background">
              <Text color="$color">Blue</Text>
            </Card>
          </Theme>
          <Theme name="red">
            <Card testID="card-red" padding="$3" backgroundColor="$background">
              <Text color="$color">Red</Text>
            </Card>
          </Theme>
          <Theme name="green">
            <Card testID="card-green" padding="$3" backgroundColor="$background">
              <Text color="$color">Green</Text>
            </Card>
          </Theme>
        </XStack>
      </YStack>

      {/* Test that palette colors are applied */}
      <YStack gap="$2">
        <Text testID="section-palette">Palette Colors</Text>
        <XStack gap="$1">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map((i) => (
            <YStack
              key={i}
              testID={`palette-color-${i}`}
              width={30}
              height={30}
              backgroundColor={`$color${i}` as any}
              borderRadius="$2"
            />
          ))}
        </XStack>
      </YStack>
    </YStack>
  )
}
