export declare const stylePropsUnitless: {
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
};
export declare const stylePropsTransform: {
    x: boolean;
    y: boolean;
    scale: boolean;
    perspective: boolean;
    scaleX: boolean;
    scaleY: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
};
export declare const validStylesOnBaseProps: {
    placeholderTextColor: boolean;
};
export declare const stylePropsView: {
    elevationAndroid?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    userSelect?: boolean | undefined;
    cursor?: boolean | undefined;
    contain?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    boxSizing?: boolean | undefined;
    boxShadow?: boolean | undefined;
    outlineColor?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    placeholderTextColor: boolean;
    backfaceVisibility: boolean;
    backgroundColor: boolean;
    borderBottomColor: boolean;
    borderBottomEndRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderColor: boolean;
    borderEndColor: boolean;
    borderLeftColor: boolean;
    borderLeftWidth: boolean;
    borderRadius: boolean;
    borderRightColor: boolean;
    borderRightWidth: boolean;
    borderStartColor: boolean;
    borderStyle: boolean;
    borderTopColor: boolean;
    borderTopEndRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    height: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    maxHeight: boolean;
    maxWidth: boolean;
    minHeight: boolean;
    minWidth: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    width: boolean;
    zIndex: boolean;
    direction: boolean;
    shadowColor: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const stylePropsFont: {
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
};
export declare const stylePropsTextOnly: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    userSelect?: boolean | undefined;
    selectable?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp?: boolean | undefined;
    WebkitBoxOrient?: boolean | undefined;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
    color: boolean;
};
export declare const stylePropsText: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    userSelect?: boolean | undefined;
    selectable?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp: boolean;
    WebkitBoxOrient?: boolean | undefined;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
    color: boolean;
    elevationAndroid?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    contain?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    boxSizing?: boolean | undefined;
    boxShadow?: boolean | undefined;
    outlineColor?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    placeholderTextColor: boolean;
    backfaceVisibility: boolean;
    backgroundColor: boolean;
    borderBottomColor: boolean;
    borderBottomEndRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderColor: boolean;
    borderEndColor: boolean;
    borderLeftColor: boolean;
    borderLeftWidth: boolean;
    borderRadius: boolean;
    borderRightColor: boolean;
    borderRightWidth: boolean;
    borderStartColor: boolean;
    borderStyle: boolean;
    borderTopColor: boolean;
    borderTopEndRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    height: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    maxHeight: boolean;
    maxWidth: boolean;
    minHeight: boolean;
    minWidth: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    width: boolean;
    zIndex: boolean;
    direction: boolean;
    shadowColor: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const stylePropsAll: {
    whiteSpace?: boolean | undefined;
    wordWrap?: boolean | undefined;
    textOverflow?: boolean | undefined;
    textDecorationDistance?: boolean | undefined;
    userSelect?: boolean | undefined;
    selectable?: boolean | undefined;
    cursor?: boolean | undefined;
    WebkitLineClamp: boolean;
    WebkitBoxOrient?: boolean | undefined;
    textAlign: boolean;
    textDecorationLine: boolean;
    textDecorationStyle: boolean;
    textDecorationColor: boolean;
    textShadowColor: boolean;
    textShadowOffset: boolean;
    textShadowRadius: boolean;
    fontFamily: boolean;
    fontSize: boolean;
    fontStyle: boolean;
    fontWeight: boolean;
    letterSpacing: boolean;
    lineHeight: boolean;
    textTransform: boolean;
    color: boolean;
    elevationAndroid?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    contain?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    boxSizing?: boolean | undefined;
    boxShadow?: boolean | undefined;
    outlineColor?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    placeholderTextColor: boolean;
    backfaceVisibility: boolean;
    backgroundColor: boolean;
    borderBottomColor: boolean;
    borderBottomEndRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderColor: boolean;
    borderEndColor: boolean;
    borderLeftColor: boolean;
    borderLeftWidth: boolean;
    borderRadius: boolean;
    borderRightColor: boolean;
    borderRightWidth: boolean;
    borderStartColor: boolean;
    borderStyle: boolean;
    borderTopColor: boolean;
    borderTopEndRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    height: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    maxHeight: boolean;
    maxWidth: boolean;
    minHeight: boolean;
    minWidth: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    width: boolean;
    zIndex: boolean;
    direction: boolean;
    shadowColor: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
};
export declare const validPseudoKeys: {
    enterStyle: boolean;
    exitStyle: boolean;
    hoverStyle: boolean;
    pressStyle: boolean;
    focusStyle: boolean;
};
export declare const validStyles: {
    elevationAndroid?: boolean | undefined;
    borderBottomStyle?: boolean | undefined;
    borderTopStyle?: boolean | undefined;
    borderLeftStyle?: boolean | undefined;
    borderRightStyle?: boolean | undefined;
    overflowX?: boolean | undefined;
    overflowY?: boolean | undefined;
    userSelect?: boolean | undefined;
    cursor?: boolean | undefined;
    contain?: boolean | undefined;
    pointerEvents?: boolean | undefined;
    boxSizing?: boolean | undefined;
    boxShadow?: boolean | undefined;
    outlineColor?: boolean | undefined;
    outlineStyle?: boolean | undefined;
    outlineOffset?: boolean | undefined;
    outlineWidth?: boolean | undefined;
    WebkitLineClamp: boolean;
    animationIterationCount: boolean;
    aspectRatio: boolean;
    borderImageOutset: boolean;
    borderImageSlice: boolean;
    borderImageWidth: boolean;
    columnCount: boolean;
    flex: boolean;
    flexGrow: boolean;
    flexOrder: boolean;
    flexPositive: boolean;
    flexShrink: boolean;
    flexNegative: boolean;
    fontWeight: boolean;
    gridRow: boolean;
    gridRowEnd: boolean;
    gridRowGap: boolean;
    gridRowStart: boolean;
    gridColumn: boolean;
    gridColumnEnd: boolean;
    gridColumnGap: boolean;
    gridColumnStart: boolean;
    lineClamp: boolean;
    opacity: boolean;
    order: boolean;
    orphans: boolean;
    tabSize: boolean;
    widows: boolean;
    zoom: boolean;
    scale: boolean;
    scaleX: boolean;
    scaleY: boolean;
    scaleZ: boolean;
    shadowOpacity: boolean;
    x: boolean;
    y: boolean;
    perspective: boolean;
    skewX: boolean;
    skewY: boolean;
    matrix: boolean;
    rotate: boolean;
    rotateY: boolean;
    rotateX: boolean;
    rotateZ: boolean;
    placeholderTextColor: boolean;
    backfaceVisibility: boolean;
    backgroundColor: boolean;
    borderBottomColor: boolean;
    borderBottomEndRadius: boolean;
    borderBottomLeftRadius: boolean;
    borderBottomRightRadius: boolean;
    borderBottomStartRadius: boolean;
    borderBottomWidth: boolean;
    borderColor: boolean;
    borderEndColor: boolean;
    borderLeftColor: boolean;
    borderLeftWidth: boolean;
    borderRadius: boolean;
    borderRightColor: boolean;
    borderRightWidth: boolean;
    borderStartColor: boolean;
    borderStyle: boolean;
    borderTopColor: boolean;
    borderTopEndRadius: boolean;
    borderTopLeftRadius: boolean;
    borderTopRightRadius: boolean;
    borderTopStartRadius: boolean;
    borderTopWidth: boolean;
    borderWidth: boolean;
    transform: boolean;
    alignContent: boolean;
    alignItems: boolean;
    alignSelf: boolean;
    borderEndWidth: boolean;
    borderStartWidth: boolean;
    bottom: boolean;
    display: boolean;
    end: boolean;
    flexBasis: boolean;
    flexDirection: boolean;
    flexWrap: boolean;
    gap: boolean;
    columnGap: boolean;
    rowGap: boolean;
    height: boolean;
    justifyContent: boolean;
    left: boolean;
    margin: boolean;
    marginBottom: boolean;
    marginEnd: boolean;
    marginHorizontal: boolean;
    marginLeft: boolean;
    marginRight: boolean;
    marginStart: boolean;
    marginTop: boolean;
    marginVertical: boolean;
    maxHeight: boolean;
    maxWidth: boolean;
    minHeight: boolean;
    minWidth: boolean;
    overflow: boolean;
    padding: boolean;
    paddingBottom: boolean;
    paddingEnd: boolean;
    paddingHorizontal: boolean;
    paddingLeft: boolean;
    paddingRight: boolean;
    paddingStart: boolean;
    paddingTop: boolean;
    paddingVertical: boolean;
    position: boolean;
    right: boolean;
    start: boolean;
    top: boolean;
    width: boolean;
    zIndex: boolean;
    direction: boolean;
    shadowColor: boolean;
    shadowOffset: boolean;
    shadowRadius: boolean;
    enterStyle: boolean;
    exitStyle: boolean;
    hoverStyle: boolean;
    pressStyle: boolean;
    focusStyle: boolean;
};
//# sourceMappingURL=validStyleProps.d.ts.map