export declare const stylePropsTransform: Readonly<{
    x: true;
    y: true;
    scale: true;
    perspective: true;
    scaleX: true;
    scaleY: true;
    skewX: true;
    skewY: true;
    matrix: true;
    rotate: true;
    rotateY: true;
    rotateX: true;
    rotateZ: true;
}>;
export declare const stylePropsView: Readonly<{
    overflowX?: true | undefined;
    overflowY?: true | undefined;
    userSelect?: true | undefined;
    cursor?: true | undefined;
    contain?: true | undefined;
    pointerEvents?: true | undefined;
    boxSizing?: true | undefined;
    boxShadow?: true | undefined;
    x: true;
    y: true;
    scale: true;
    perspective: true;
    scaleX: true;
    scaleY: true;
    skewX: true;
    skewY: true;
    matrix: true;
    rotate: true;
    rotateY: true;
    rotateX: true;
    rotateZ: true;
    backfaceVisibility: true;
    backgroundColor: true;
    borderBottomColor: true;
    borderBottomStyle: true;
    borderTopStyle: true;
    borderLeftStyle: true;
    borderRightStyle: true;
    borderBottomEndRadius: true;
    borderBottomLeftRadius: true;
    borderBottomRightRadius: true;
    borderBottomStartRadius: true;
    borderBottomWidth: true;
    borderColor: true;
    borderEndColor: true;
    borderLeftColor: true;
    borderLeftWidth: true;
    borderRadius: true;
    borderRightColor: true;
    borderRightWidth: true;
    borderStartColor: true;
    borderStyle: true;
    borderTopColor: true;
    borderTopEndRadius: true;
    borderTopLeftRadius: true;
    borderTopRightRadius: true;
    borderTopStartRadius: true;
    borderTopWidth: true;
    borderWidth: true;
    opacity: true;
    transform: true;
    alignContent: true;
    alignItems: true;
    alignSelf: true;
    aspectRatio: true;
    borderEndWidth: true;
    borderStartWidth: true;
    bottom: true;
    display: true;
    end: true;
    flex: true;
    flexBasis: true;
    flexDirection: true;
    flexGrow: true;
    flexShrink: true;
    flexWrap: true;
    height: true;
    justifyContent: true;
    left: true;
    margin: true;
    marginBottom: true;
    marginEnd: true;
    marginHorizontal: true;
    marginLeft: true;
    marginRight: true;
    marginStart: true;
    marginTop: true;
    marginVertical: true;
    maxHeight: true;
    maxWidth: true;
    minHeight: true;
    minWidth: true;
    overflow: true;
    padding: true;
    paddingBottom: true;
    paddingEnd: true;
    paddingHorizontal: true;
    paddingLeft: true;
    paddingRight: true;
    paddingStart: true;
    paddingTop: true;
    paddingVertical: true;
    position: true;
    right: true;
    start: true;
    top: true;
    width: true;
    zIndex: true;
    direction: true;
    shadowColor: true;
    shadowOffset: true;
    shadowOpacity: true;
    shadowRadius: true;
}>;
export declare const stylePropsTextOnly: Readonly<{
    whiteSpace?: true | undefined;
    wordWrap?: true | undefined;
    textOverflow?: true | undefined;
    textDecorationDistance?: true | undefined;
    userSelect?: true | undefined;
    selectable?: true | undefined;
    cursor?: true | undefined;
    color: true;
    fontFamily: true;
    fontSize: true;
    fontStyle: true;
    fontWeight: true;
    letterSpacing: true;
    lineHeight: true;
    textAlign: true;
    textDecorationLine: true;
    textDecorationStyle: true;
    textDecorationColor: true;
    textShadowColor: true;
    textShadowOffset: true;
    textShadowRadius: true;
    textTransform: true;
}>;
export declare const stylePropsText: Readonly<{
    whiteSpace?: true | undefined;
    wordWrap?: true | undefined;
    textOverflow?: true | undefined;
    textDecorationDistance?: true | undefined;
    userSelect?: true | undefined;
    selectable?: true | undefined;
    cursor?: true | undefined;
    color: true;
    fontFamily: true;
    fontSize: true;
    fontStyle: true;
    fontWeight: true;
    letterSpacing: true;
    lineHeight: true;
    textAlign: true;
    textDecorationLine: true;
    textDecorationStyle: true;
    textDecorationColor: true;
    textShadowColor: true;
    textShadowOffset: true;
    textShadowRadius: true;
    textTransform: true;
    overflowX?: true | undefined;
    overflowY?: true | undefined;
    contain?: true | undefined;
    pointerEvents?: true | undefined;
    boxSizing?: true | undefined;
    boxShadow?: true | undefined;
    x: true;
    y: true;
    scale: true;
    perspective: true;
    scaleX: true;
    scaleY: true;
    skewX: true;
    skewY: true;
    matrix: true;
    rotate: true;
    rotateY: true;
    rotateX: true;
    rotateZ: true;
    backfaceVisibility: true;
    backgroundColor: true;
    borderBottomColor: true;
    borderBottomStyle: true;
    borderTopStyle: true;
    borderLeftStyle: true;
    borderRightStyle: true;
    borderBottomEndRadius: true;
    borderBottomLeftRadius: true;
    borderBottomRightRadius: true;
    borderBottomStartRadius: true;
    borderBottomWidth: true;
    borderColor: true;
    borderEndColor: true;
    borderLeftColor: true;
    borderLeftWidth: true;
    borderRadius: true;
    borderRightColor: true;
    borderRightWidth: true;
    borderStartColor: true;
    borderStyle: true;
    borderTopColor: true;
    borderTopEndRadius: true;
    borderTopLeftRadius: true;
    borderTopRightRadius: true;
    borderTopStartRadius: true;
    borderTopWidth: true;
    borderWidth: true;
    opacity: true;
    transform: true;
    alignContent: true;
    alignItems: true;
    alignSelf: true;
    aspectRatio: true;
    borderEndWidth: true;
    borderStartWidth: true;
    bottom: true;
    display: true;
    end: true;
    flex: true;
    flexBasis: true;
    flexDirection: true;
    flexGrow: true;
    flexShrink: true;
    flexWrap: true;
    height: true;
    justifyContent: true;
    left: true;
    margin: true;
    marginBottom: true;
    marginEnd: true;
    marginHorizontal: true;
    marginLeft: true;
    marginRight: true;
    marginStart: true;
    marginTop: true;
    marginVertical: true;
    maxHeight: true;
    maxWidth: true;
    minHeight: true;
    minWidth: true;
    overflow: true;
    padding: true;
    paddingBottom: true;
    paddingEnd: true;
    paddingHorizontal: true;
    paddingLeft: true;
    paddingRight: true;
    paddingStart: true;
    paddingTop: true;
    paddingVertical: true;
    position: true;
    right: true;
    start: true;
    top: true;
    width: true;
    zIndex: true;
    direction: true;
    shadowColor: true;
    shadowOffset: true;
    shadowOpacity: true;
    shadowRadius: true;
}>;
export declare const stylePropsAll: Readonly<{
    whiteSpace?: true | undefined;
    wordWrap?: true | undefined;
    textOverflow?: true | undefined;
    textDecorationDistance?: true | undefined;
    userSelect?: true | undefined;
    selectable?: true | undefined;
    cursor?: true | undefined;
    color: true;
    fontFamily: true;
    fontSize: true;
    fontStyle: true;
    fontWeight: true;
    letterSpacing: true;
    lineHeight: true;
    textAlign: true;
    textDecorationLine: true;
    textDecorationStyle: true;
    textDecorationColor: true;
    textShadowColor: true;
    textShadowOffset: true;
    textShadowRadius: true;
    textTransform: true;
    overflowX?: true | undefined;
    overflowY?: true | undefined;
    contain?: true | undefined;
    pointerEvents?: true | undefined;
    boxSizing?: true | undefined;
    boxShadow?: true | undefined;
    x: true;
    y: true;
    scale: true;
    perspective: true;
    scaleX: true;
    scaleY: true;
    skewX: true;
    skewY: true;
    matrix: true;
    rotate: true;
    rotateY: true;
    rotateX: true;
    rotateZ: true;
    backfaceVisibility: true;
    backgroundColor: true;
    borderBottomColor: true;
    borderBottomStyle: true;
    borderTopStyle: true;
    borderLeftStyle: true;
    borderRightStyle: true;
    borderBottomEndRadius: true;
    borderBottomLeftRadius: true;
    borderBottomRightRadius: true;
    borderBottomStartRadius: true;
    borderBottomWidth: true;
    borderColor: true;
    borderEndColor: true;
    borderLeftColor: true;
    borderLeftWidth: true;
    borderRadius: true;
    borderRightColor: true;
    borderRightWidth: true;
    borderStartColor: true;
    borderStyle: true;
    borderTopColor: true;
    borderTopEndRadius: true;
    borderTopLeftRadius: true;
    borderTopRightRadius: true;
    borderTopStartRadius: true;
    borderTopWidth: true;
    borderWidth: true;
    opacity: true;
    transform: true;
    alignContent: true;
    alignItems: true;
    alignSelf: true;
    aspectRatio: true;
    borderEndWidth: true;
    borderStartWidth: true;
    bottom: true;
    display: true;
    end: true;
    flex: true;
    flexBasis: true;
    flexDirection: true;
    flexGrow: true;
    flexShrink: true;
    flexWrap: true;
    height: true;
    justifyContent: true;
    left: true;
    margin: true;
    marginBottom: true;
    marginEnd: true;
    marginHorizontal: true;
    marginLeft: true;
    marginRight: true;
    marginStart: true;
    marginTop: true;
    marginVertical: true;
    maxHeight: true;
    maxWidth: true;
    minHeight: true;
    minWidth: true;
    overflow: true;
    padding: true;
    paddingBottom: true;
    paddingEnd: true;
    paddingHorizontal: true;
    paddingLeft: true;
    paddingRight: true;
    paddingStart: true;
    paddingTop: true;
    paddingVertical: true;
    position: true;
    right: true;
    start: true;
    top: true;
    width: true;
    zIndex: true;
    direction: true;
    shadowColor: true;
    shadowOffset: true;
    shadowOpacity: true;
    shadowRadius: true;
}>;
export declare const validPseudoKeys: Readonly<{
    enterStyle: true;
    exitStyle: true;
    hoverStyle: true;
    pressStyle: true;
    focusStyle: true;
}>;
export declare const validStyles: Readonly<{
    overflowX?: true | undefined;
    overflowY?: true | undefined;
    userSelect?: true | undefined;
    cursor?: true | undefined;
    contain?: true | undefined;
    pointerEvents?: true | undefined;
    boxSizing?: true | undefined;
    boxShadow?: true | undefined;
    x: true;
    y: true;
    scale: true;
    perspective: true;
    scaleX: true;
    scaleY: true;
    skewX: true;
    skewY: true;
    matrix: true;
    rotate: true;
    rotateY: true;
    rotateX: true;
    rotateZ: true;
    backfaceVisibility: true;
    backgroundColor: true;
    borderBottomColor: true;
    borderBottomStyle: true;
    borderTopStyle: true;
    borderLeftStyle: true;
    borderRightStyle: true;
    borderBottomEndRadius: true;
    borderBottomLeftRadius: true;
    borderBottomRightRadius: true;
    borderBottomStartRadius: true;
    borderBottomWidth: true;
    borderColor: true;
    borderEndColor: true;
    borderLeftColor: true;
    borderLeftWidth: true;
    borderRadius: true;
    borderRightColor: true;
    borderRightWidth: true;
    borderStartColor: true;
    borderStyle: true;
    borderTopColor: true;
    borderTopEndRadius: true;
    borderTopLeftRadius: true;
    borderTopRightRadius: true;
    borderTopStartRadius: true;
    borderTopWidth: true;
    borderWidth: true;
    opacity: true;
    transform: true;
    alignContent: true;
    alignItems: true;
    alignSelf: true;
    aspectRatio: true;
    borderEndWidth: true;
    borderStartWidth: true;
    bottom: true;
    display: true;
    end: true;
    flex: true;
    flexBasis: true;
    flexDirection: true;
    flexGrow: true;
    flexShrink: true;
    flexWrap: true;
    height: true;
    justifyContent: true;
    left: true;
    margin: true;
    marginBottom: true;
    marginEnd: true;
    marginHorizontal: true;
    marginLeft: true;
    marginRight: true;
    marginStart: true;
    marginTop: true;
    marginVertical: true;
    maxHeight: true;
    maxWidth: true;
    minHeight: true;
    minWidth: true;
    overflow: true;
    padding: true;
    paddingBottom: true;
    paddingEnd: true;
    paddingHorizontal: true;
    paddingLeft: true;
    paddingRight: true;
    paddingStart: true;
    paddingTop: true;
    paddingVertical: true;
    position: true;
    right: true;
    start: true;
    top: true;
    width: true;
    zIndex: true;
    direction: true;
    shadowColor: true;
    shadowOffset: true;
    shadowOpacity: true;
    shadowRadius: true;
    enterStyle: true;
    exitStyle: true;
    hoverStyle: true;
    pressStyle: true;
    focusStyle: true;
}>;
//# sourceMappingURL=validStyleProps.d.ts.map