type Theme = {
    accentBackground: string;
    accentColor: string;
    shadowColor: string;
    shadowColorHover: string;
    shadowColorPress: string;
    shadowColorFocus: string;
    background0: string;
    background025: string;
    background05: string;
    background075: string;
    color1: string;
    color2: string;
    color3: string;
    color4: string;
    color5: string;
    color6: string;
    color7: string;
    color8: string;
    color9: string;
    color10: string;
    color11: string;
    color12: string;
    color0: string;
    color025: string;
    color05: string;
    color075: string;
    background: string;
    backgroundHover: string;
    backgroundPress: string;
    backgroundFocus: string;
    borderColor: string;
    borderColorHover: string;
    borderColorPress: string;
    borderColorFocus: string;
    color: string;
    colorHover: string;
    colorPress: string;
    colorFocus: string;
    colorTransparent: string;
    placeholderColor: string;
    outlineColor: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
};
export declare const light: Theme;
export declare const dark: Theme;
export declare const light_accent: Theme;
export declare const dark_accent: Theme;
export declare const light_error: Theme;
export declare const light_warning: Theme;
export declare const light_success: Theme;
export declare const dark_error: Theme;
export declare const dark_warning: Theme;
export declare const dark_success: Theme;
export declare const light_ListItem: Theme;
export declare const light_SelectTrigger: Theme;
export declare const light_Card: Theme;
export declare const light_Progress: Theme;
export declare const light_TooltipArrow: Theme;
export declare const light_SliderTrack: Theme;
export declare const light_Input: Theme;
export declare const light_TextArea: Theme;
export declare const light_Button: Theme;
export declare const light_SliderTrackActive: Theme;
export declare const light_Checkbox: Theme;
export declare const light_Switch: Theme;
export declare const light_TooltipContent: Theme;
export declare const light_RadioGroupItem: Theme;
export declare const light_SwitchThumb: Theme;
export declare const light_SliderThumb: Theme;
export declare const light_Tooltip: Theme;
export declare const light_ProgressIndicator: Theme;
export declare const dark_ListItem: Theme;
export declare const dark_SelectTrigger: Theme;
export declare const dark_Card: Theme;
export declare const dark_Progress: Theme;
export declare const dark_TooltipArrow: Theme;
export declare const dark_SliderTrack: Theme;
export declare const dark_Input: Theme;
export declare const dark_TextArea: Theme;
export declare const dark_Button: Theme;
export declare const dark_SliderTrackActive: Theme;
export declare const dark_Checkbox: Theme;
export declare const dark_Switch: Theme;
export declare const dark_TooltipContent: Theme;
export declare const dark_RadioGroupItem: Theme;
export declare const dark_SwitchThumb: Theme;
export declare const dark_SliderThumb: Theme;
export declare const dark_Tooltip: Theme;
export declare const dark_ProgressIndicator: Theme;
export declare const light_error_ListItem: Theme;
export declare const light_error_SelectTrigger: Theme;
export declare const light_error_Card: Theme;
export declare const light_error_Progress: Theme;
export declare const light_error_TooltipArrow: Theme;
export declare const light_error_SliderTrack: Theme;
export declare const light_error_Input: Theme;
export declare const light_error_TextArea: Theme;
export declare const light_error_Button: Theme;
export declare const light_error_SliderTrackActive: Theme;
export declare const light_error_Checkbox: Theme;
export declare const light_error_Switch: Theme;
export declare const light_error_TooltipContent: Theme;
export declare const light_error_RadioGroupItem: Theme;
export declare const light_error_SwitchThumb: Theme;
export declare const light_error_SliderThumb: Theme;
export declare const light_error_Tooltip: Theme;
export declare const light_error_ProgressIndicator: Theme;
export declare const light_warning_ListItem: Theme;
export declare const light_warning_SelectTrigger: Theme;
export declare const light_warning_Card: Theme;
export declare const light_warning_Progress: Theme;
export declare const light_warning_TooltipArrow: Theme;
export declare const light_warning_SliderTrack: Theme;
export declare const light_warning_Input: Theme;
export declare const light_warning_TextArea: Theme;
export declare const light_warning_Button: Theme;
export declare const light_warning_SliderTrackActive: Theme;
export declare const light_warning_Checkbox: Theme;
export declare const light_warning_Switch: Theme;
export declare const light_warning_TooltipContent: Theme;
export declare const light_warning_RadioGroupItem: Theme;
export declare const light_warning_SwitchThumb: Theme;
export declare const light_warning_SliderThumb: Theme;
export declare const light_warning_Tooltip: Theme;
export declare const light_warning_ProgressIndicator: Theme;
export declare const light_success_ListItem: Theme;
export declare const light_success_SelectTrigger: Theme;
export declare const light_success_Card: Theme;
export declare const light_success_Progress: Theme;
export declare const light_success_TooltipArrow: Theme;
export declare const light_success_SliderTrack: Theme;
export declare const light_success_Input: Theme;
export declare const light_success_TextArea: Theme;
export declare const light_success_Button: Theme;
export declare const light_success_SliderTrackActive: Theme;
export declare const light_success_Checkbox: Theme;
export declare const light_success_Switch: Theme;
export declare const light_success_TooltipContent: Theme;
export declare const light_success_RadioGroupItem: Theme;
export declare const light_success_SwitchThumb: Theme;
export declare const light_success_SliderThumb: Theme;
export declare const light_success_Tooltip: Theme;
export declare const light_success_ProgressIndicator: Theme;
export declare const dark_error_ListItem: Theme;
export declare const dark_error_SelectTrigger: Theme;
export declare const dark_error_Card: Theme;
export declare const dark_error_Progress: Theme;
export declare const dark_error_TooltipArrow: Theme;
export declare const dark_error_SliderTrack: Theme;
export declare const dark_error_Input: Theme;
export declare const dark_error_TextArea: Theme;
export declare const dark_error_Button: Theme;
export declare const dark_error_SliderTrackActive: Theme;
export declare const dark_error_Checkbox: Theme;
export declare const dark_error_Switch: Theme;
export declare const dark_error_TooltipContent: Theme;
export declare const dark_error_RadioGroupItem: Theme;
export declare const dark_error_SwitchThumb: Theme;
export declare const dark_error_SliderThumb: Theme;
export declare const dark_error_Tooltip: Theme;
export declare const dark_error_ProgressIndicator: Theme;
export declare const dark_warning_ListItem: Theme;
export declare const dark_warning_SelectTrigger: Theme;
export declare const dark_warning_Card: Theme;
export declare const dark_warning_Progress: Theme;
export declare const dark_warning_TooltipArrow: Theme;
export declare const dark_warning_SliderTrack: Theme;
export declare const dark_warning_Input: Theme;
export declare const dark_warning_TextArea: Theme;
export declare const dark_warning_Button: Theme;
export declare const dark_warning_SliderTrackActive: Theme;
export declare const dark_warning_Checkbox: Theme;
export declare const dark_warning_Switch: Theme;
export declare const dark_warning_TooltipContent: Theme;
export declare const dark_warning_RadioGroupItem: Theme;
export declare const dark_warning_SwitchThumb: Theme;
export declare const dark_warning_SliderThumb: Theme;
export declare const dark_warning_Tooltip: Theme;
export declare const dark_warning_ProgressIndicator: Theme;
export declare const dark_success_ListItem: Theme;
export declare const dark_success_SelectTrigger: Theme;
export declare const dark_success_Card: Theme;
export declare const dark_success_Progress: Theme;
export declare const dark_success_TooltipArrow: Theme;
export declare const dark_success_SliderTrack: Theme;
export declare const dark_success_Input: Theme;
export declare const dark_success_TextArea: Theme;
export declare const dark_success_Button: Theme;
export declare const dark_success_SliderTrackActive: Theme;
export declare const dark_success_Checkbox: Theme;
export declare const dark_success_Switch: Theme;
export declare const dark_success_TooltipContent: Theme;
export declare const dark_success_RadioGroupItem: Theme;
export declare const dark_success_SwitchThumb: Theme;
export declare const dark_success_SliderThumb: Theme;
export declare const dark_success_Tooltip: Theme;
export declare const dark_success_ProgressIndicator: Theme;
export {};
//# sourceMappingURL=generated-v4.d.ts.map