export declare const size: {
    0: number;
    '0-25': number;
    '0-5': number;
    '0-75': number;
    1: number;
    '1-5': number;
    2: number;
    '2-5': number;
    3: number;
    '3-5': number;
    4: number;
    '4-5': number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
    13: number;
    14: number;
    15: number;
    16: number;
    17: number;
    18: number;
    19: number;
    20: number;
};
type SizeKeysIn = keyof typeof size;
type Sizes = {
    [Key in SizeKeysIn]: number;
};
type SizeKeys = `${SizeKeysIn}`;
export declare const spaces: (readonly [string, number])[];
export declare const spacesNegative: (string | number)[][];
type SizeKeysWithNegatives = Exclude<`-${SizeKeys}`, '-0'> | SizeKeys;
export declare const space: {
    [Key in SizeKeysWithNegatives]: Key extends keyof Sizes ? Sizes[Key] : number;
};
export declare const zIndex: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
export declare const radius: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
};
export declare const tokens: {
    "size-0-25": number;
    "size-0-5": number;
    "size-0-75": number;
    "size-1-5": number;
    "size-2-5": number;
    "size-3-5": number;
    "size-4-5": number;
    "space--0-25": number;
    "space--0-5": number;
    "space--0-75": number;
    "space--1": number;
    "space--1-5": number;
    "space--10": number;
    "space--11": number;
    "space--12": number;
    "space--13": number;
    "space--14": number;
    "space--15": number;
    "space--16": number;
    "space--17": number;
    "space--18": number;
    "space--19": number;
    "space--2": number;
    "space--2-5": number;
    "space--20": number;
    "space--3": number;
    "space--3-5": number;
    "space--4": number;
    "space--4-5": number;
    "space--5": number;
    "space--6": number;
    "space--7": number;
    "space--8": number;
    "space--9": number;
    "space-0": number;
    "space-0-25": number;
    "space-0-5": number;
    "space-0-75": number;
    "space-1": number;
    "space-1-5": number;
    "space-10": number;
    "space-11": number;
    "space-12": number;
    "space-13": number;
    "space-14": number;
    "space-15": number;
    "space-16": number;
    "space-17": number;
    "space-18": number;
    "space-19": number;
    "space-2": number;
    "space-2-5": number;
    "space-20": number;
    "space-3": number;
    "space-3-5": number;
    "space-4": number;
    "space-4-5": number;
    "space-5": number;
    "space-6": number;
    "space-7": number;
    "space-8": number;
    "space-9": number;
};
export type V5Tokens = typeof tokens;
export {};
//# sourceMappingURL=v5-tokens.d.ts.map