'use client'

import React from 'react'

import SupabaseProvider from './SupabaseProvider'
import { TamaguiProvider } from './TamaguiProvider'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <TamaguiProvider>{children}</TamaguiProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
