// Generated by dts-bundle-generator v5.9.0

export interface TamaguiOptions {
	components: string[];
	config?: string;
	evaluateVars?: boolean;
	importsWhitelist?: string[];
	disableExtraction?: boolean;
	disableDebugAttr?: boolean;
	disableExtractInlineMedia?: boolean;
	exclude?: RegExp;
	logTimings?: boolean;
	cssPath?: string;
	cssData?: any;
	deoptProps?: Set<string>;
	excludeProps?: string[];
}
export declare const withTamagui: (tamaguiOptions: TamaguiOptions) => (nextConfig?: any) => any;

export {};
