// Generated by dts-bundle-generator v5.9.0

export interface TamaguiOptions {
	components: string[];
	config?: string;
	evaluateVars?: boolean;
	importsWhitelist?: string[];
	disableExtraction?: boolean;
	exclude?: RegExp;
	logTimings?: boolean;
	cssPath?: string;
	cssData?: any;
	deoptProps?: Set<string>;
	excludeProps?: string[];
}
export declare const withTamagui: (tamaguiOptions: TamaguiOptions) => {
	webpack: (webpackConfig: any, options: any) => any;
};

export {};
