create table "public"."discord_invites" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "subscription_id" text not null,
    "discord_user_id" text not null,
    "discord_channel_id" text not null
);


alter table "public"."discord_invites" enable row level security;

CREATE UNIQUE INDEX discord_invites_pkey ON public.discord_invites USING btree (id);

alter table "public"."discord_invites" add constraint "discord_invites_pkey" PRIMARY KEY using index "discord_invites_pkey";

alter table "public"."discord_invites" add constraint "discord_invites_subscription_id_fkey" FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE not valid;

alter table "public"."discord_invites" validate constraint "discord_invites_subscription_id_fkey";


