create table "public"."app_installations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "installed_at" timestamp with time zone,
    "github_installation_id" bigint,
    "user_id" uuid
);


alter table "public"."app_installations" enable row level security;

CREATE UNIQUE INDEX app_installations_pkey ON public.app_installations USING btree (id);

alter table "public"."app_installations" add constraint "app_installations_pkey" PRIMARY KEY using index "app_installations_pkey";

alter table "public"."app_installations" add constraint "app_installations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."app_installations" validate constraint "app_installations_user_id_fkey";
