create table "public"."bot_pull_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "base_pr_number" bigint not null,
    "final_pr_num" bigint,
    "github_installation_id" bigint not null,
    "error" text,
    "repo_id" bigint
);


alter table "public"."bot_pull_requests" enable row level security;

CREATE UNIQUE INDEX app_installations_github_installation_id_key ON public.app_installations USING btree (github_installation_id);

CREATE UNIQUE INDEX bot_pull_requests_pkey ON public.bot_pull_requests USING btree (id);

alter table "public"."bot_pull_requests" add constraint "bot_pull_requests_pkey" PRIMARY KEY using index "bot_pull_requests_pkey";

alter table "public"."app_installations" add constraint "app_installations_github_installation_id_key" UNIQUE using index "app_installations_github_installation_id_key";

alter table "public"."bot_pull_requests" add constraint "bot_pull_requests_github_installation_id_fkey" FOREIGN KEY (github_installation_id) REFERENCES app_installations(github_installation_id) ON DELETE CASCADE not valid;

alter table "public"."bot_pull_requests" validate constraint "bot_pull_requests_github_installation_id_fkey";


