CREATE TABLE "public"."theme_histories" (
  "id" bigint generated by default as identity not null,
  "user_id" UUID NOT NULL REFERENCES auth.users(id),
  "search_query" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "theme_data" JSONB NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(user_id, search_query)
);

CREATE INDEX idx_theme_histories_user_id ON theme_histories(user_id);
CREATE INDEX idx_theme_histories_created_at ON theme_histories(created_at);