-- pro whitelist table for granting pro access to specific github users
-- admin-only table (no RLS, accessed via service role only)
create table if not exists pro_whitelist (
  id bigint generated by default as identity primary key,
  github_username text not null unique,
  note text, -- optional note about why they were whitelisted (e.g. "contributor", "partner")
  created_at timestamptz default now() not null,
  created_by uuid references auth.users(id) on delete set null -- admin who added them
);

-- index for fast lookup by github username (used in access checks)
create index if not exists pro_whitelist_github_username_idx on pro_whitelist(github_username);

-- NO RLS - this table is only accessed via supabaseAdmin (service role)
-- this prevents any client-side manipulation

-- seed initial whitelist entry for DaveyEke (contributor)
insert into pro_whitelist (github_username, note)
values ('DaveyEke', 'contributor - 51 contributions')
on conflict (github_username) do nothing;
