export declare const overlayThemeDefinitions: {
    parent: string;
    theme: {
        background: string;
    };
}[];
export declare const componentThemeDefinitions: {
    ListItem: ({
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        parent: string;
        mask: "strengthen";
    } | {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        parent: string;
        mask: "identity";
    })[];
    Card: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften";
    };
    Button: {
        override: {
            borderColor: string;
            borderColorHover: string;
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften2";
    };
    Checkbox: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "softenBorder2";
    };
    Switch: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften2";
    };
    SwitchThumb: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "inverseStrengthen2";
    };
    TooltipContent: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften2";
    };
    DrawerFrame: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften";
    };
    Progress: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften";
    };
    RadioGroupItem: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "softenBorder2";
    };
    TooltipArrow: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften";
    };
    SliderTrackActive: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "inverseSoften";
    };
    SliderTrack: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "soften2";
    };
    SliderThumb: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "inverse";
    };
    Tooltip: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "inverse";
    };
    ProgressIndicator: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "inverse";
    };
    SheetOverlay: {
        parent: string;
        theme: {
            background: string;
        };
    }[];
    DialogOverlay: {
        parent: string;
        theme: {
            background: string;
        };
    }[];
    ModalOverlay: {
        parent: string;
        theme: {
            background: string;
        };
    }[];
    Input: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "softenBorder2";
    };
    TextArea: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette;
        overrideStrategy?: "shift" | "swap";
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask>;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask>;
        strength?: number;
        max?: number;
        min?: number;
        parentName?: string;
        mask: "softenBorder2";
    };
};
//# sourceMappingURL=componentThemeDefinitions.d.ts.map