export declare const templates: {
    base: {
        background: number;
        backgroundHover: number;
        backgroundPress: number;
        backgroundFocus: number;
        backgroundStrong: number;
        backgroundTransparent: number;
        color: number;
        colorHover: number;
        colorPress: number;
        colorFocus: number;
        colorTransparent: number;
        borderColor: number;
        borderColorHover: number;
        borderColorFocus: number;
        borderColorPress: number;
        placeholderColor: number;
        color1: number;
        color2: number;
        color3: number;
        color4: number;
        color5: number;
        color6: number;
        color7: number;
        color8: number;
        color9: number;
        color10: number;
        color11: number;
        color12: number;
    };
    colorLight: {
        borderColor: number;
        borderColorHover: number;
        borderColorFocus: number;
        borderColorPress: number;
        background: number;
        backgroundHover: number;
        backgroundPress: number;
        backgroundFocus: number;
        backgroundStrong: number;
        backgroundTransparent: number;
        color: number;
        colorHover: number;
        colorPress: number;
        colorFocus: number;
        colorTransparent: number;
        placeholderColor: number;
        color1: number;
        color2: number;
        color3: number;
        color4: number;
        color5: number;
        color6: number;
        color7: number;
        color8: number;
        color9: number;
        color10: number;
        color11: number;
        color12: number;
    };
};
export declare const maskOptions: {
    component: {
        override: {
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette | undefined;
        overrideStrategy?: "shift" | "swap" | undefined;
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        strength?: number | undefined;
        max?: number | undefined;
        min?: number | undefined;
        parentName?: string | undefined;
    };
    alt: {
        palette?: import("@tamagui/create-theme").CreateThemePalette | undefined;
        override?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        overrideStrategy?: "shift" | "swap" | undefined;
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        skip?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        strength?: number | undefined;
        max?: number | undefined;
        min?: number | undefined;
        parentName?: string | undefined;
    };
    button: {
        override: {
            borderColor: string;
            borderColorHover: string;
            color: number;
            colorHover: number;
            colorFocus: number;
            colorPress: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        skip: {
            color1: number;
            color2: number;
            color3: number;
            color4: number;
            color5: number;
            color6: number;
            color7: number;
            color8: number;
            color9: number;
            color10: number;
            color11: number;
            color12: number;
            shadowColor: number;
            shadowColorHover: number;
            shadowColorPress: number;
            shadowColorFocus: number;
        };
        palette?: import("@tamagui/create-theme").CreateThemePalette | undefined;
        overrideStrategy?: "shift" | "swap" | undefined;
        overrideSwap?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        overrideShift?: Partial<import("@tamagui/create-theme").ThemeMask> | undefined;
        strength?: number | undefined;
        max?: number | undefined;
        min?: number | undefined;
        parentName?: string | undefined;
    };
};
//# sourceMappingURL=templates.d.ts.map