// @generated by @tamagui/style-grammar's scripts/generateRustGrammar.ts.
// Do not edit: run `bun scripts/generateRustGrammar.ts` in that package.
//
// These are the grammar's own tables, not a Rust reading of them. The crate is
// an editor transport for the flat value grammar and never a second owner of
// what a modifier means.

/// the core interaction and lifecycle modifiers, in grammar order
pub const CORE_STATE_MODIFIERS: &[&str] = &["hover", "press", "focus", "focus-visible", "focus-within", "disabled", "enter", "exit"];

/// the component-tier state words the behavior packages expose as DOM
/// attributes, which style through an attribute selector rather than a pseudo
pub const COMPONENT_STATE_MODIFIERS: &[&str] = &["open", "checked", "highlighted", "selected", "invalid"];

/// every alternate spelling and the modifier it means
pub const MODIFIER_ALIASES: &[(&str, &str)] = &[("active", "press"), ("pressed", "press"), ("starting", "enter"), ("ending", "exit")];

/// every built-in state spelling: core, aliases, component tier
pub const STATE_MODIFIERS: &[&str] = &["hover", "press", "focus", "focus-visible", "focus-within", "disabled", "enter", "exit", "active", "pressed", "starting", "ending", "open", "checked", "highlighted", "selected", "invalid"];

pub const PLATFORM_MODIFIERS: &[&str] = &["web", "native", "android", "ios", "tv", "androidtv", "tvos"];

/// `group-hover` targets the nearest unnamed group, `group-hover/card` a named one
pub const GROUP_PREFIX: &str = "group-";

/// `@sm` targets the nearest container, `@sm/card` a named one, and no
/// configured name may take the prefix
pub const CONTAINER_PREFIX: char = '@';

/// how many distinct non-platform conditions one clause may encode
pub const MAX_NON_PLATFORM_DEPTH: usize = 5;
