export { shorthands } from '@tamagui/shorthands/v5';
export { createThemes } from '@tamagui/theme-builder';
export { themes, tokens, createV5Theme } from '@tamagui/themes/v5';
export { createSystemFont, fonts } from './v5-fonts';
export { breakpoints, media, mediaQueryDefaultActive } from './v5-media';
export declare const selectionStyles: (theme: any) => {
    backgroundColor: any;
    color: any;
} | null;
export declare const settings: {
    mediaQueryDefaultActive: {
        pointerTouch: boolean;
        heightXXXS: boolean;
        heightXXS: boolean;
        heightXS: boolean;
        heightSM: boolean;
        heightMD: boolean;
        heightLG: boolean;
        maxXXXS: boolean;
        maxXXS: boolean;
        maxXS: boolean;
        maxSM: boolean;
        maxMD: boolean;
        maxLG: boolean;
        maxXL: boolean;
        maxXXL: boolean;
        xxxs: boolean;
        xxs: boolean;
        xs: boolean;
        sm: boolean;
        md: boolean;
        lg: boolean;
        xl: boolean;
        xxl: boolean;
    };
    defaultFont: string;
    fastSchemeChange: true;
    shouldAddPrefersColorThemes: true;
    allowedStyleValues: "somewhat-strict-web";
    addThemeClassName: "html";
    onlyAllowShorthands: true;
    styleCompat: "react-native";
};
export declare const defaultConfigBase: {
    media: {
        readonly pointerTouch: {
            readonly pointer: "coarse";
        };
        readonly heightXXXS: {
            readonly minHeight: number;
        };
        readonly heightXXS: {
            readonly minHeight: number;
        };
        readonly heightXS: {
            readonly minHeight: number;
        };
        readonly heightSM: {
            readonly minHeight: number;
        };
        readonly heightMD: {
            readonly minHeight: number;
        };
        readonly heightLG: {
            readonly minHeight: number;
        };
        readonly maxXXXS: {
            readonly maxWidth: number;
        };
        readonly maxXXS: {
            readonly maxWidth: number;
        };
        readonly maxXS: {
            readonly maxWidth: number;
        };
        readonly maxSM: {
            readonly maxWidth: number;
        };
        readonly maxMD: {
            readonly maxWidth: number;
        };
        readonly maxLG: {
            readonly maxWidth: number;
        };
        readonly maxXL: {
            readonly maxWidth: number;
        };
        readonly maxXXL: {
            readonly maxWidth: number;
        };
        readonly xxxs: {
            readonly minWidth: number;
        };
        readonly xxs: {
            readonly minWidth: number;
        };
        readonly xs: {
            readonly minWidth: number;
        };
        readonly sm: {
            readonly minWidth: number;
        };
        readonly md: {
            readonly minWidth: number;
        };
        readonly lg: {
            readonly minWidth: number;
        };
        readonly xl: {
            readonly minWidth: number;
        };
        readonly xxl: {
            readonly minWidth: number;
        };
    };
    shorthands: {
        text: "textAlign";
        b: "bottom";
        bg: "backgroundColor";
        content: "alignContent";
        grow: "flexGrow";
        items: "alignItems";
        justify: "justifyContent";
        l: "left";
        m: "margin";
        maxH: "maxHeight";
        maxW: "maxWidth";
        mb: "marginBottom";
        minH: "minHeight";
        minW: "minWidth";
        ml: "marginLeft";
        mr: "marginRight";
        mt: "marginTop";
        mx: "marginHorizontal";
        my: "marginVertical";
        p: "padding";
        pb: "paddingBottom";
        pl: "paddingLeft";
        pr: "paddingRight";
        pt: "paddingTop";
        px: "paddingHorizontal";
        py: "paddingVertical";
        r: "right";
        rounded: "borderRadius";
        select: "userSelect";
        self: "alignSelf";
        shrink: "flexShrink";
        t: "top";
        z: "zIndex";
    };
    themes: Record<"light" | "dark" | "light_yellow" | "light_green" | "light_blue" | "light_red" | "dark_yellow" | "dark_green" | "dark_blue" | "dark_red" | "light_alt1" | "light_alt2" | "dark_alt1" | "dark_alt2" | "light_yellow_alt1" | "light_yellow_alt2" | "light_green_alt1" | "light_green_alt2" | "light_blue_alt1" | "light_blue_alt2" | "light_red_alt1" | "light_red_alt2" | "dark_yellow_alt1" | "dark_yellow_alt2" | "dark_green_alt1" | "dark_green_alt2" | "dark_blue_alt1" | "dark_blue_alt2" | "dark_red_alt1" | "dark_red_alt2" | "light_gray" | "dark_gray" | "light_gray_alt1" | "light_gray_alt2" | "dark_gray_alt1" | "dark_gray_alt2" | "light_surface1" | "light_surface2" | "light_surface3" | "dark_surface1" | "dark_surface2" | "dark_surface3" | "light_blue_surface1" | "light_blue_surface2" | "light_blue_surface3" | "light_gray_surface1" | "light_gray_surface2" | "light_gray_surface3" | "light_green_surface1" | "light_green_surface2" | "light_green_surface3" | "light_red_surface1" | "light_red_surface2" | "light_red_surface3" | "light_yellow_surface1" | "light_yellow_surface2" | "light_yellow_surface3" | "dark_blue_surface1" | "dark_blue_surface2" | "dark_blue_surface3" | "dark_gray_surface1" | "dark_gray_surface2" | "dark_gray_surface3" | "dark_green_surface1" | "dark_green_surface2" | "dark_green_surface3" | "dark_red_surface1" | "dark_red_surface2" | "dark_red_surface3" | "dark_yellow_surface1" | "dark_yellow_surface2" | "dark_yellow_surface3" | "light_black" | "light_white" | "dark_black" | "dark_white" | "light_accent" | "dark_accent" | "light_black_accent" | "light_white_accent" | "light_blue_accent" | "light_red_accent" | "light_yellow_accent" | "light_green_accent" | "dark_black_accent" | "dark_white_accent" | "dark_blue_accent" | "dark_red_accent" | "dark_yellow_accent" | "dark_green_accent" | "light_neutral" | "dark_neutral" | "light_white_alt1" | "dark_white_alt1" | "light_white_alt2" | "dark_white_alt2" | "light_white_surface1" | "light_white_surface2" | "light_white_surface3" | "light_black_alt1" | "dark_black_alt1" | "light_black_alt2" | "dark_black_alt2" | "dark_black_surface1" | "dark_black_surface2" | "dark_black_surface3" | "light_black_surface1" | "light_black_surface2" | "light_black_surface3" | "light_gray_accent" | "light_neutral_accent" | "light_neutral_alt1" | "dark_neutral_alt1" | "light_neutral_alt2" | "dark_neutral_alt2" | "light_neutral_surface1" | "light_neutral_surface2" | "light_neutral_surface3" | "dark_white_surface1" | "dark_white_surface2" | "dark_white_surface3" | "dark_gray_accent" | "dark_neutral_accent" | "dark_neutral_surface1" | "dark_neutral_surface2" | "dark_neutral_surface3", {
        accentBackground: string;
        accentColor: string;
        background0: string;
        background02: string;
        background04: string;
        background06: string;
        background08: string;
        color1: string;
        color2: string;
        color3: string;
        color4: string;
        color5: string;
        color6: string;
        color7: string;
        color8: string;
        color9: string;
        color10: string;
        color11: string;
        color12: string;
        color0: string;
        color02: string;
        color04: string;
        color06: string;
        color08: string;
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        backgroundActive: string;
        borderColor: string;
        borderColorHover: string;
        borderColorPress: string;
        borderColorFocus: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorFocus: string;
        placeholderColor: string;
        outlineColor: string;
        colorTransparent: string;
        black1: string;
        black2: string;
        black3: string;
        black4: string;
        black5: string;
        black6: string;
        black7: string;
        black8: string;
        black9: string;
        black10: string;
        black11: string;
        black12: string;
        white1: string;
        white2: string;
        white3: string;
        white4: string;
        white5: string;
        white6: string;
        white7: string;
        white8: string;
        white9: string;
        white10: string;
        white11: string;
        white12: string;
        white: string;
        white0: string;
        white02: string;
        white04: string;
        white06: string;
        white08: string;
        black: string;
        black0: string;
        black02: string;
        black04: string;
        black06: string;
        black08: string;
        shadow1: string;
        shadow2: string;
        shadow3: string;
        shadow4: string;
        shadow5: string;
        shadow6: string;
        shadowColor: string;
        gray1: string;
        gray2: string;
        gray3: string;
        gray4: string;
        gray5: string;
        gray6: string;
        gray7: string;
        gray8: string;
        gray9: string;
        gray10: string;
        gray11: string;
        gray12: string;
        blue1: string;
        blue2: string;
        blue3: string;
        blue4: string;
        blue5: string;
        blue6: string;
        blue7: string;
        blue8: string;
        blue9: string;
        blue10: string;
        blue11: string;
        blue12: string;
        red1: string;
        red2: string;
        red3: string;
        red4: string;
        red5: string;
        red6: string;
        red7: string;
        red8: string;
        red9: string;
        red10: string;
        red11: string;
        red12: string;
        yellow1: string;
        yellow2: string;
        yellow3: string;
        yellow4: string;
        yellow5: string;
        yellow6: string;
        yellow7: string;
        yellow8: string;
        yellow9: string;
        yellow10: string;
        yellow11: string;
        yellow12: string;
        green1: string;
        green2: string;
        green3: string;
        green4: string;
        green5: string;
        green6: string;
        green7: string;
        green8: string;
        green9: string;
        green10: string;
        green11: string;
        green12: string;
        neutral1: string;
        neutral2: string;
        neutral3: string;
        neutral4: string;
        neutral5: string;
        neutral6: string;
        neutral7: string;
        neutral8: string;
        neutral9: string;
        neutral10: string;
        neutral11: string;
        neutral12: string;
        accent1: string;
        accent2: string;
        accent3: string;
        accent4: string;
        accent5: string;
        accent6: string;
        accent7: string;
        accent8: string;
        accent9: string;
        accent10: string;
        accent11: string;
        accent12: string;
        color0pt5: string;
        color1pt5: string;
        color2pt5: string;
        color01: string;
        color0075: string;
        color005: string;
        color0025: string;
        color002: string;
        color001: string;
        background01: string;
        background0075: string;
        background005: string;
        background0025: string;
        background002: string;
        background001: string;
    }>;
    tokens: {
        readonly radius: {
            0: number;
            1: number;
            2: number;
            3: number;
            4: number;
            true: number;
            5: number;
            6: number;
            7: number;
            8: number;
            9: number;
            10: number;
            11: number;
            12: number;
        };
        readonly zIndex: {
            0: number;
            1: number;
            2: number;
            3: number;
            4: number;
            5: number;
        };
        readonly space: {
            0: number;
            0.25: number;
            0.5: number;
            0.75: number;
            1: number;
            1.5: number;
            2: number;
            2.5: number;
            3: number;
            3.5: number;
            4: number;
            true: number;
            4.5: number;
            5: number;
            6: number;
            7: number;
            8: number;
            9: number;
            10: number;
            11: number;
            12: number;
            13: number;
            14: number;
            15: number;
            16: number;
            17: number;
            18: number;
            19: number;
            20: number;
            [-0.25]: number;
            [-0.5]: number;
            [-0.75]: number;
            [-1]: number;
            [-1.5]: number;
            [-2]: number;
            [-2.5]: number;
            [-3]: number;
            [-3.5]: number;
            [-4]: number;
            "-true": number;
            [-4.5]: number;
            [-5]: number;
            [-6]: number;
            [-7]: number;
            [-8]: number;
            [-9]: number;
            [-10]: number;
            [-11]: number;
            [-12]: number;
            [-13]: number;
            [-14]: number;
            [-15]: number;
            [-16]: number;
            [-17]: number;
            [-18]: number;
            [-19]: number;
            [-20]: number;
        };
        readonly size: {
            $0: number;
            "$0.25": number;
            "$0.5": number;
            "$0.75": number;
            $1: number;
            "$1.5": number;
            $2: number;
            "$2.5": number;
            $3: number;
            "$3.5": number;
            $4: number;
            $true: number;
            "$4.5": number;
            $5: number;
            $6: number;
            $7: number;
            $8: number;
            $9: number;
            $10: number;
            $11: number;
            $12: number;
            $13: number;
            $14: number;
            $15: number;
            $16: number;
            $17: number;
            $18: number;
            $19: number;
            $20: number;
        };
    };
    fonts: {
        body: import("@tamagui/web").FillInFont<import("@tamagui/web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 12 | 16 | 11 | 14 | 4 | 7 | 8 | 13 | "true">;
        heading: import("@tamagui/web").FillInFont<import("@tamagui/web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 12 | 16 | 11 | 14 | 4 | 7 | 8 | 13 | "true">;
    };
    selectionStyles: (theme: any) => {
        backgroundColor: any;
        color: any;
    } | null;
    settings: {
        mediaQueryDefaultActive: {
            pointerTouch: boolean;
            heightXXXS: boolean;
            heightXXS: boolean;
            heightXS: boolean;
            heightSM: boolean;
            heightMD: boolean;
            heightLG: boolean;
            maxXXXS: boolean;
            maxXXS: boolean;
            maxXS: boolean;
            maxSM: boolean;
            maxMD: boolean;
            maxLG: boolean;
            maxXL: boolean;
            maxXXL: boolean;
            xxxs: boolean;
            xxs: boolean;
            xs: boolean;
            sm: boolean;
            md: boolean;
            lg: boolean;
            xl: boolean;
            xxl: boolean;
        };
        defaultFont: string;
        fastSchemeChange: true;
        shouldAddPrefersColorThemes: true;
        allowedStyleValues: "somewhat-strict-web";
        addThemeClassName: "html";
        onlyAllowShorthands: true;
        styleCompat: "react-native";
    };
};
//# sourceMappingURL=v5-base.d.ts.map