import { tailwindColors, themes, type Theme, type ThemeNames, type Themes } from '@tamagui/themes';
export * from './v6-base';
export { tailwindColors, themes };
export type { Theme as V6Theme, ThemeNames as V6ThemeNames, Themes as V6Themes };
/** the Tailwind colors pack: color tokens + themes generated from the same palette */
export declare const colors: {
    themes: Themes;
    colorTokens: {
        readonly white: string;
        readonly black: string;
        readonly 'slate-50': string;
        readonly 'slate-100': string;
        readonly 'slate-200': string;
        readonly 'slate-300': string;
        readonly 'slate-400': string;
        readonly 'slate-500': string;
        readonly 'slate-600': string;
        readonly 'slate-700': string;
        readonly 'slate-800': string;
        readonly 'slate-900': string;
        readonly 'slate-950': string;
        readonly 'gray-50': string;
        readonly 'gray-100': string;
        readonly 'gray-200': string;
        readonly 'gray-300': string;
        readonly 'gray-400': string;
        readonly 'gray-500': string;
        readonly 'gray-600': string;
        readonly 'gray-700': string;
        readonly 'gray-800': string;
        readonly 'gray-900': string;
        readonly 'gray-950': string;
        readonly 'zinc-50': string;
        readonly 'zinc-100': string;
        readonly 'zinc-200': string;
        readonly 'zinc-300': string;
        readonly 'zinc-400': string;
        readonly 'zinc-500': string;
        readonly 'zinc-600': string;
        readonly 'zinc-700': string;
        readonly 'zinc-800': string;
        readonly 'zinc-900': string;
        readonly 'zinc-950': string;
        readonly 'neutral-50': string;
        readonly 'neutral-100': string;
        readonly 'neutral-200': string;
        readonly 'neutral-300': string;
        readonly 'neutral-400': string;
        readonly 'neutral-500': string;
        readonly 'neutral-600': string;
        readonly 'neutral-700': string;
        readonly 'neutral-800': string;
        readonly 'neutral-900': string;
        readonly 'neutral-950': string;
        readonly 'stone-50': string;
        readonly 'stone-100': string;
        readonly 'stone-200': string;
        readonly 'stone-300': string;
        readonly 'stone-400': string;
        readonly 'stone-500': string;
        readonly 'stone-600': string;
        readonly 'stone-700': string;
        readonly 'stone-800': string;
        readonly 'stone-900': string;
        readonly 'stone-950': string;
        readonly 'mauve-50': string;
        readonly 'mauve-100': string;
        readonly 'mauve-200': string;
        readonly 'mauve-300': string;
        readonly 'mauve-400': string;
        readonly 'mauve-500': string;
        readonly 'mauve-600': string;
        readonly 'mauve-700': string;
        readonly 'mauve-800': string;
        readonly 'mauve-900': string;
        readonly 'mauve-950': string;
        readonly 'olive-50': string;
        readonly 'olive-100': string;
        readonly 'olive-200': string;
        readonly 'olive-300': string;
        readonly 'olive-400': string;
        readonly 'olive-500': string;
        readonly 'olive-600': string;
        readonly 'olive-700': string;
        readonly 'olive-800': string;
        readonly 'olive-900': string;
        readonly 'olive-950': string;
        readonly 'mist-50': string;
        readonly 'mist-100': string;
        readonly 'mist-200': string;
        readonly 'mist-300': string;
        readonly 'mist-400': string;
        readonly 'mist-500': string;
        readonly 'mist-600': string;
        readonly 'mist-700': string;
        readonly 'mist-800': string;
        readonly 'mist-900': string;
        readonly 'mist-950': string;
        readonly 'taupe-50': string;
        readonly 'taupe-100': string;
        readonly 'taupe-200': string;
        readonly 'taupe-300': string;
        readonly 'taupe-400': string;
        readonly 'taupe-500': string;
        readonly 'taupe-600': string;
        readonly 'taupe-700': string;
        readonly 'taupe-800': string;
        readonly 'taupe-900': string;
        readonly 'taupe-950': string;
        readonly 'red-50': string;
        readonly 'red-100': string;
        readonly 'red-200': string;
        readonly 'red-300': string;
        readonly 'red-400': string;
        readonly 'red-500': string;
        readonly 'red-600': string;
        readonly 'red-700': string;
        readonly 'red-800': string;
        readonly 'red-900': string;
        readonly 'red-950': string;
        readonly 'orange-50': string;
        readonly 'orange-100': string;
        readonly 'orange-200': string;
        readonly 'orange-300': string;
        readonly 'orange-400': string;
        readonly 'orange-500': string;
        readonly 'orange-600': string;
        readonly 'orange-700': string;
        readonly 'orange-800': string;
        readonly 'orange-900': string;
        readonly 'orange-950': string;
        readonly 'amber-50': string;
        readonly 'amber-100': string;
        readonly 'amber-200': string;
        readonly 'amber-300': string;
        readonly 'amber-400': string;
        readonly 'amber-500': string;
        readonly 'amber-600': string;
        readonly 'amber-700': string;
        readonly 'amber-800': string;
        readonly 'amber-900': string;
        readonly 'amber-950': string;
        readonly 'yellow-50': string;
        readonly 'yellow-100': string;
        readonly 'yellow-200': string;
        readonly 'yellow-300': string;
        readonly 'yellow-400': string;
        readonly 'yellow-500': string;
        readonly 'yellow-600': string;
        readonly 'yellow-700': string;
        readonly 'yellow-800': string;
        readonly 'yellow-900': string;
        readonly 'yellow-950': string;
        readonly 'lime-50': string;
        readonly 'lime-100': string;
        readonly 'lime-200': string;
        readonly 'lime-300': string;
        readonly 'lime-400': string;
        readonly 'lime-500': string;
        readonly 'lime-600': string;
        readonly 'lime-700': string;
        readonly 'lime-800': string;
        readonly 'lime-900': string;
        readonly 'lime-950': string;
        readonly 'green-50': string;
        readonly 'green-100': string;
        readonly 'green-200': string;
        readonly 'green-300': string;
        readonly 'green-400': string;
        readonly 'green-500': string;
        readonly 'green-600': string;
        readonly 'green-700': string;
        readonly 'green-800': string;
        readonly 'green-900': string;
        readonly 'green-950': string;
        readonly 'emerald-50': string;
        readonly 'emerald-100': string;
        readonly 'emerald-200': string;
        readonly 'emerald-300': string;
        readonly 'emerald-400': string;
        readonly 'emerald-500': string;
        readonly 'emerald-600': string;
        readonly 'emerald-700': string;
        readonly 'emerald-800': string;
        readonly 'emerald-900': string;
        readonly 'emerald-950': string;
        readonly 'teal-50': string;
        readonly 'teal-100': string;
        readonly 'teal-200': string;
        readonly 'teal-300': string;
        readonly 'teal-400': string;
        readonly 'teal-500': string;
        readonly 'teal-600': string;
        readonly 'teal-700': string;
        readonly 'teal-800': string;
        readonly 'teal-900': string;
        readonly 'teal-950': string;
        readonly 'cyan-50': string;
        readonly 'cyan-100': string;
        readonly 'cyan-200': string;
        readonly 'cyan-300': string;
        readonly 'cyan-400': string;
        readonly 'cyan-500': string;
        readonly 'cyan-600': string;
        readonly 'cyan-700': string;
        readonly 'cyan-800': string;
        readonly 'cyan-900': string;
        readonly 'cyan-950': string;
        readonly 'sky-50': string;
        readonly 'sky-100': string;
        readonly 'sky-200': string;
        readonly 'sky-300': string;
        readonly 'sky-400': string;
        readonly 'sky-500': string;
        readonly 'sky-600': string;
        readonly 'sky-700': string;
        readonly 'sky-800': string;
        readonly 'sky-900': string;
        readonly 'sky-950': string;
        readonly 'blue-50': string;
        readonly 'blue-100': string;
        readonly 'blue-200': string;
        readonly 'blue-300': string;
        readonly 'blue-400': string;
        readonly 'blue-500': string;
        readonly 'blue-600': string;
        readonly 'blue-700': string;
        readonly 'blue-800': string;
        readonly 'blue-900': string;
        readonly 'blue-950': string;
        readonly 'indigo-50': string;
        readonly 'indigo-100': string;
        readonly 'indigo-200': string;
        readonly 'indigo-300': string;
        readonly 'indigo-400': string;
        readonly 'indigo-500': string;
        readonly 'indigo-600': string;
        readonly 'indigo-700': string;
        readonly 'indigo-800': string;
        readonly 'indigo-900': string;
        readonly 'indigo-950': string;
        readonly 'violet-50': string;
        readonly 'violet-100': string;
        readonly 'violet-200': string;
        readonly 'violet-300': string;
        readonly 'violet-400': string;
        readonly 'violet-500': string;
        readonly 'violet-600': string;
        readonly 'violet-700': string;
        readonly 'violet-800': string;
        readonly 'violet-900': string;
        readonly 'violet-950': string;
        readonly 'purple-50': string;
        readonly 'purple-100': string;
        readonly 'purple-200': string;
        readonly 'purple-300': string;
        readonly 'purple-400': string;
        readonly 'purple-500': string;
        readonly 'purple-600': string;
        readonly 'purple-700': string;
        readonly 'purple-800': string;
        readonly 'purple-900': string;
        readonly 'purple-950': string;
        readonly 'fuchsia-50': string;
        readonly 'fuchsia-100': string;
        readonly 'fuchsia-200': string;
        readonly 'fuchsia-300': string;
        readonly 'fuchsia-400': string;
        readonly 'fuchsia-500': string;
        readonly 'fuchsia-600': string;
        readonly 'fuchsia-700': string;
        readonly 'fuchsia-800': string;
        readonly 'fuchsia-900': string;
        readonly 'fuchsia-950': string;
        readonly 'pink-50': string;
        readonly 'pink-100': string;
        readonly 'pink-200': string;
        readonly 'pink-300': string;
        readonly 'pink-400': string;
        readonly 'pink-500': string;
        readonly 'pink-600': string;
        readonly 'pink-700': string;
        readonly 'pink-800': string;
        readonly 'pink-900': string;
        readonly 'pink-950': string;
        readonly 'rose-50': string;
        readonly 'rose-100': string;
        readonly 'rose-200': string;
        readonly 'rose-300': string;
        readonly 'rose-400': string;
        readonly 'rose-500': string;
        readonly 'rose-600': string;
        readonly 'rose-700': string;
        readonly 'rose-800': string;
        readonly 'rose-900': string;
        readonly 'rose-950': string;
        readonly 'brand-50': string;
        readonly 'brand-100': string;
        readonly 'brand-200': string;
        readonly 'brand-300': string;
        readonly 'brand-400': string;
        readonly 'brand-500': string;
        readonly 'brand-600': string;
        readonly 'brand-700': string;
        readonly 'brand-800': string;
        readonly 'brand-900': string;
        readonly 'brand-950': string;
        readonly 'shadow-1': 'rgba(0, 0, 0, 0.05)';
        readonly 'shadow-2': 'rgba(0, 0, 0, 0.08)';
        readonly 'shadow-3': 'rgba(0, 0, 0, 0.12)';
        readonly 'shadow-4': 'rgba(0, 0, 0, 0.16)';
        readonly 'shadow-5': 'rgba(0, 0, 0, 0.2)';
        readonly 'shadow-6': 'rgba(0, 0, 0, 0.25)';
        readonly 'shadow-7': 'rgba(0, 0, 0, 0.3)';
    };
};
export declare const tokens: {
    readonly space: {
        readonly '0': 0;
        readonly '1': 4;
        readonly '2': 8;
        readonly '3': 12;
        readonly '4': 16;
        readonly '5': 20;
        readonly '6': 24;
        readonly '7': 28;
        readonly '8': 32;
        readonly '9': 36;
        readonly '10': 40;
        readonly '11': 44;
        readonly '12': 48;
        readonly '14': 56;
        readonly '16': 64;
        readonly '20': 80;
        readonly '24': 96;
        readonly '28': 112;
        readonly '32': 128;
        readonly '36': 144;
        readonly '40': 160;
        readonly '44': 176;
        readonly '48': 192;
        readonly '52': 208;
        readonly '56': 224;
        readonly '60': 240;
        readonly '64': 256;
        readonly '72': 288;
        readonly '80': 320;
        readonly '96': 384;
        readonly px: 1;
        readonly '0-5': 2;
        readonly '1-5': 6;
        readonly '2-5': 10;
        readonly '3-5': 14;
        readonly '-px': -1;
        readonly '-0-5': -2;
        readonly '-1': -4;
        readonly '-1-5': -6;
        readonly '-2': -8;
        readonly '-2-5': -10;
        readonly '-3': -12;
        readonly '-3-5': -14;
        readonly '-4': -16;
        readonly '-5': -20;
        readonly '-6': -24;
        readonly '-7': -28;
        readonly '-8': -32;
        readonly '-9': -36;
        readonly '-10': -40;
        readonly '-11': -44;
        readonly '-12': -48;
        readonly '-14': -56;
        readonly '-16': -64;
        readonly '-20': -80;
        readonly '-24': -96;
        readonly '-28': -112;
        readonly '-32': -128;
        readonly '-36': -144;
        readonly '-40': -160;
        readonly '-44': -176;
        readonly '-48': -192;
        readonly '-52': -208;
        readonly '-56': -224;
        readonly '-60': -240;
        readonly '-64': -256;
        readonly '-72': -288;
        readonly '-80': -320;
        readonly '-96': -384;
    };
    readonly size: {
        readonly '0': 0;
        readonly '1': 4;
        readonly '2': 8;
        readonly '3': 12;
        readonly '4': 16;
        readonly '5': 20;
        readonly '6': 24;
        readonly '7': 28;
        readonly '8': 32;
        readonly '9': 36;
        readonly '10': 40;
        readonly '11': 44;
        readonly '12': 48;
        readonly '14': 56;
        readonly '16': 64;
        readonly '20': 80;
        readonly '24': 96;
        readonly '28': 112;
        readonly '32': 128;
        readonly '36': 144;
        readonly '40': 160;
        readonly '44': 176;
        readonly '48': 192;
        readonly '52': 208;
        readonly '56': 224;
        readonly '60': 240;
        readonly '64': 256;
        readonly '72': 288;
        readonly '80': 320;
        readonly '96': 384;
        readonly px: 1;
        readonly '0-5': 2;
        readonly '1-5': 6;
        readonly '2-5': 10;
        readonly '3-5': 14;
    };
    readonly radius: {
        readonly xs: 2;
        readonly sm: 4;
        readonly md: 6;
        readonly lg: 8;
        readonly xl: 12;
        readonly '2xl': 16;
        readonly '3xl': 24;
        readonly '4xl': 32;
        readonly full: 9999;
        readonly 0: 0;
        readonly 1: 3;
        readonly 2: 5;
        readonly 3: 7;
        readonly 4: 9;
        readonly 5: 10;
        readonly 6: 16;
        readonly 7: 19;
        readonly 8: 22;
        readonly 9: 26;
        readonly 10: 34;
        readonly 11: 42;
        readonly 12: 50;
    };
    readonly color: {
        readonly white: string;
        readonly black: string;
        readonly 'slate-50': string;
        readonly 'slate-100': string;
        readonly 'slate-200': string;
        readonly 'slate-300': string;
        readonly 'slate-400': string;
        readonly 'slate-500': string;
        readonly 'slate-600': string;
        readonly 'slate-700': string;
        readonly 'slate-800': string;
        readonly 'slate-900': string;
        readonly 'slate-950': string;
        readonly 'gray-50': string;
        readonly 'gray-100': string;
        readonly 'gray-200': string;
        readonly 'gray-300': string;
        readonly 'gray-400': string;
        readonly 'gray-500': string;
        readonly 'gray-600': string;
        readonly 'gray-700': string;
        readonly 'gray-800': string;
        readonly 'gray-900': string;
        readonly 'gray-950': string;
        readonly 'zinc-50': string;
        readonly 'zinc-100': string;
        readonly 'zinc-200': string;
        readonly 'zinc-300': string;
        readonly 'zinc-400': string;
        readonly 'zinc-500': string;
        readonly 'zinc-600': string;
        readonly 'zinc-700': string;
        readonly 'zinc-800': string;
        readonly 'zinc-900': string;
        readonly 'zinc-950': string;
        readonly 'neutral-50': string;
        readonly 'neutral-100': string;
        readonly 'neutral-200': string;
        readonly 'neutral-300': string;
        readonly 'neutral-400': string;
        readonly 'neutral-500': string;
        readonly 'neutral-600': string;
        readonly 'neutral-700': string;
        readonly 'neutral-800': string;
        readonly 'neutral-900': string;
        readonly 'neutral-950': string;
        readonly 'stone-50': string;
        readonly 'stone-100': string;
        readonly 'stone-200': string;
        readonly 'stone-300': string;
        readonly 'stone-400': string;
        readonly 'stone-500': string;
        readonly 'stone-600': string;
        readonly 'stone-700': string;
        readonly 'stone-800': string;
        readonly 'stone-900': string;
        readonly 'stone-950': string;
        readonly 'mauve-50': string;
        readonly 'mauve-100': string;
        readonly 'mauve-200': string;
        readonly 'mauve-300': string;
        readonly 'mauve-400': string;
        readonly 'mauve-500': string;
        readonly 'mauve-600': string;
        readonly 'mauve-700': string;
        readonly 'mauve-800': string;
        readonly 'mauve-900': string;
        readonly 'mauve-950': string;
        readonly 'olive-50': string;
        readonly 'olive-100': string;
        readonly 'olive-200': string;
        readonly 'olive-300': string;
        readonly 'olive-400': string;
        readonly 'olive-500': string;
        readonly 'olive-600': string;
        readonly 'olive-700': string;
        readonly 'olive-800': string;
        readonly 'olive-900': string;
        readonly 'olive-950': string;
        readonly 'mist-50': string;
        readonly 'mist-100': string;
        readonly 'mist-200': string;
        readonly 'mist-300': string;
        readonly 'mist-400': string;
        readonly 'mist-500': string;
        readonly 'mist-600': string;
        readonly 'mist-700': string;
        readonly 'mist-800': string;
        readonly 'mist-900': string;
        readonly 'mist-950': string;
        readonly 'taupe-50': string;
        readonly 'taupe-100': string;
        readonly 'taupe-200': string;
        readonly 'taupe-300': string;
        readonly 'taupe-400': string;
        readonly 'taupe-500': string;
        readonly 'taupe-600': string;
        readonly 'taupe-700': string;
        readonly 'taupe-800': string;
        readonly 'taupe-900': string;
        readonly 'taupe-950': string;
        readonly 'red-50': string;
        readonly 'red-100': string;
        readonly 'red-200': string;
        readonly 'red-300': string;
        readonly 'red-400': string;
        readonly 'red-500': string;
        readonly 'red-600': string;
        readonly 'red-700': string;
        readonly 'red-800': string;
        readonly 'red-900': string;
        readonly 'red-950': string;
        readonly 'orange-50': string;
        readonly 'orange-100': string;
        readonly 'orange-200': string;
        readonly 'orange-300': string;
        readonly 'orange-400': string;
        readonly 'orange-500': string;
        readonly 'orange-600': string;
        readonly 'orange-700': string;
        readonly 'orange-800': string;
        readonly 'orange-900': string;
        readonly 'orange-950': string;
        readonly 'amber-50': string;
        readonly 'amber-100': string;
        readonly 'amber-200': string;
        readonly 'amber-300': string;
        readonly 'amber-400': string;
        readonly 'amber-500': string;
        readonly 'amber-600': string;
        readonly 'amber-700': string;
        readonly 'amber-800': string;
        readonly 'amber-900': string;
        readonly 'amber-950': string;
        readonly 'yellow-50': string;
        readonly 'yellow-100': string;
        readonly 'yellow-200': string;
        readonly 'yellow-300': string;
        readonly 'yellow-400': string;
        readonly 'yellow-500': string;
        readonly 'yellow-600': string;
        readonly 'yellow-700': string;
        readonly 'yellow-800': string;
        readonly 'yellow-900': string;
        readonly 'yellow-950': string;
        readonly 'lime-50': string;
        readonly 'lime-100': string;
        readonly 'lime-200': string;
        readonly 'lime-300': string;
        readonly 'lime-400': string;
        readonly 'lime-500': string;
        readonly 'lime-600': string;
        readonly 'lime-700': string;
        readonly 'lime-800': string;
        readonly 'lime-900': string;
        readonly 'lime-950': string;
        readonly 'green-50': string;
        readonly 'green-100': string;
        readonly 'green-200': string;
        readonly 'green-300': string;
        readonly 'green-400': string;
        readonly 'green-500': string;
        readonly 'green-600': string;
        readonly 'green-700': string;
        readonly 'green-800': string;
        readonly 'green-900': string;
        readonly 'green-950': string;
        readonly 'emerald-50': string;
        readonly 'emerald-100': string;
        readonly 'emerald-200': string;
        readonly 'emerald-300': string;
        readonly 'emerald-400': string;
        readonly 'emerald-500': string;
        readonly 'emerald-600': string;
        readonly 'emerald-700': string;
        readonly 'emerald-800': string;
        readonly 'emerald-900': string;
        readonly 'emerald-950': string;
        readonly 'teal-50': string;
        readonly 'teal-100': string;
        readonly 'teal-200': string;
        readonly 'teal-300': string;
        readonly 'teal-400': string;
        readonly 'teal-500': string;
        readonly 'teal-600': string;
        readonly 'teal-700': string;
        readonly 'teal-800': string;
        readonly 'teal-900': string;
        readonly 'teal-950': string;
        readonly 'cyan-50': string;
        readonly 'cyan-100': string;
        readonly 'cyan-200': string;
        readonly 'cyan-300': string;
        readonly 'cyan-400': string;
        readonly 'cyan-500': string;
        readonly 'cyan-600': string;
        readonly 'cyan-700': string;
        readonly 'cyan-800': string;
        readonly 'cyan-900': string;
        readonly 'cyan-950': string;
        readonly 'sky-50': string;
        readonly 'sky-100': string;
        readonly 'sky-200': string;
        readonly 'sky-300': string;
        readonly 'sky-400': string;
        readonly 'sky-500': string;
        readonly 'sky-600': string;
        readonly 'sky-700': string;
        readonly 'sky-800': string;
        readonly 'sky-900': string;
        readonly 'sky-950': string;
        readonly 'blue-50': string;
        readonly 'blue-100': string;
        readonly 'blue-200': string;
        readonly 'blue-300': string;
        readonly 'blue-400': string;
        readonly 'blue-500': string;
        readonly 'blue-600': string;
        readonly 'blue-700': string;
        readonly 'blue-800': string;
        readonly 'blue-900': string;
        readonly 'blue-950': string;
        readonly 'indigo-50': string;
        readonly 'indigo-100': string;
        readonly 'indigo-200': string;
        readonly 'indigo-300': string;
        readonly 'indigo-400': string;
        readonly 'indigo-500': string;
        readonly 'indigo-600': string;
        readonly 'indigo-700': string;
        readonly 'indigo-800': string;
        readonly 'indigo-900': string;
        readonly 'indigo-950': string;
        readonly 'violet-50': string;
        readonly 'violet-100': string;
        readonly 'violet-200': string;
        readonly 'violet-300': string;
        readonly 'violet-400': string;
        readonly 'violet-500': string;
        readonly 'violet-600': string;
        readonly 'violet-700': string;
        readonly 'violet-800': string;
        readonly 'violet-900': string;
        readonly 'violet-950': string;
        readonly 'purple-50': string;
        readonly 'purple-100': string;
        readonly 'purple-200': string;
        readonly 'purple-300': string;
        readonly 'purple-400': string;
        readonly 'purple-500': string;
        readonly 'purple-600': string;
        readonly 'purple-700': string;
        readonly 'purple-800': string;
        readonly 'purple-900': string;
        readonly 'purple-950': string;
        readonly 'fuchsia-50': string;
        readonly 'fuchsia-100': string;
        readonly 'fuchsia-200': string;
        readonly 'fuchsia-300': string;
        readonly 'fuchsia-400': string;
        readonly 'fuchsia-500': string;
        readonly 'fuchsia-600': string;
        readonly 'fuchsia-700': string;
        readonly 'fuchsia-800': string;
        readonly 'fuchsia-900': string;
        readonly 'fuchsia-950': string;
        readonly 'pink-50': string;
        readonly 'pink-100': string;
        readonly 'pink-200': string;
        readonly 'pink-300': string;
        readonly 'pink-400': string;
        readonly 'pink-500': string;
        readonly 'pink-600': string;
        readonly 'pink-700': string;
        readonly 'pink-800': string;
        readonly 'pink-900': string;
        readonly 'pink-950': string;
        readonly 'rose-50': string;
        readonly 'rose-100': string;
        readonly 'rose-200': string;
        readonly 'rose-300': string;
        readonly 'rose-400': string;
        readonly 'rose-500': string;
        readonly 'rose-600': string;
        readonly 'rose-700': string;
        readonly 'rose-800': string;
        readonly 'rose-900': string;
        readonly 'rose-950': string;
        readonly 'brand-50': string;
        readonly 'brand-100': string;
        readonly 'brand-200': string;
        readonly 'brand-300': string;
        readonly 'brand-400': string;
        readonly 'brand-500': string;
        readonly 'brand-600': string;
        readonly 'brand-700': string;
        readonly 'brand-800': string;
        readonly 'brand-900': string;
        readonly 'brand-950': string;
        readonly 'shadow-1': 'rgba(0, 0, 0, 0.05)';
        readonly 'shadow-2': 'rgba(0, 0, 0, 0.08)';
        readonly 'shadow-3': 'rgba(0, 0, 0, 0.12)';
        readonly 'shadow-4': 'rgba(0, 0, 0, 0.16)';
        readonly 'shadow-5': 'rgba(0, 0, 0, 0.2)';
        readonly 'shadow-6': 'rgba(0, 0, 0, 0.25)';
        readonly 'shadow-7': 'rgba(0, 0, 0, 0.3)';
    };
};
export declare const defaultConfig: {
    media: {
        readonly touchable: {
            pointer: string;
        };
        readonly hoverable: {
            hover: string;
        };
        readonly 'max-xxl': {
            readonly maxWidth: number;
        };
        readonly 'max-xl': {
            readonly maxWidth: number;
        };
        readonly 'max-lg': {
            readonly maxWidth: number;
        };
        readonly 'max-md': {
            readonly maxWidth: number;
        };
        readonly 'max-sm': {
            readonly maxWidth: number;
        };
        readonly 'max-xs': {
            readonly maxWidth: number;
        };
        readonly 'max-xxs': {
            readonly maxWidth: number;
        };
        readonly 'max-xxxs': {
            readonly maxWidth: number;
        };
        readonly 'max-200': {
            readonly maxWidth: number;
        };
        readonly 'max-100': {
            readonly maxWidth: number;
        };
        readonly xxxs: {
            readonly minWidth: number;
        };
        readonly xxs: {
            readonly minWidth: number;
        };
        readonly xs: {
            readonly minWidth: number;
        };
        readonly sm: {
            readonly minWidth: number;
        };
        readonly md: {
            readonly minWidth: number;
        };
        readonly lg: {
            readonly minWidth: number;
        };
        readonly xl: {
            readonly minWidth: number;
        };
        readonly xxl: {
            readonly minWidth: number;
        };
        readonly 'max-height-lg': {
            readonly maxHeight: number;
        };
        readonly 'max-height-md': {
            readonly maxHeight: number;
        };
        readonly 'max-height-sm': {
            readonly maxHeight: number;
        };
        readonly 'max-height-xs': {
            readonly maxHeight: number;
        };
        readonly 'max-height-xxs': {
            readonly maxHeight: number;
        };
        readonly 'max-height-xxxs': {
            readonly maxHeight: number;
        };
        readonly 'max-height-200': {
            readonly maxHeight: number;
        };
        readonly 'max-height-100': {
            readonly maxHeight: number;
        };
        readonly 'height-sm': {
            readonly minHeight: number;
        };
        readonly 'height-md': {
            readonly minHeight: number;
        };
        readonly 'height-lg': {
            readonly minHeight: number;
        };
    };
    shorthands: {
        text: "textAlign";
        b: "bottom";
        bg: "background";
        content: "alignContent";
        grow: "flexGrow";
        h: "height";
        items: "alignItems";
        justify: "justifyContent";
        l: "left";
        m: "margin";
        maxH: "maxHeight";
        maxW: "maxWidth";
        mb: "marginBottom";
        minH: "minHeight";
        minW: "minWidth";
        ml: "marginLeft";
        mr: "marginRight";
        mt: "marginTop";
        mx: "marginHorizontal";
        my: "marginVertical";
        p: "padding";
        pb: "paddingBottom";
        pl: "paddingLeft";
        pr: "paddingRight";
        pt: "paddingTop";
        px: "paddingHorizontal";
        py: "paddingVertical";
        r: "right";
        rounded: "borderRadius";
        select: "userSelect";
        self: "alignSelf";
        shrink: "flexShrink";
        t: "top";
        w: "width";
        z: "zIndex";
    };
    fonts: {
        body: import("@tamagui/web").FillInFont<import("@tamagui/web").GenericFont, 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16> & {
            size: {
                xs: 12;
                sm: 14;
                base: 16;
                lg: 18;
                xl: 20;
                '2xl': 24;
                '3xl': 30;
                '4xl': 36;
                '5xl': 48;
                '6xl': 60;
                '7xl': 72;
                '8xl': 96;
                '9xl': 128;
            };
            lineHeight: {
                xs: 16;
                sm: 20;
                base: 24;
                lg: 28;
                xl: 28;
                '2xl': 32;
                '3xl': 36;
                '4xl': 40;
                '5xl': 48;
                '6xl': 60;
                '7xl': 72;
                '8xl': 96;
                '9xl': 128;
            };
        };
        heading: import("@tamagui/web").FillInFont<import("@tamagui/web").GenericFont, 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16> & {
            size: {
                xs: 12;
                sm: 14;
                base: 16;
                lg: 18;
                xl: 20;
                '2xl': 24;
                '3xl': 30;
                '4xl': 36;
                '5xl': 48;
                '6xl': 60;
                '7xl': 72;
                '8xl': 96;
                '9xl': 128;
            };
            lineHeight: {
                xs: 16;
                sm: 20;
                base: 24;
                lg: 28;
                xl: 28;
                '2xl': 32;
                '3xl': 36;
                '4xl': 40;
                '5xl': 48;
                '6xl': 60;
                '7xl': 72;
                '8xl': 96;
                '9xl': 128;
            };
        };
    };
    selectionStyles: typeof import("./settings").selectionStyles;
    settings: {
        mediaQueryDefaultActive: {
            touchable: boolean;
            hoverable: boolean;
            'max-xxl': boolean;
            'max-xl': boolean;
            'max-lg': boolean;
            'max-md': boolean;
            'max-sm': boolean;
            'max-xs': boolean;
            'max-xxs': boolean;
            'max-xxxs': boolean;
            xxxs: boolean;
            xxs: boolean;
            xs: boolean;
            sm: boolean;
            md: boolean;
            lg: boolean;
            xl: boolean;
            xxl: boolean;
            'max-height-sm': boolean;
            'max-height-md': boolean;
            'max-height-lg': boolean;
            'height-sm': boolean;
            'height-md': boolean;
            'height-lg': boolean;
        };
        defaultFont: string;
        fastSchemeChange: true;
        shouldAddPrefersColorThemes: true;
        allowedStyleValues: "somewhat-strict-web";
        addThemeClassName: "html";
        onlyAllowShorthands: true;
        styleCompat: "web";
    };
} & {
    themes: {
        dark: Theme & {};
        dark_accent: Theme;
        dark_accent_level2: Theme;
        dark_accent_level2_level2: Theme;
        dark_accent_level2_level2_level2: Theme;
        dark_accent_level2_level2_level3: Theme;
        dark_accent_level2_level2_level4: Theme;
        dark_accent_level2_level3: Theme;
        dark_accent_level2_level4: Theme;
        dark_accent_level3: Theme;
        dark_accent_level3_level2: Theme;
        dark_accent_level3_level3: Theme;
        dark_accent_level3_level4: Theme;
        dark_accent_level4: Theme;
        dark_brand: Theme;
        dark_brand_level2: Theme;
        dark_brand_level2_level2: Theme;
        dark_brand_level2_level2_level2: Theme;
        dark_brand_level2_level2_level3: Theme;
        dark_brand_level2_level2_level4: Theme;
        dark_brand_level2_level3: Theme;
        dark_brand_level2_level4: Theme;
        dark_brand_level3: Theme;
        dark_brand_level3_level2: Theme;
        dark_brand_level3_level3: Theme;
        dark_brand_level3_level4: Theme;
        dark_brand_level4: Theme;
        dark_green: Theme;
        dark_green_level2: Theme;
        dark_green_level3: Theme;
        dark_green_level4: Theme;
        dark_inverse: Theme;
        dark_inverse_level2: Theme;
        dark_inverse_level2_level2: Theme;
        dark_inverse_level2_level2_level2: Theme;
        dark_inverse_level2_level2_level3: Theme;
        dark_inverse_level2_level2_level4: Theme;
        dark_inverse_level2_level3: Theme;
        dark_inverse_level2_level4: Theme;
        dark_inverse_level3: Theme;
        dark_inverse_level3_level2: Theme;
        dark_inverse_level3_level3: Theme;
        dark_inverse_level3_level4: Theme;
        dark_inverse_level4: Theme;
        dark_level2: Theme;
        dark_level2_level2: Theme;
        dark_level2_level2_level2: Theme;
        dark_level2_level2_level3: Theme;
        dark_level2_level2_level4: Theme;
        dark_level2_level3: Theme;
        dark_level2_level4: Theme;
        dark_level3: Theme;
        dark_level3_level2: Theme;
        dark_level3_level3: Theme;
        dark_level3_level4: Theme;
        dark_level4: Theme;
        dark_red: Theme;
        dark_red_level2: Theme;
        dark_red_level3: Theme;
        dark_red_level4: Theme;
        dark_yellow: Theme;
        dark_yellow_level2: Theme;
        dark_yellow_level3: Theme;
        dark_yellow_level4: Theme;
        light: Theme & {};
        light_accent: Theme;
        light_accent_level2: Theme;
        light_accent_level2_level2: Theme;
        light_accent_level2_level2_level2: Theme;
        light_accent_level2_level2_level3: Theme;
        light_accent_level2_level2_level4: Theme;
        light_accent_level2_level3: Theme;
        light_accent_level2_level4: Theme;
        light_accent_level3: Theme;
        light_accent_level3_level2: Theme;
        light_accent_level3_level3: Theme;
        light_accent_level3_level4: Theme;
        light_accent_level4: Theme;
        light_brand: Theme;
        light_brand_level2: Theme;
        light_brand_level2_level2: Theme;
        light_brand_level2_level2_level2: Theme;
        light_brand_level2_level2_level3: Theme;
        light_brand_level2_level2_level4: Theme;
        light_brand_level2_level3: Theme;
        light_brand_level2_level4: Theme;
        light_brand_level3: Theme;
        light_brand_level3_level2: Theme;
        light_brand_level3_level3: Theme;
        light_brand_level3_level4: Theme;
        light_brand_level4: Theme;
        light_green: Theme;
        light_green_level2: Theme;
        light_green_level3: Theme;
        light_green_level4: Theme;
        light_inverse: Theme;
        light_inverse_level2: Theme;
        light_inverse_level2_level2: Theme;
        light_inverse_level2_level2_level2: Theme;
        light_inverse_level2_level2_level3: Theme;
        light_inverse_level2_level2_level4: Theme;
        light_inverse_level2_level3: Theme;
        light_inverse_level2_level4: Theme;
        light_inverse_level3: Theme;
        light_inverse_level3_level2: Theme;
        light_inverse_level3_level3: Theme;
        light_inverse_level3_level4: Theme;
        light_inverse_level4: Theme;
        light_level2: Theme;
        light_level2_level2: Theme;
        light_level2_level2_level2: Theme;
        light_level2_level2_level3: Theme;
        light_level2_level2_level4: Theme;
        light_level2_level3: Theme;
        light_level2_level4: Theme;
        light_level3: Theme;
        light_level3_level2: Theme;
        light_level3_level3: Theme;
        light_level3_level4: Theme;
        light_level4: Theme;
        light_red: Theme;
        light_red_level2: Theme;
        light_red_level3: Theme;
        light_red_level4: Theme;
        light_yellow: Theme;
        light_yellow_level2: Theme;
        light_yellow_level3: Theme;
        light_yellow_level4: Theme;
    };
    tokens: {
        readonly space: {
            readonly '0': 0;
            readonly '1': 4;
            readonly '2': 8;
            readonly '3': 12;
            readonly '4': 16;
            readonly '5': 20;
            readonly '6': 24;
            readonly '7': 28;
            readonly '8': 32;
            readonly '9': 36;
            readonly '10': 40;
            readonly '11': 44;
            readonly '12': 48;
            readonly '14': 56;
            readonly '16': 64;
            readonly '20': 80;
            readonly '24': 96;
            readonly '28': 112;
            readonly '32': 128;
            readonly '36': 144;
            readonly '40': 160;
            readonly '44': 176;
            readonly '48': 192;
            readonly '52': 208;
            readonly '56': 224;
            readonly '60': 240;
            readonly '64': 256;
            readonly '72': 288;
            readonly '80': 320;
            readonly '96': 384;
            readonly px: 1;
            readonly '0-5': 2;
            readonly '1-5': 6;
            readonly '2-5': 10;
            readonly '3-5': 14;
            readonly '-px': -1;
            readonly '-0-5': -2;
            readonly '-1': -4;
            readonly '-1-5': -6;
            readonly '-2': -8;
            readonly '-2-5': -10;
            readonly '-3': -12;
            readonly '-3-5': -14;
            readonly '-4': -16;
            readonly '-5': -20;
            readonly '-6': -24;
            readonly '-7': -28;
            readonly '-8': -32;
            readonly '-9': -36;
            readonly '-10': -40;
            readonly '-11': -44;
            readonly '-12': -48;
            readonly '-14': -56;
            readonly '-16': -64;
            readonly '-20': -80;
            readonly '-24': -96;
            readonly '-28': -112;
            readonly '-32': -128;
            readonly '-36': -144;
            readonly '-40': -160;
            readonly '-44': -176;
            readonly '-48': -192;
            readonly '-52': -208;
            readonly '-56': -224;
            readonly '-60': -240;
            readonly '-64': -256;
            readonly '-72': -288;
            readonly '-80': -320;
            readonly '-96': -384;
        };
        readonly size: {
            readonly '0': 0;
            readonly '1': 4;
            readonly '2': 8;
            readonly '3': 12;
            readonly '4': 16;
            readonly '5': 20;
            readonly '6': 24;
            readonly '7': 28;
            readonly '8': 32;
            readonly '9': 36;
            readonly '10': 40;
            readonly '11': 44;
            readonly '12': 48;
            readonly '14': 56;
            readonly '16': 64;
            readonly '20': 80;
            readonly '24': 96;
            readonly '28': 112;
            readonly '32': 128;
            readonly '36': 144;
            readonly '40': 160;
            readonly '44': 176;
            readonly '48': 192;
            readonly '52': 208;
            readonly '56': 224;
            readonly '60': 240;
            readonly '64': 256;
            readonly '72': 288;
            readonly '80': 320;
            readonly '96': 384;
            readonly px: 1;
            readonly '0-5': 2;
            readonly '1-5': 6;
            readonly '2-5': 10;
            readonly '3-5': 14;
        };
        readonly radius: {
            readonly xs: 2;
            readonly sm: 4;
            readonly md: 6;
            readonly lg: 8;
            readonly xl: 12;
            readonly '2xl': 16;
            readonly '3xl': 24;
            readonly '4xl': 32;
            readonly full: 9999;
            readonly 0: 0;
            readonly 1: 3;
            readonly 2: 5;
            readonly 3: 7;
            readonly 4: 9;
            readonly 5: 10;
            readonly 6: 16;
            readonly 7: 19;
            readonly 8: 22;
            readonly 9: 26;
            readonly 10: 34;
            readonly 11: 42;
            readonly 12: 50;
        };
    } & {
        color: {
            readonly white: string;
            readonly black: string;
            readonly 'slate-50': string;
            readonly 'slate-100': string;
            readonly 'slate-200': string;
            readonly 'slate-300': string;
            readonly 'slate-400': string;
            readonly 'slate-500': string;
            readonly 'slate-600': string;
            readonly 'slate-700': string;
            readonly 'slate-800': string;
            readonly 'slate-900': string;
            readonly 'slate-950': string;
            readonly 'gray-50': string;
            readonly 'gray-100': string;
            readonly 'gray-200': string;
            readonly 'gray-300': string;
            readonly 'gray-400': string;
            readonly 'gray-500': string;
            readonly 'gray-600': string;
            readonly 'gray-700': string;
            readonly 'gray-800': string;
            readonly 'gray-900': string;
            readonly 'gray-950': string;
            readonly 'zinc-50': string;
            readonly 'zinc-100': string;
            readonly 'zinc-200': string;
            readonly 'zinc-300': string;
            readonly 'zinc-400': string;
            readonly 'zinc-500': string;
            readonly 'zinc-600': string;
            readonly 'zinc-700': string;
            readonly 'zinc-800': string;
            readonly 'zinc-900': string;
            readonly 'zinc-950': string;
            readonly 'neutral-50': string;
            readonly 'neutral-100': string;
            readonly 'neutral-200': string;
            readonly 'neutral-300': string;
            readonly 'neutral-400': string;
            readonly 'neutral-500': string;
            readonly 'neutral-600': string;
            readonly 'neutral-700': string;
            readonly 'neutral-800': string;
            readonly 'neutral-900': string;
            readonly 'neutral-950': string;
            readonly 'stone-50': string;
            readonly 'stone-100': string;
            readonly 'stone-200': string;
            readonly 'stone-300': string;
            readonly 'stone-400': string;
            readonly 'stone-500': string;
            readonly 'stone-600': string;
            readonly 'stone-700': string;
            readonly 'stone-800': string;
            readonly 'stone-900': string;
            readonly 'stone-950': string;
            readonly 'mauve-50': string;
            readonly 'mauve-100': string;
            readonly 'mauve-200': string;
            readonly 'mauve-300': string;
            readonly 'mauve-400': string;
            readonly 'mauve-500': string;
            readonly 'mauve-600': string;
            readonly 'mauve-700': string;
            readonly 'mauve-800': string;
            readonly 'mauve-900': string;
            readonly 'mauve-950': string;
            readonly 'olive-50': string;
            readonly 'olive-100': string;
            readonly 'olive-200': string;
            readonly 'olive-300': string;
            readonly 'olive-400': string;
            readonly 'olive-500': string;
            readonly 'olive-600': string;
            readonly 'olive-700': string;
            readonly 'olive-800': string;
            readonly 'olive-900': string;
            readonly 'olive-950': string;
            readonly 'mist-50': string;
            readonly 'mist-100': string;
            readonly 'mist-200': string;
            readonly 'mist-300': string;
            readonly 'mist-400': string;
            readonly 'mist-500': string;
            readonly 'mist-600': string;
            readonly 'mist-700': string;
            readonly 'mist-800': string;
            readonly 'mist-900': string;
            readonly 'mist-950': string;
            readonly 'taupe-50': string;
            readonly 'taupe-100': string;
            readonly 'taupe-200': string;
            readonly 'taupe-300': string;
            readonly 'taupe-400': string;
            readonly 'taupe-500': string;
            readonly 'taupe-600': string;
            readonly 'taupe-700': string;
            readonly 'taupe-800': string;
            readonly 'taupe-900': string;
            readonly 'taupe-950': string;
            readonly 'red-50': string;
            readonly 'red-100': string;
            readonly 'red-200': string;
            readonly 'red-300': string;
            readonly 'red-400': string;
            readonly 'red-500': string;
            readonly 'red-600': string;
            readonly 'red-700': string;
            readonly 'red-800': string;
            readonly 'red-900': string;
            readonly 'red-950': string;
            readonly 'orange-50': string;
            readonly 'orange-100': string;
            readonly 'orange-200': string;
            readonly 'orange-300': string;
            readonly 'orange-400': string;
            readonly 'orange-500': string;
            readonly 'orange-600': string;
            readonly 'orange-700': string;
            readonly 'orange-800': string;
            readonly 'orange-900': string;
            readonly 'orange-950': string;
            readonly 'amber-50': string;
            readonly 'amber-100': string;
            readonly 'amber-200': string;
            readonly 'amber-300': string;
            readonly 'amber-400': string;
            readonly 'amber-500': string;
            readonly 'amber-600': string;
            readonly 'amber-700': string;
            readonly 'amber-800': string;
            readonly 'amber-900': string;
            readonly 'amber-950': string;
            readonly 'yellow-50': string;
            readonly 'yellow-100': string;
            readonly 'yellow-200': string;
            readonly 'yellow-300': string;
            readonly 'yellow-400': string;
            readonly 'yellow-500': string;
            readonly 'yellow-600': string;
            readonly 'yellow-700': string;
            readonly 'yellow-800': string;
            readonly 'yellow-900': string;
            readonly 'yellow-950': string;
            readonly 'lime-50': string;
            readonly 'lime-100': string;
            readonly 'lime-200': string;
            readonly 'lime-300': string;
            readonly 'lime-400': string;
            readonly 'lime-500': string;
            readonly 'lime-600': string;
            readonly 'lime-700': string;
            readonly 'lime-800': string;
            readonly 'lime-900': string;
            readonly 'lime-950': string;
            readonly 'green-50': string;
            readonly 'green-100': string;
            readonly 'green-200': string;
            readonly 'green-300': string;
            readonly 'green-400': string;
            readonly 'green-500': string;
            readonly 'green-600': string;
            readonly 'green-700': string;
            readonly 'green-800': string;
            readonly 'green-900': string;
            readonly 'green-950': string;
            readonly 'emerald-50': string;
            readonly 'emerald-100': string;
            readonly 'emerald-200': string;
            readonly 'emerald-300': string;
            readonly 'emerald-400': string;
            readonly 'emerald-500': string;
            readonly 'emerald-600': string;
            readonly 'emerald-700': string;
            readonly 'emerald-800': string;
            readonly 'emerald-900': string;
            readonly 'emerald-950': string;
            readonly 'teal-50': string;
            readonly 'teal-100': string;
            readonly 'teal-200': string;
            readonly 'teal-300': string;
            readonly 'teal-400': string;
            readonly 'teal-500': string;
            readonly 'teal-600': string;
            readonly 'teal-700': string;
            readonly 'teal-800': string;
            readonly 'teal-900': string;
            readonly 'teal-950': string;
            readonly 'cyan-50': string;
            readonly 'cyan-100': string;
            readonly 'cyan-200': string;
            readonly 'cyan-300': string;
            readonly 'cyan-400': string;
            readonly 'cyan-500': string;
            readonly 'cyan-600': string;
            readonly 'cyan-700': string;
            readonly 'cyan-800': string;
            readonly 'cyan-900': string;
            readonly 'cyan-950': string;
            readonly 'sky-50': string;
            readonly 'sky-100': string;
            readonly 'sky-200': string;
            readonly 'sky-300': string;
            readonly 'sky-400': string;
            readonly 'sky-500': string;
            readonly 'sky-600': string;
            readonly 'sky-700': string;
            readonly 'sky-800': string;
            readonly 'sky-900': string;
            readonly 'sky-950': string;
            readonly 'blue-50': string;
            readonly 'blue-100': string;
            readonly 'blue-200': string;
            readonly 'blue-300': string;
            readonly 'blue-400': string;
            readonly 'blue-500': string;
            readonly 'blue-600': string;
            readonly 'blue-700': string;
            readonly 'blue-800': string;
            readonly 'blue-900': string;
            readonly 'blue-950': string;
            readonly 'indigo-50': string;
            readonly 'indigo-100': string;
            readonly 'indigo-200': string;
            readonly 'indigo-300': string;
            readonly 'indigo-400': string;
            readonly 'indigo-500': string;
            readonly 'indigo-600': string;
            readonly 'indigo-700': string;
            readonly 'indigo-800': string;
            readonly 'indigo-900': string;
            readonly 'indigo-950': string;
            readonly 'violet-50': string;
            readonly 'violet-100': string;
            readonly 'violet-200': string;
            readonly 'violet-300': string;
            readonly 'violet-400': string;
            readonly 'violet-500': string;
            readonly 'violet-600': string;
            readonly 'violet-700': string;
            readonly 'violet-800': string;
            readonly 'violet-900': string;
            readonly 'violet-950': string;
            readonly 'purple-50': string;
            readonly 'purple-100': string;
            readonly 'purple-200': string;
            readonly 'purple-300': string;
            readonly 'purple-400': string;
            readonly 'purple-500': string;
            readonly 'purple-600': string;
            readonly 'purple-700': string;
            readonly 'purple-800': string;
            readonly 'purple-900': string;
            readonly 'purple-950': string;
            readonly 'fuchsia-50': string;
            readonly 'fuchsia-100': string;
            readonly 'fuchsia-200': string;
            readonly 'fuchsia-300': string;
            readonly 'fuchsia-400': string;
            readonly 'fuchsia-500': string;
            readonly 'fuchsia-600': string;
            readonly 'fuchsia-700': string;
            readonly 'fuchsia-800': string;
            readonly 'fuchsia-900': string;
            readonly 'fuchsia-950': string;
            readonly 'pink-50': string;
            readonly 'pink-100': string;
            readonly 'pink-200': string;
            readonly 'pink-300': string;
            readonly 'pink-400': string;
            readonly 'pink-500': string;
            readonly 'pink-600': string;
            readonly 'pink-700': string;
            readonly 'pink-800': string;
            readonly 'pink-900': string;
            readonly 'pink-950': string;
            readonly 'rose-50': string;
            readonly 'rose-100': string;
            readonly 'rose-200': string;
            readonly 'rose-300': string;
            readonly 'rose-400': string;
            readonly 'rose-500': string;
            readonly 'rose-600': string;
            readonly 'rose-700': string;
            readonly 'rose-800': string;
            readonly 'rose-900': string;
            readonly 'rose-950': string;
            readonly 'brand-50': string;
            readonly 'brand-100': string;
            readonly 'brand-200': string;
            readonly 'brand-300': string;
            readonly 'brand-400': string;
            readonly 'brand-500': string;
            readonly 'brand-600': string;
            readonly 'brand-700': string;
            readonly 'brand-800': string;
            readonly 'brand-900': string;
            readonly 'brand-950': string;
            readonly 'shadow-1': 'rgba(0, 0, 0, 0.05)';
            readonly 'shadow-2': 'rgba(0, 0, 0, 0.08)';
            readonly 'shadow-3': 'rgba(0, 0, 0, 0.12)';
            readonly 'shadow-4': 'rgba(0, 0, 0, 0.16)';
            readonly 'shadow-5': 'rgba(0, 0, 0, 0.2)';
            readonly 'shadow-6': 'rgba(0, 0, 0, 0.25)';
            readonly 'shadow-7': 'rgba(0, 0, 0, 0.3)';
        };
    };
};
//# sourceMappingURL=v6.d.ts.map