name: 'Install'
description: 'Install and pre-build'
inputs:
  transcrypt_password:
    description: 'Key to unlock repo'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'

    - name: install yarn
      shell: bash
      run: npm i yarn -g

    - name: Clone Bento repository
      shell: bash
      run: |
        # Clone bento as sibling directory (required)
        cd ..
        echo "Cloning bento repository..."
        gh repo clone tamagui/bento
        cd tamagui
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Install Dependencies
      shell: bash
      run: yarn install
      env:
        # postinstall uses this (also generates bento proxy)
        TRANSCRYPT_PASSWORD: ${{ inputs.transcrypt_password }}
        SHOULD_UNLOCK_GIT_CRYPT: "1"

    - name: Build JS
      shell: bash
      run: yarn build:js