name: 'Install'
description: 'Install and pre-build'

inputs:
  workspace-focus:
    description: 'Package name to focus build on (optional)'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: 'package.json'

    - name: Get Home Dir Path
      id: get-home-dir-path
      shell: bash
      run: |
        echo "Home dir path: $HOME"
        echo "path=$HOME" >> $GITHUB_OUTPUT

    - name: Cache Bun
      uses: actions/cache@v4
      env:
        cache-name: bun_cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-

    - name: Install Dependencies
      shell: bash
      run: bun install

    - name: Build
      shell: bash
      # Run full build (including types) to ensure type definitions are available for typecheck
      run: ${{ inputs.workspace-focus && format('bunx turbo run build --filter={0}...', inputs.workspace-focus) || 'bun run build'}}

    - name: Re-link workspace bins
      shell: bash
      # Re-run install to ensure bin symlinks are created for workspace packages after build
      run: bun install
