// Generated by @tamagui/dom scripts/generate-html.ts from the tables in
// that package. Run `bun run generate:html` there after changing a table.
// Do not edit by hand.

/**
 * The events with a native equivalent reach the DOM primitives, which
 * forward or adapt each one. Tamagui otherwise drops these as web-only
 * props on native, and the primitives are what carry them.
 */
export const domEventProps: Record<string, 1> = {
  onPointerCancel: 1,
  onPointerDown: 1,
  onPointerEnter: 1,
  onPointerLeave: 1,
  onPointerMove: 1,
  onPointerOut: 1,
  onPointerOver: 1,
  onPointerUp: 1,
  onGotPointerCapture: 1,
  onLostPointerCapture: 1,
  onTouchCancel: 1,
  onTouchEnd: 1,
  onTouchMove: 1,
  onTouchStart: 1,
  onClick: 1,
  onBlur: 1,
  onFocus: 1,
  onKeyDown: 1,
  onScroll: 1,
  onMouseDown: 1,
  onMouseEnter: 1,
  onMouseLeave: 1,
  onMouseOut: 1,
  onMouseOver: 1,
  onMouseUp: 1,
  onError: 1,
  onLoad: 1,
  onChange: 1,
  onInput: 1,
}
