// Generated by @tamagui/dom scripts/generate-html.ts from the tables in
// that package. Run `bun run generate:html` there after changing a table.
// Do not edit by hand.

import type {
  StrictDOMAnchorProps,
  StrictDOMButtonProps,
  StrictDOMImageProps,
  StrictDOMInputProps,
  StrictDOMLabelProps,
  StrictDOMListItemProps,
  StrictDOMOptionGroupProps,
  StrictDOMOptionProps,
  StrictDOMProps,
  StrictDOMSelectProps,
  StrictDOMTextAreaProps,
  StrictDOMVoidProps,
} from '@tamagui/dom'

import { createComponent } from '../createComponent'
import { setComponentDisplayName } from '../helpers/componentDisplayName'
import type {
  StackNonStyleProps,
  StackStyleBase,
  StaticConfig,
  TamaguiElement,
  TamaguiTextElement,
  TextNonStyleProps,
  TextProps,
  TextStylePropsBase,
} from '../types'
import { textStaticConfig } from '../views/Text'
import type { ViewProps } from '../views/View'
import { viewStaticConfig } from '../views/View'

/**
 * `StaticConfig.Component` is typed for component values, but a literal tag
 * string is what the web frontend renders and what `createComponent` already
 * handles; `styled.a()` casts the same way.
 */
const tag = (name: string) => name as unknown as StaticConfig['Component']

/**
 * The semantic elements of the Tamagui DOM contract.
 *
 * On web each one is an ordinary Tamagui component that renders the literal
 * tag, so it takes the regular Tamagui style props as well as the strict DOM
 * props for that element. The element defaults below are the browser's own,
 * applied explicitly so a page renders the same whether or not a css reset
 * ran; `compatibility.ts` in `@tamagui/dom` records where they differ from
 * React Strict DOM and why.
 */
const a = setComponentDisplayName(
  createComponent<
    StrictDOMAnchorProps & TextProps,
    TamaguiTextElement,
    StrictDOMAnchorProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('a'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'a'
)

const article = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('article'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'article'
)

const aside = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('aside'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'aside'
)

const b = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('b'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontWeight: 'bold',
    },
  }),
  'b'
)

const bdi = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('bdi'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'bdi'
)

const bdo = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('bdo'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'bdo'
)

const blockquote = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('blockquote'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'blockquote'
)

const br = setComponentDisplayName(
  createComponent<
    StrictDOMVoidProps & TextProps,
    TamaguiTextElement,
    StrictDOMVoidProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('br'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'br'
)

const button = setComponentDisplayName(
  createComponent<
    StrictDOMButtonProps & ViewProps,
    TamaguiElement,
    StrictDOMButtonProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('button'),
    defaultProps: {
      ...viewStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      borderStyle: 'solid',
      borderWidth: 1,
    },
  }),
  'button'
)

const code = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('code'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontFamily: 'monospace',
      fontSize: '1em',
    },
  }),
  'code'
)

const del = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('del'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'line-through',
    },
  }),
  'del'
)

const div = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('div'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'div'
)

const em = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('em'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontStyle: 'italic',
    },
  }),
  'em'
)

const fieldset = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('fieldset'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'fieldset'
)

const footer = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('footer'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'footer'
)

const form = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('form'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'form'
)

const h1 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h1'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h1'
)

const h2 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h2'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h2'
)

const h3 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h3'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h3'
)

const h4 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h4'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h4'
)

const h5 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h5'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h5'
)

const h6 = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('h6'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontSize: '1.5rem',
      fontWeight: 'bold',
    },
  }),
  'h6'
)

const header = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('header'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'header'
)

const hr = setComponentDisplayName(
  createComponent<
    StrictDOMVoidProps & ViewProps,
    TamaguiElement,
    StrictDOMVoidProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('hr'),
    defaultProps: {
      ...viewStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      backgroundColor: 'black',
      height: 1,
      borderStyle: 'none',
      borderWidth: 0,
      boxSizing: 'border-box',
    },
  }),
  'hr'
)

const i = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('i'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontStyle: 'italic',
    },
  }),
  'i'
)

const img = setComponentDisplayName(
  createComponent<
    StrictDOMImageProps & ViewProps,
    TamaguiElement,
    StrictDOMImageProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('img'),
    defaultProps: {
      ...viewStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      objectFit: 'fill',
      height: 'auto',
      maxWidth: '100%',
    },
  }),
  'img'
)

const input = setComponentDisplayName(
  createComponent<
    StrictDOMInputProps & TextProps,
    TamaguiTextElement,
    StrictDOMInputProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('input'),
    isInput: true,
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      borderStyle: 'solid',
      borderWidth: 1,
    },
  }),
  'input'
)

const ins = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('ins'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'underline',
    },
  }),
  'ins'
)

const kbd = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('kbd'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontFamily: 'monospace',
      fontSize: '1em',
    },
  }),
  'kbd'
)

const label = setComponentDisplayName(
  createComponent<
    StrictDOMLabelProps & TextProps,
    TamaguiTextElement,
    StrictDOMLabelProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('label'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'label'
)

const li = setComponentDisplayName(
  createComponent<
    StrictDOMListItemProps & ViewProps,
    TamaguiElement,
    StrictDOMListItemProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('li'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'li'
)

const main = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('main'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'main'
)

const mark = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('mark'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      backgroundColor: 'yellow',
      color: 'black',
    },
  }),
  'mark'
)

const nav = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('nav'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'nav'
)

const ol = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('ol'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'ol'
)

const optgroup = setComponentDisplayName(
  createComponent<
    StrictDOMOptionGroupProps & ViewProps,
    TamaguiElement,
    StrictDOMOptionGroupProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('optgroup'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'optgroup'
)

const option = setComponentDisplayName(
  createComponent<
    StrictDOMOptionProps & TextProps,
    TamaguiTextElement,
    StrictDOMOptionProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('option'),
    defaultProps: { ...textStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'option'
)

const p = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('p'),
    defaultProps: { ...textStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'p'
)

const pre = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('pre'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      fontFamily: 'monospace',
      fontSize: '1em',
      overflow: 'auto',
    },
  }),
  'pre'
)

const s = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('s'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'line-through',
    },
  }),
  's'
)

const section = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('section'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'section'
)

const select = setComponentDisplayName(
  createComponent<
    StrictDOMSelectProps & ViewProps,
    TamaguiElement,
    StrictDOMSelectProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('select'),
    defaultProps: {
      ...viewStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      borderStyle: 'solid',
    },
  }),
  'select'
)

const span = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('span'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'span'
)

const strong = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('strong'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
      fontWeight: 'bold',
    },
  }),
  'strong'
)

const sub = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('sub'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'sub'
)

const sup = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('sup'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'none',
    },
  }),
  'sup'
)

const textarea = setComponentDisplayName(
  createComponent<
    StrictDOMTextAreaProps & TextProps,
    TamaguiTextElement,
    StrictDOMTextAreaProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('textarea'),
    isInput: true,
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      borderStyle: 'solid',
      borderWidth: 1,
    },
  }),
  'textarea'
)

const u = setComponentDisplayName(
  createComponent<
    StrictDOMProps & TextProps,
    TamaguiTextElement,
    StrictDOMProps & TextNonStyleProps,
    TextStylePropsBase
  >({
    ...textStaticConfig,
    Component: tag('u'),
    defaultProps: {
      ...textStaticConfig.defaultProps,
      margin: 0,
      padding: 0,
      textDecorationLine: 'underline',
    },
  }),
  'u'
)

const ul = setComponentDisplayName(
  createComponent<
    StrictDOMProps & ViewProps,
    TamaguiElement,
    StrictDOMProps & StackNonStyleProps,
    StackStyleBase
  >({
    ...viewStaticConfig,
    Component: tag('ul'),
    defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
  }),
  'ul'
)

export const html = {
  a,
  article,
  aside,
  b,
  bdi,
  bdo,
  blockquote,
  br,
  button,
  code,
  del,
  div,
  em,
  fieldset,
  footer,
  form,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  header,
  hr,
  i,
  img,
  input,
  ins,
  kbd,
  label,
  li,
  main,
  mark,
  nav,
  ol,
  optgroup,
  option,
  p,
  pre,
  s,
  section,
  select,
  span,
  strong,
  sub,
  sup,
  textarea,
  u,
  ul,
}
