// Generated by @tamagui/dom scripts/generate-html.ts from the tables in
// that package. Run `bun run generate:html` there after changing a table.
// Do not edit by hand.

import type {
  StrictDOMAnchorProps,
  StrictDOMButtonProps,
  StrictDOMImageProps,
  StrictDOMInputProps,
  StrictDOMLabelProps,
  StrictDOMListItemProps,
  StrictDOMOptionGroupProps,
  StrictDOMOptionProps,
  StrictDOMProps,
  StrictDOMSelectProps,
  StrictDOMTextAreaProps,
  StrictDOMVoidProps,
} from '@tamagui/dom'

import { createComponent } from '../createComponent'
import type {
  StackNonStyleProps,
  StaticConfig,
  TamaguiElement,
  TamaguiTextElement,
  TextNonStyleProps,
  WithThemeAndShorthands,
} from '../types'
import { htmlStaticConfig, htmlTextStaticConfig } from './htmlStaticConfig'
import type { TamaguiStyleProps } from './styleTypes'

/**
 * `StaticConfig.Component` is typed for component values, but a literal tag
 * string is what the web frontend renders and what `createComponent` already
 * handles.
 */
const tag = (name: string) => name as unknown as StaticConfig['Component']

/** regular Tamagui non-style props win when the strict DOM contract names the same prop */
type MergeHTMLProps<DOMProps, TamaguiProps, TamaguiNonStyleProps> = Omit<
  DOMProps,
  keyof TamaguiNonStyleProps
> &
  TamaguiProps

/**
 * The html.* style surface: the web contract from `./styleTypes` (not the
 * react-native-typed `StackStyleBase` / `TextStylePropsBase`) with theme
 * values, shorthands and clause forms, over the regular Tamagui non-style
 * props per backing kind.
 */
type HtmlStyle = WithThemeAndShorthands<TamaguiStyleProps>
type HtmlTextProps = TextNonStyleProps & HtmlStyle
type HtmlViewProps = StackNonStyleProps & HtmlStyle

/**
 * The semantic elements of the Tamagui DOM contract.
 *
 * On web each one is an ordinary Tamagui component that renders the literal
 * tag, so it takes the web style props as well as the strict DOM props for
 * that element. The element defaults below are the semantic ones, applied
 * as atomic defaults so author styles still win over them; undoing the
 * browser's own stylesheet is the zero-specificity `:where(.is_DOM)` reset
 * instead, so page CSS still reaches these hosts. `compatibility.ts` in
 * `@tamagui/dom` records where the defaults differ from React Strict DOM
 * and why.
 */
const a = createComponent<
  MergeHTMLProps<StrictDOMAnchorProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMAnchorProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('a'),
  displayName: 'a',
})

const article = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('article'),
  displayName: 'article',
})

const aside = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('aside'),
  displayName: 'aside',
})

const b = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('b'),
  displayName: 'b',
  defaultProps: { fontWeight: 'bold' },
})

const bdi = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('bdi'),
  displayName: 'bdi',
})

const bdo = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('bdo'),
  displayName: 'bdo',
})

const blockquote = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('blockquote'),
  displayName: 'blockquote',
})

const br = createComponent<
  MergeHTMLProps<StrictDOMVoidProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMVoidProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('br'),
  displayName: 'br',
})

const button = createComponent<
  MergeHTMLProps<StrictDOMButtonProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMButtonProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('button'),
  displayName: 'button',
  defaultProps: { borderWidth: 1 },
})

const code = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('code'),
  displayName: 'code',
  defaultProps: { fontFamily: 'monospace', fontSize: '1em' },
})

const del = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('del'),
  displayName: 'del',
  defaultProps: { textDecorationLine: 'line-through' },
})

const div = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('div'),
  displayName: 'div',
})

const em = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('em'),
  displayName: 'em',
  defaultProps: { fontStyle: 'italic' },
})

const fieldset = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('fieldset'),
  displayName: 'fieldset',
})

const footer = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('footer'),
  displayName: 'footer',
})

const form = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('form'),
  displayName: 'form',
})

const h1 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h1'),
  displayName: 'h1',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const h2 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h2'),
  displayName: 'h2',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const h3 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h3'),
  displayName: 'h3',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const h4 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h4'),
  displayName: 'h4',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const h5 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h5'),
  displayName: 'h5',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const h6 = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('h6'),
  displayName: 'h6',
  defaultProps: { fontSize: '1.5rem', fontWeight: 'bold' },
})

const header = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('header'),
  displayName: 'header',
})

const hr = createComponent<
  MergeHTMLProps<StrictDOMVoidProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMVoidProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('hr'),
  displayName: 'hr',
  defaultProps: {
    backgroundColor: 'black',
    height: 1,
    borderStyle: 'none',
    borderWidth: 0,
    boxSizing: 'border-box',
  },
})

const i = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('i'),
  displayName: 'i',
  defaultProps: { fontStyle: 'italic' },
})

const img = createComponent<
  MergeHTMLProps<StrictDOMImageProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMImageProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('img'),
  displayName: 'img',
  defaultProps: { objectFit: 'fill', height: 'auto', maxWidth: '100%' },
})

const input = createComponent<
  MergeHTMLProps<StrictDOMInputProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMInputProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('input'),
  displayName: 'input',
  isInput: true,
  defaultProps: { borderWidth: 1 },
})

const ins = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('ins'),
  displayName: 'ins',
  defaultProps: { textDecorationLine: 'underline' },
})

const kbd = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('kbd'),
  displayName: 'kbd',
  defaultProps: { fontFamily: 'monospace', fontSize: '1em' },
})

const label = createComponent<
  MergeHTMLProps<StrictDOMLabelProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMLabelProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('label'),
  displayName: 'label',
})

const li = createComponent<
  MergeHTMLProps<StrictDOMListItemProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMListItemProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('li'),
  displayName: 'li',
})

const main = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('main'),
  displayName: 'main',
})

const mark = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('mark'),
  displayName: 'mark',
  defaultProps: { backgroundColor: 'yellow', color: 'black' },
})

const nav = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('nav'),
  displayName: 'nav',
})

const ol = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('ol'),
  displayName: 'ol',
})

const optgroup = createComponent<
  MergeHTMLProps<StrictDOMOptionGroupProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMOptionGroupProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('optgroup'),
  displayName: 'optgroup',
})

const option = createComponent<
  MergeHTMLProps<StrictDOMOptionProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMOptionProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('option'),
  displayName: 'option',
})

const p = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('p'),
  displayName: 'p',
})

const pre = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('pre'),
  displayName: 'pre',
  defaultProps: { fontFamily: 'monospace', fontSize: '1em', overflow: 'auto' },
})

const s = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('s'),
  displayName: 's',
  defaultProps: { textDecorationLine: 'line-through' },
})

const section = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('section'),
  displayName: 'section',
})

const select = createComponent<
  MergeHTMLProps<StrictDOMSelectProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMSelectProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('select'),
  displayName: 'select',
})

const span = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('span'),
  displayName: 'span',
})

const strong = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('strong'),
  displayName: 'strong',
  defaultProps: { fontWeight: 'bold' },
})

const sub = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('sub'),
  displayName: 'sub',
})

const sup = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('sup'),
  displayName: 'sup',
})

const textarea = createComponent<
  MergeHTMLProps<StrictDOMTextAreaProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMTextAreaProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('textarea'),
  displayName: 'textarea',
  isInput: true,
  defaultProps: { borderWidth: 1 },
})

const u = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlTextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlTextStaticConfig,
  Component: tag('u'),
  displayName: 'u',
  defaultProps: { textDecorationLine: 'underline' },
})

const ul = createComponent<
  MergeHTMLProps<StrictDOMProps, HtmlViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  TamaguiStyleProps
>({
  ...htmlStaticConfig,
  Component: tag('ul'),
  displayName: 'ul',
})

export const html = {
  a,
  article,
  aside,
  b,
  bdi,
  bdo,
  blockquote,
  br,
  button,
  code,
  del,
  div,
  em,
  fieldset,
  footer,
  form,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  header,
  hr,
  i,
  img,
  input,
  ins,
  kbd,
  label,
  li,
  main,
  mark,
  nav,
  ol,
  optgroup,
  option,
  p,
  pre,
  s,
  section,
  select,
  span,
  strong,
  sub,
  sup,
  textarea,
  u,
  ul,
}
