// Generated by @tamagui/dom scripts/generate-html.ts from the tables in
// that package. Run `bun run generate:html` there after changing a table.
// Do not edit by hand.

import type {
  StrictDOMAnchorProps,
  StrictDOMButtonProps,
  StrictDOMImageProps,
  StrictDOMInputProps,
  StrictDOMLabelProps,
  StrictDOMListItemProps,
  StrictDOMOptionGroupProps,
  StrictDOMOptionProps,
  StrictDOMProps,
  StrictDOMSelectProps,
  StrictDOMTextAreaProps,
  StrictDOMVoidProps,
} from '@tamagui/dom'

import { createComponent } from '../createComponent'
import type {
  StackNonStyleProps,
  StackStyleBase,
  StaticConfig,
  TamaguiElement,
  TamaguiTextElement,
  TextNonStyleProps,
  TextProps,
  TextStylePropsBase,
} from '../types'
import { textStaticConfig } from '../views/Text'
import type { ViewProps } from '../views/View'
import { viewStaticConfig } from '../views/View'

/**
 * `StaticConfig.Component` is typed for component values, but a literal tag
 * string is what the web frontend renders and what `createComponent` already
 * handles.
 */
const tag = (name: string) => name as unknown as StaticConfig['Component']

/** regular Tamagui non-style props win when the strict DOM contract names the same prop */
type MergeHTMLProps<DOMProps, TamaguiProps, TamaguiNonStyleProps> = Omit<
  DOMProps,
  keyof TamaguiNonStyleProps
> &
  TamaguiProps

/**
 * The semantic elements of the Tamagui DOM contract.
 *
 * On web each one is an ordinary Tamagui component that renders the literal
 * tag, so it takes the regular Tamagui style props as well as the strict DOM
 * props for that element. The element defaults below are the browser's own,
 * applied explicitly so a page renders the same whether or not a css reset
 * ran; `compatibility.ts` in `@tamagui/dom` records where they differ from
 * React Strict DOM and why.
 */
const a = createComponent<
  MergeHTMLProps<StrictDOMAnchorProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMAnchorProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('a'),
  displayName: 'a',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const article = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('article'),
  displayName: 'article',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const aside = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('aside'),
  displayName: 'aside',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const b = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('b'),
  displayName: 'b',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontWeight: 'bold',
  },
})

const bdi = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('bdi'),
  displayName: 'bdi',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const bdo = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('bdo'),
  displayName: 'bdo',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const blockquote = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('blockquote'),
  displayName: 'blockquote',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const br = createComponent<
  MergeHTMLProps<StrictDOMVoidProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMVoidProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('br'),
  displayName: 'br',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const button = createComponent<
  MergeHTMLProps<StrictDOMButtonProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMButtonProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('button'),
  displayName: 'button',
  defaultProps: {
    ...viewStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    borderStyle: 'solid',
    borderWidth: 1,
  },
})

const code = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('code'),
  displayName: 'code',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontFamily: 'monospace',
    fontSize: '1em',
  },
})

const del = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('del'),
  displayName: 'del',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'line-through',
  },
})

const div = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('div'),
  displayName: 'div',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const em = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('em'),
  displayName: 'em',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontStyle: 'italic',
  },
})

const fieldset = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('fieldset'),
  displayName: 'fieldset',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const footer = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('footer'),
  displayName: 'footer',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const form = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('form'),
  displayName: 'form',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const h1 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h1'),
  displayName: 'h1',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const h2 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h2'),
  displayName: 'h2',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const h3 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h3'),
  displayName: 'h3',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const h4 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h4'),
  displayName: 'h4',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const h5 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h5'),
  displayName: 'h5',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const h6 = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('h6'),
  displayName: 'h6',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
})

const header = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('header'),
  displayName: 'header',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const hr = createComponent<
  MergeHTMLProps<StrictDOMVoidProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMVoidProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('hr'),
  displayName: 'hr',
  defaultProps: {
    ...viewStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    backgroundColor: 'black',
    height: 1,
    borderStyle: 'none',
    borderWidth: 0,
    boxSizing: 'border-box',
  },
})

const i = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('i'),
  displayName: 'i',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontStyle: 'italic',
  },
})

const img = createComponent<
  MergeHTMLProps<StrictDOMImageProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMImageProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('img'),
  displayName: 'img',
  defaultProps: {
    ...viewStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    objectFit: 'fill',
    height: 'auto',
    maxWidth: '100%',
  },
})

const input = createComponent<
  MergeHTMLProps<StrictDOMInputProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMInputProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('input'),
  displayName: 'input',
  isInput: true,
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    borderStyle: 'solid',
    borderWidth: 1,
  },
})

const ins = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('ins'),
  displayName: 'ins',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'underline',
  },
})

const kbd = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('kbd'),
  displayName: 'kbd',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontFamily: 'monospace',
    fontSize: '1em',
  },
})

const label = createComponent<
  MergeHTMLProps<StrictDOMLabelProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMLabelProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('label'),
  displayName: 'label',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const li = createComponent<
  MergeHTMLProps<StrictDOMListItemProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMListItemProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('li'),
  displayName: 'li',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const main = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('main'),
  displayName: 'main',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const mark = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('mark'),
  displayName: 'mark',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    backgroundColor: 'yellow',
    color: 'black',
  },
})

const nav = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('nav'),
  displayName: 'nav',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const ol = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('ol'),
  displayName: 'ol',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const optgroup = createComponent<
  MergeHTMLProps<StrictDOMOptionGroupProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMOptionGroupProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('optgroup'),
  displayName: 'optgroup',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const option = createComponent<
  MergeHTMLProps<StrictDOMOptionProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMOptionProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('option'),
  displayName: 'option',
  defaultProps: { ...textStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const p = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('p'),
  displayName: 'p',
  defaultProps: { ...textStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const pre = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('pre'),
  displayName: 'pre',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    fontFamily: 'monospace',
    fontSize: '1em',
    overflow: 'auto',
  },
})

const s = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('s'),
  displayName: 's',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'line-through',
  },
})

const section = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('section'),
  displayName: 'section',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

const select = createComponent<
  MergeHTMLProps<StrictDOMSelectProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMSelectProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('select'),
  displayName: 'select',
  defaultProps: {
    ...viewStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    borderStyle: 'solid',
  },
})

const span = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('span'),
  displayName: 'span',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const strong = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('strong'),
  displayName: 'strong',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
    fontWeight: 'bold',
  },
})

const sub = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('sub'),
  displayName: 'sub',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const sup = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('sup'),
  displayName: 'sup',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'none',
  },
})

const textarea = createComponent<
  MergeHTMLProps<StrictDOMTextAreaProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMTextAreaProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('textarea'),
  displayName: 'textarea',
  isInput: true,
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    borderStyle: 'solid',
    borderWidth: 1,
  },
})

const u = createComponent<
  MergeHTMLProps<StrictDOMProps, TextProps, TextNonStyleProps>,
  TamaguiTextElement,
  MergeHTMLProps<StrictDOMProps, TextNonStyleProps, TextNonStyleProps>,
  TextStylePropsBase
>({
  ...textStaticConfig,
  Component: tag('u'),
  displayName: 'u',
  defaultProps: {
    ...textStaticConfig.defaultProps,
    margin: 0,
    padding: 0,
    textDecorationLine: 'underline',
  },
})

const ul = createComponent<
  MergeHTMLProps<StrictDOMProps, ViewProps, StackNonStyleProps>,
  TamaguiElement,
  MergeHTMLProps<StrictDOMProps, StackNonStyleProps, StackNonStyleProps>,
  StackStyleBase
>({
  ...viewStaticConfig,
  Component: tag('ul'),
  displayName: 'ul',
  defaultProps: { ...viewStaticConfig.defaultProps, margin: 0, padding: 0 },
})

export const html = {
  a,
  article,
  aside,
  b,
  bdi,
  bdo,
  blockquote,
  br,
  button,
  code,
  del,
  div,
  em,
  fieldset,
  footer,
  form,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  header,
  hr,
  i,
  img,
  input,
  ins,
  kbd,
  label,
  li,
  main,
  mark,
  nav,
  ol,
  optgroup,
  option,
  p,
  pre,
  s,
  section,
  select,
  span,
  strong,
  sub,
  sup,
  textarea,
  u,
  ul,
}
