// Generated by @tamagui/dom scripts/generate-html.ts from the tables in
// that package. Run `bun run generate:html` there after changing a table.
// Do not edit by hand.

/**
 * The semantic elements of the Tamagui DOM contract, on native.
 *
 * There is no runtime here. Tag classification, native primitive injection
 * and literal text wrapping are structural rewrites the compiler performs at
 * build time, and none of them can be done while the app runs. So on native
 * the compiler is required, and reaching one of these means it did not run.
 */
const requireCompiler = (tag: string) => () => {
  throw new Error(
    `<html.${tag}> reached the runtime on native, which means the Tamagui ` +
      `compiler did not run. DOM mode is a build-time contract on native: the ` +
      `compiler classifies each tag, injects the native primitive it lowers to ` +
      `and wraps literal text, none of which can happen at runtime. Add the ` +
      `Tamagui compiler to the native build, or use the regular Tamagui ` +
      `components instead of html.*.`
  )
}

export const html = {
  a: requireCompiler('a'),
  article: requireCompiler('article'),
  aside: requireCompiler('aside'),
  b: requireCompiler('b'),
  bdi: requireCompiler('bdi'),
  bdo: requireCompiler('bdo'),
  blockquote: requireCompiler('blockquote'),
  br: requireCompiler('br'),
  button: requireCompiler('button'),
  code: requireCompiler('code'),
  del: requireCompiler('del'),
  div: requireCompiler('div'),
  em: requireCompiler('em'),
  fieldset: requireCompiler('fieldset'),
  footer: requireCompiler('footer'),
  form: requireCompiler('form'),
  h1: requireCompiler('h1'),
  h2: requireCompiler('h2'),
  h3: requireCompiler('h3'),
  h4: requireCompiler('h4'),
  h5: requireCompiler('h5'),
  h6: requireCompiler('h6'),
  header: requireCompiler('header'),
  hr: requireCompiler('hr'),
  i: requireCompiler('i'),
  img: requireCompiler('img'),
  input: requireCompiler('input'),
  ins: requireCompiler('ins'),
  kbd: requireCompiler('kbd'),
  label: requireCompiler('label'),
  li: requireCompiler('li'),
  main: requireCompiler('main'),
  mark: requireCompiler('mark'),
  nav: requireCompiler('nav'),
  ol: requireCompiler('ol'),
  optgroup: requireCompiler('optgroup'),
  option: requireCompiler('option'),
  p: requireCompiler('p'),
  pre: requireCompiler('pre'),
  s: requireCompiler('s'),
  section: requireCompiler('section'),
  select: requireCompiler('select'),
  span: requireCompiler('span'),
  strong: requireCompiler('strong'),
  sub: requireCompiler('sub'),
  sup: requireCompiler('sup'),
  textarea: requireCompiler('textarea'),
  u: requireCompiler('u'),
  ul: requireCompiler('ul'),
}
