import { type ClausePrecedenceKey, type ParsedValue } from '@tamagui/style-grammar/runtime';
import type { GetStyleState, TamaguiInternalConfig } from '../types';
export type MergeStyle = (state: GetStyleState, key: string, value: any, importance: number, disableNormalize?: boolean, originalValue?: any) => void;
type Condition = {
    source: string;
    key: string;
    active: boolean;
    emit: boolean;
    selector: string;
    parts: (number | string)[];
    wrappers?: string[];
    enter?: true;
    exit?: true;
    theme?: string;
    precedence: ClausePrecedenceKey;
    classRepetitions: number;
    flags: number;
    unsupportedState?: string;
};
type CachedFlatValue = {
    value?: ParsedValue;
    conditions?: Condition[];
    error?: string;
    flags: number;
};
export declare const FLAT_VALUE_ENTER = 1;
export declare const FLAT_VALUE_PLATFORM_PSEUDO = 2;
export declare function platformMatches(name: string): boolean;
export declare function getCachedFlatValue(conf: TamaguiInternalConfig, source: string): CachedFlatValue;
export declare function flatValueHasModifier(conf: TamaguiInternalConfig, source: string, flag: number): boolean;
export declare function directStyleSignature(property: string, value: unknown, conditionKey?: string): string;
export declare function flushDirectStyles(state: GetStyleState, clear?: boolean): void;
export declare function getDirectDynamicThemeAccess(state: GetStyleState): boolean | undefined;
export declare function contributeStyleString(state: GetStyleState, property: string, source: string, merge: MergeStyle, originalValue?: any, contextOnly?: boolean): boolean;
export declare function contributeFrontendValue(state: GetStyleState, property: string, value: ParsedValue, merge: MergeStyle, contextOnly?: boolean): boolean;
export declare function contributeVariantClauseValue(state: GetStyleState, property: string, value: any, conditionSource: string, merge: MergeStyle, originalValue?: any, contextOnly?: boolean): void;
export declare function contributeStyleValue(state: GetStyleState, property: string, value: any, merge: MergeStyle, originalValue?: any, contextOnly?: boolean): boolean;
export declare function clearDirectStyle(state: GetStyleState, property: string): void;
export {};
//# sourceMappingURL=directStyle.d.ts.map