// canonical property binding used by style resolution, grammar adapters, and tooling
export const tokenCategoryNames = [
  '',
  'space',
  'size',
  'radius',
  'zIndex',
  'color',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'lineHeight',
  'letterSpacing',
] as const

export type TokenCategoryName = Exclude<(typeof tokenCategoryNames)[number], ''>
export type TokenCategoryCode = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10

export const tokenCategorySpace = 1
export const tokenCategorySize = 2
export const tokenCategoryRadius = 3
export const tokenCategoryZIndex = 4
export const tokenCategoryColor = 5
export const tokenCategoryFontFamily = 6
export const tokenCategoryFontSize = 7
export const tokenCategoryFontWeight = 8
export const tokenCategoryLineHeight = 9
export const tokenCategoryLetterSpacing = 10

export const propToTokenCategoryCode: Readonly<Record<string, number>> = Object.freeze({
  borderRadius: tokenCategoryRadius,
  borderTopLeftRadius: tokenCategoryRadius,
  borderTopRightRadius: tokenCategoryRadius,
  borderBottomLeftRadius: tokenCategoryRadius,
  borderBottomRightRadius: tokenCategoryRadius,
  borderTopStartRadius: tokenCategoryRadius,
  borderTopEndRadius: tokenCategoryRadius,
  borderBottomStartRadius: tokenCategoryRadius,
  borderBottomEndRadius: tokenCategoryRadius,
  borderStartStartRadius: tokenCategoryRadius,
  borderStartEndRadius: tokenCategoryRadius,
  borderEndStartRadius: tokenCategoryRadius,
  borderEndEndRadius: tokenCategoryRadius,
  width: tokenCategorySize,
  height: tokenCategorySize,
  minWidth: tokenCategorySize,
  minHeight: tokenCategorySize,
  maxWidth: tokenCategorySize,
  maxHeight: tokenCategorySize,
  blockSize: tokenCategorySize,
  minBlockSize: tokenCategorySize,
  maxBlockSize: tokenCategorySize,
  inlineSize: tokenCategorySize,
  minInlineSize: tokenCategorySize,
  maxInlineSize: tokenCategorySize,
  shadowRadius: tokenCategorySize,
  zIndex: tokenCategoryZIndex,
  backgroundColor: tokenCategoryColor,
  borderColor: tokenCategoryColor,
  borderBlockStartColor: tokenCategoryColor,
  borderBlockEndColor: tokenCategoryColor,
  borderBlockColor: tokenCategoryColor,
  borderBottomColor: tokenCategoryColor,
  borderInlineColor: tokenCategoryColor,
  borderInlineStartColor: tokenCategoryColor,
  borderInlineEndColor: tokenCategoryColor,
  borderTopColor: tokenCategoryColor,
  borderLeftColor: tokenCategoryColor,
  borderRightColor: tokenCategoryColor,
  borderEndColor: tokenCategoryColor,
  borderStartColor: tokenCategoryColor,
  shadowColor: tokenCategoryColor,
  color: tokenCategoryColor,
  textDecorationColor: tokenCategoryColor,
  textShadowColor: tokenCategoryColor,
  outlineColor: tokenCategoryColor,
  ...(process.env.TAMAGUI_TARGET === 'web' && { caretColor: tokenCategoryColor }),
  placeholderTextColor: tokenCategoryColor,
  selectionColor: tokenCategoryColor,
  cursorColor: tokenCategoryColor,
  selectionHandleColor: tokenCategoryColor,
  x: tokenCategorySpace,
  y: tokenCategorySpace,
  borderWidth: tokenCategorySpace,
  borderTopWidth: tokenCategorySpace,
  borderRightWidth: tokenCategorySpace,
  borderBottomWidth: tokenCategorySpace,
  borderLeftWidth: tokenCategorySpace,
  borderBlockWidth: tokenCategorySpace,
  borderBlockStartWidth: tokenCategorySpace,
  borderBlockEndWidth: tokenCategorySpace,
  borderInlineWidth: tokenCategorySpace,
  borderInlineStartWidth: tokenCategorySpace,
  borderInlineEndWidth: tokenCategorySpace,
  outlineOffset: tokenCategorySpace,
  outlineWidth: tokenCategorySpace,
  gap: tokenCategorySpace,
  rowGap: tokenCategorySpace,
  columnGap: tokenCategorySpace,
  top: tokenCategorySpace,
  right: tokenCategorySpace,
  bottom: tokenCategorySpace,
  left: tokenCategorySpace,
  inset: tokenCategorySpace,
  insetBlock: tokenCategorySpace,
  insetBlockEnd: tokenCategorySpace,
  insetBlockStart: tokenCategorySpace,
  insetInline: tokenCategorySpace,
  insetInlineEnd: tokenCategorySpace,
  insetInlineStart: tokenCategorySpace,
  margin: tokenCategorySpace,
  marginBlock: tokenCategorySpace,
  marginBlockEnd: tokenCategorySpace,
  marginBlockStart: tokenCategorySpace,
  marginInline: tokenCategorySpace,
  marginInlineEnd: tokenCategorySpace,
  marginInlineStart: tokenCategorySpace,
  marginTop: tokenCategorySpace,
  marginRight: tokenCategorySpace,
  marginBottom: tokenCategorySpace,
  marginEnd: tokenCategorySpace,
  marginLeft: tokenCategorySpace,
  marginHorizontal: tokenCategorySpace,
  marginStart: tokenCategorySpace,
  marginVertical: tokenCategorySpace,
  padding: tokenCategorySpace,
  paddingBlock: tokenCategorySpace,
  paddingBlockEnd: tokenCategorySpace,
  paddingBlockStart: tokenCategorySpace,
  paddingInline: tokenCategorySpace,
  paddingInlineEnd: tokenCategorySpace,
  paddingInlineStart: tokenCategorySpace,
  paddingTop: tokenCategorySpace,
  paddingRight: tokenCategorySpace,
  paddingBottom: tokenCategorySpace,
  paddingEnd: tokenCategorySpace,
  paddingLeft: tokenCategorySpace,
  paddingHorizontal: tokenCategorySpace,
  paddingStart: tokenCategorySpace,
  paddingVertical: tokenCategorySpace,
  fontFamily: tokenCategoryFontFamily,
  fontSize: tokenCategoryFontSize,
  fontWeight: tokenCategoryFontWeight,
  lineHeight: tokenCategoryLineHeight,
  letterSpacing: tokenCategoryLetterSpacing,
})

export function getTokenCategoryName(code: number): TokenCategoryName | undefined {
  return tokenCategoryNames[code] || undefined
}
