import type React from "react";
import { type TextProps, type TextStyle } from "react-native";
export interface TamaguiTextProps extends TextProps {
	/**
	* Pre-computed styles for each theme, keyed by theme name.
	* Generated by the compiler at build time.
	*/
	__styles?: Record<string, TextStyle>;
}
/**
* Optimized Text component that uses pre-computed theme styles.
* The compiler generates __styles with resolved values for each theme,
* eliminating runtime style computation.
*/
export declare function _TamaguiText({ __styles, style,...props }: TamaguiTextProps): React.ReactElement;

//# sourceMappingURL=_TamaguiText.d.ts.map