import type React from "react";
import { type ViewProps, type ViewStyle } from "react-native";
interface DeduplicatedStyle extends ViewStyle {
	__themes?: string[];
}
export interface TamaguiViewProps extends ViewProps {
	/**
	* Pre-computed styles for each theme, keyed by theme name.
	* Generated by the compiler at build time.
	* Styles may be deduplicated with __themes array listing all theme names
	* that share the same style.
	*/
	__styles?: Record<string, DeduplicatedStyle>;
}
/**
* Optimized View component that uses pre-computed theme styles.
* The compiler generates __styles with resolved values for each theme,
* eliminating runtime style computation.
*
* When native-style-registry is available and native module is loaded:
* - Component renders ONCE with initial theme style
* - Theme changes update the view directly via ShadowTree
* - NO React re-renders on theme change
*
* When native module is NOT available (JS fallback):
* - Uses useThemeName() which subscribes to theme changes
* - Re-renders on theme change (same as current behavior)
*
* Supports deduplicated styles where multiple themes share the same values.
*/
export declare function _TamaguiView({ __styles, style,...props }: TamaguiViewProps): React.ReactElement;
export {};

//# sourceMappingURL=_TamaguiView.d.ts.map