export declare const shorthands: {
    text: "textAlign";
    b: "bottom";
    bg: "backgroundColor";
    content: "alignContent";
    grow: "flexGrow";
    h: "height";
    items: "alignItems";
    justify: "justifyContent";
    l: "left";
    m: "margin";
    maxH: "maxHeight";
    maxW: "maxWidth";
    mb: "marginBottom";
    minH: "minHeight";
    minW: "minWidth";
    ml: "marginLeft";
    mr: "marginRight";
    mt: "marginTop";
    mx: "marginHorizontal";
    my: "marginVertical";
    p: "padding";
    pb: "paddingBottom";
    pl: "paddingLeft";
    pr: "paddingRight";
    pt: "paddingTop";
    px: "paddingHorizontal";
    py: "paddingVertical";
    r: "right";
    rounded: "borderRadius";
    select: "userSelect";
    self: "alignSelf";
    shrink: "flexShrink";
    t: "top";
    w: "width";
    z: "zIndex";
};
export type Shorthands = typeof shorthands;
export type ShorthandKeys = keyof Shorthands;
//# sourceMappingURL=v6.d.ts.map