import { GetProps, StackProps } from '@tamagui/core';
import React from 'react';
import { ImageProps as RNImageProps } from 'react-native';
declare const StyledImage: import("@tamagui/core").StaticComponent<Exclude<keyof (ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}), never> extends never ? RNImageProps : Omit<RNImageProps, `$${string}` | keyof import("@tamagui/core").PseudoProps<any> | Exclude<keyof (ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}), never>> & {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never> & import("@tamagui/core").MediaProps<RNImageProps & {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never> & import("@tamagui/core").WithShorthands<RNImageProps & {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never>>> & import("@tamagui/core").PseudoProps<RNImageProps & {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never> & import("@tamagui/core").WithShorthands<RNImageProps & {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never>>>, {} & Omit<ParentComponent extends import("@tamagui/core").StaticComponent<void, infer V, any, import("@tamagui/core").StaticConfigParsed> ? V : {}, never>, any, import("@tamagui/core").StaticConfigParsed>;
declare type StyledImageProps = GetProps<typeof StyledImage>;
export declare type ImageProps = StackProps & Omit<StyledImageProps, 'source'> & {
    src?: string | StyledImageProps['source'];
};
export declare const Image: React.FC<ImageProps>;
export {};
//# sourceMappingURL=Image.d.ts.map