create table
  public.climb_requests (
    id integer generated by default as identity,
    profile_id uuid not null,
    climb_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint climb_requests_pkey primary key (id),
    constraint climb_requests_climb_id_fkey foreign key (climb_id) references climbs (id),
    constraint climb_requests_profile_id_fkey foreign key (profile_id) references profiles (id)
  ) tablespace pg_default;
