
create table public.climbs (
    id integer generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    type climb_type NOT NULL,
    start timestamp with time zone not null default (
      (now() at time zone 'utc'::text) + '00:05:00'::interval
    ),
    duration timestamp with time zone not null default (
      (now() at time zone 'utc'::text) + '00:35:00'::interval
    ),
    created_by uuid not null,
    constraint climbs_created_by_fkey foreign key (created_by) references profiles (id),
    constraint climbs_pkey primary key (id)
) tablespace pg_default;
