const React = require('react')

module.exports.Defs = (p) => React.createElement('defs', p)
module.exports.Ellipse = (p) => React.createElement('ellipse', p)
module.exports.G = (p) => React.createElement('g', p)
module.exports.Line = (p) => React.createElement('line', p)
module.exports.LinearGradient = (p) => React.createElement('lineargradient', p)
module.exports.Path = (p) => React.createElement('path', p)
module.exports.Polygon = (p) => React.createElement('polygon', p)
module.exports.Polyline = (p) => React.createElement('polyline', p)
module.exports.RadialGradient = (p) => React.createElement('radialgradient', p)
module.exports.Rect = (p) => React.createElement('rect', p)
module.exports.Stop = (p) => React.createElement('stop', p)
module.exports.Svg = (p) => React.createElement('svg', p)
module.exports.Symbol = (p) => React.createElement('symbol', p)
module.exports.Text = (p) => React.createElement('text', p)
module.exports.Use = (p) => React.createElement('use', p)
module.exports.Circle = (p) => React.createElement('circle', p)
