import React from 'react'

export const Circle = (p) => React.createElement('circle', p)
export const ClipPath = (p) => React.createElement('clipPath', p)
export const Defs = (p) => React.createElement('defs', p)
export const Ellipse = (p) => React.createElement('ellipse', p)
export const ForeignObject = (p) => React.createElement('foreignObject', p)
export const G = (p) => React.createElement('g', p)
export const Image = (p) => React.createElement('image', p)
export const Line = (p) => React.createElement('line', p)
export const LinearGradient = (p) => React.createElement('lineargradient', p)
export const Marker = (p) => React.createElement('marker', p)
export const Mask = (p) => React.createElement('mask', p)
export const Path = (p) => React.createElement('path', p)
export const Pattern = (p) => React.createElement('pattern', p)
export const Polygon = (p) => React.createElement('polygon', p)
export const Polyline = (p) => React.createElement('polyline', p)
export const RadialGradient = (p) => React.createElement('radialgradient', p)
export const Rect = (p) => React.createElement('rect', p)
export const Shape = (p) => React.createElement('shape', p)
export const Stop = (p) => React.createElement('stop', p)
export const Svg = (p) => React.createElement('svg', p)
export const Symbol = (p) => React.createElement('symbol', p)
export const Text = (p) => React.createElement('text', p)
export const TextPath = (p) => React.createElement('clipPath', p)
export const TSpan = (p) => React.createElement('tSpan', p)
export const Use = (p) => React.createElement('use', p)
