// Generated by dts-bundle-generator v5.9.0

export declare const isWeb: boolean;
export declare const isSSR: boolean;
export declare const useIsomorphicLayoutEffect: (effect: () => void | (() => void), deps?: any[]) => void;
export declare type WindowSize = [
	number,
	number
];
export declare function useWindowSize({ adjust, }?: {
	adjust?: (x: WindowSize) => WindowSize;
}): WindowSize;

export {};
