name: Changelog

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  tagged-release:
    name: Changelog
    runs-on: ubuntu-latest
    # needs: release
    permissions:
      contents: write

    steps:
      - uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1 # latest (archived action - consider replacing with softprops/action-gh-release)
        with:
          repo_token: '${{ github.token }}'
          prerelease: false
